### ISSUE TITLE
Mega menu sub link limit in desktop view - WET 4.0.11 Intranet Theme

### ISSUE THREAD

**Issue by boryswawryn** [wet-boew/wet-boew#6668] opened 2015-04-07 15:52 UTC
Hello
It looks like the mega menu drop down does not render beyond 26 sub items. We have one case where we have a bigger menu than that. The view/generated source includes all items but not visually. When page width is reduced and mobile navigation is used, all items appear. This happens regardless if Ajax is used or not. We are using Government of Canada Intranet v4.0.11
Thank you

**Comment by pjackson28** [comment] 2015-04-07 16:01
Looks like it is because the max-height for the submenus is set to 1000px. To actually run into that problem the menu needs to be around at least 1.5 pages long on most desktops (so requires a good amount of scrolling to see the entire submenu). We could increase the max height but why would you have a global menu that is so long? It is likely that some users would not even think to scroll down to see the rest of the menu.

**Comment by LaurentGoderre** [comment] 2015-04-07 16:10
@boryswawryn do you have a sccreenshot?

**Comment by pjackson28** [comment] 2015-04-07 16:17
Note I was able to reproduce the issue in all themes as it is a core issue (applied to <code>.wb-menu .sm.open</code>). I couldn't reach the items beyond 1000px with a mouse but could reach them with a keyboard (since it scrolls the hidden items into view within the sub-menu). When I increased the max-height then the items became available by mouse.

@thomasgohard What are your thoughts on this? Should we bump up the max-height to allow for longer sub-menus (that could span multiple screens), or should we be changing <code>overflow: hidden</code> to <code>overflow: auto</code> so a scrollbar is made available when the max-height is exceeded (in which case what should be the max-height?)?

**Comment by boryswawryn** [comment] 2015-04-07 16:39
I hear you Paul, The menus is general are reasonably short lists except for one (regions and sectors). Our menus are dynamically driven by clients.  Ideally we want to avoid forcing one unit from being removed, given that it was fine in WET3.x. We will propose solutions to the client if need be.

**Comment by pjackson28** [comment] 2015-04-07 16:50
It would be better to have a link in the menu to a regions and sectors page rather than putting them all in a submenu. It will be much easier for users to navigate such a long list of options in the content area than in a submenu (likely much more usable). I would suspect that any regions/sectors that are not visible without scrolling would be harder to find. Also you are likely to overwhelm the users with so many options in a menu system.

**Comment by boryswawryn** [comment] 2015-04-07 17:18
Thanks for the feedback. We contacted the client for an IA review.

**Comment by hsrudnicki** [comment] 2015-06-17 14:02
Are you ready to close this issue?

**Comment by boryswawryn** [comment] 2015-06-17 14:30
closed now. Thanks

>>> On 6/17/2015 at 10:02 AM, in message <wet-boew/wet-boew/issues/6668/112812263@github.com>, hsrudnicki <notifications@github.com> wrote:

Are you ready to close this issue?

**Closed** 2015-06-17 14:30 UTC
Labels: Plugin: Menu, Theme: Intranet
