### ISSUE TITLE
Calendar of Events: single letters for days of the week 

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#6971] opened 2015-07-23 16:18 UTC
Can we expand the days of the week from single letters to either full words such as "Monday, tuesday etc) or at least 3 character abbreviations such as "MON, TUE, WED etc)?

this will provide necessary context for blind/low bvision at users.

@wet-boew/access-working-group

**Comment by LaurentGoderre** [comment] 2015-07-23 17:02
It uses abbreviation tags for the full name of the day of the week. It isn't sufficient?

**Comment by pjackson28** [comment] 2015-07-23 17:04
@SBleeks The current solution uses the <code>abbr</code> element to provide an expansion for those letters (e.g., <code>&lt;abbr title="Thursday"&gt;T&lt;/abbr&gt;</code>). Is the expansion not being read to you?

Now it may be possible to go to three letters using the same approach (e.g., <code>&lt;abbr title="Thursday"&gt;Thu&;lt/abbr&gt;</code>) but there could be some spacing issues since the days of the month are maximum two characters long and the days of the week would be three. Nonetheless it may help users to more easily recognize visually which is Saturday and which is Sunday.

@masterbee @thomasgohard What are your thoughts on this?

**Comment by dfarough** [comment] 2015-07-23 18:07
I have tried setting Jaws to speak both abbreviations and acronyms.  Only the One character day letter is spoken when using table navigation keys to move through the table.  If the specified day in the table contains a link, then the full date with appropriate day is spoken.  If there is no link specified for the date then jaws will speak the one character day from the table column followed by blank.

I should point out that the date picker from the wet 4.0 examples does not conform to the  ARIA guidelines because even when I turn off the virtual cursor in Jaws I can not use up or down arrows to move back or forward by a week as required.

**Comment by LaurentGoderre** [comment] 2015-07-23 18:10
I just tested it and the up and down arrow behave as expected, perhaps the AT you are using in interfering with it? Perhaps we need role=application?

**Comment by pjackson28** [comment] 2015-07-23 18:28
It is bizarre that Jaws does not respect the <code>abbr</code> tag in that case. Regardless of mode it should still read it off.  Will you be filing a bug for that? As a possible workaround, maybe we could hide the rest of the word with CSS or hide the expanded form after the letter(s) with CSS (so forgoing the abbr element). Although this would really be a dirty solution as we would be going against WCAG conventions for abbreviations and acronyms (we should be using HTML semantics, not CSS tricks).

As for why the up and down arrows are not working in Jaws, it is because Jaws is not turning on applications mode automatically (because it does not support the WAI-ARIA region that we are using). With NVDA on the other hand, it does support the WAI-ARIA region so switches into focus mode which has the up and down arrow support. So the problem is not that the date picker doesn't meet the WAI-ARIA date picker spec, it is that Jaws is not supporting the WAI-ARIA date picker spec in this case.

As for role="application", that is where we fall into the NVDA vs. Jaws issues. Both NVDA and Jaws treat role="application" very differently. NVDA treats it like a black box (can't navigate in normally) while Jaws just treats it as a trigger for the forms/applications mode. This is an issue because Jaws doesn't support all the WAI-ARIA regions like NVDA does. This means that our current solution works well in NVDA but not Jaws and if we add role="application" then it will work well in Jaws but not NVDA.

I think there was one way around this problem, where we move focus into the application region for the user, which would work for both Jaws and NVDA. That may work fine for the date picker dialog, but would not work well for the calendar of events. That is because with the date picker dialog you don't navigate in normally, you activate a button and then are moved into the date picker (so fits the workaround scenario). With the calendar of events, the user is supposed to navigate in normally (tabbing, arrowing, etc.) which means the workaround scenario won't apply meaning using role="application" will result in a black box in NVDA (broken support) while it would work fine in Jaws.

So role="application" likely will work fine for the date picker dialog but I don't see what we can do about the calendar of events considering how inconsistent NVDA and Jaws are on this (up to this point we have lived with Jaws being broken on this).

**Comment by dfarough** [comment] 2015-07-23 18:51
Role = application is exactly what I have been asking for for some time now
polyfill (date picker): Can we redesign the calendar? #6705 
Input type="date" polyfill (date picker): arrow keys do not work as expected in the calendar grid of days  #6670 
.

**Comment by SBleeks** [comment] 2015-07-23 19:02
Enabling the JAWS  screen reader setting to identify abbreviations has solved this issue for me.  Even when navigating the table using the (Ctrl/Alt +arrow keys), the day of the week is properly referenced using JAWS screen reader.

NVDA screen reader requires the user to expand the abbr tag using Insert/numpad 5, as outlined in NVDA community ticket ##3828 (NVDA doesn't recognize abbr html tag) – NVDA Community:
http://community.nvda-project.org/ticket/3828

thanks.

**Comment by hsrudnicki** [comment] 2015-08-12 13:19
@LaurentGoderre and others : Can be this issue solved and closed or otherwise?

**Comment by hsrudnicki** [comment] 2015-09-24 19:19
Please update this issue's status

**Comment by hsrudnicki** [comment] 2016-03-09 19:54
Is this still an outstanding issue?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by dfarough** [comment] 2016-03-10 14:54
This issue has been addressed.

**Comment by LaurentGoderre** [comment] 2016-03-10 14:55
Has it? I don't remember fixing this

**Comment by dfarough** [comment] 2016-03-10 15:10
I am wondering if your change to the date picker has modified this behaviour.  I notice that when I move into the calendar, that Jaws is seeing it as an application.  I tried this with NVDA as well and I have not noticed any issues.

In any case I am hearing the day as I use the arrows to change the date.

**Comment by LaurentGoderre** [comment] 2016-03-10 15:45
However, this issue was more about the visual representation of the day of the week for the table, which is not used when you navigate the calendar but mostly only used when visually navigating the calendar.

**Comment by SBleeks** [comment] 2016-03-10 15:49
For this specific issue: the abbr tag is used and the AT needs to have ‘read abbr tags” enabled.  If so, the days of the week are read as full words.


Stacy Bleeks

Web Accessibility Expert - Centre of Expertise on Accessibility | Operations Branch
Statistics Canada | Government of Canada
Stacy.Bleeks@canada.ca<mailto:Stacy.Bleeks@canada.ca> / Tel: 613-951-6137

Expert en accessibilité  - Centre d'expertise en accessibilité | Direction des opérations
Statistique Canada | Gouvernement du Canada
Stacy.Bleeks@canada.ca<mailto:Stacy.Bleeks@canada.ca> / Tél : 613-951-6137

**Comment by dfarough** [comment] 2016-03-10 18:31
There are a couple of issues here that can lead to confusion.

If a user chooses to navigate the calendar grid using the conventional table navigation keys (control + alt + Right, Left, Up or Down arrow keys) they will hear the column header character spoken for that day of the week followed by the value for the cell in the grid.  For Jaws users there are options to enable the speaking of abbreviations.  By default these options have never been enabled so the user needs to be aware of this capability and where to find the setting.

When the calendar gains the focus, The focus or application role takes over.  using the arrow keys will move from date to date within the calendar grid.  the access technology should speak the value for the link within the grid.  However, if a date within the grid is out of range the focus will not change and no indication of this is provided.

**Comment by LaurentGoderre** [comment] 2016-03-10 19:04
The out of range is a separate issue. WOuld you say that the redesign, along with `role=application1` solves this issue?

**Comment by dfarough** [comment] 2016-03-10 20:16
Yes.  Assuming that the user is aware of how to enable the speaking of abbreviations in their access technology. You have done all you can to present this information.  Any cells that contain links do not rely on the abbr tag to display this information either.

**Closed** 2016-03-11 13:16 UTC
Labels: Plugin: Calendar of Events
