### ISSUE TITLE
Problem with the left menu. Version:  GoC.WebTemplate 4.0.21.2

### ISSUE THREAD

**Issue by ghost** [wet-boew/wet-boew#7643] opened 2016-08-23 12:06 UTC
The second level of the left menu is showing "Selected" for more than one file.

It should be associated only with the file "Documents.aspx" but it is also "selected" when displaying the file "DocumentsUpload.aspx".

Here is the code that I am using to generate the left menu in both pages:

``` vb
Dim oMenuSection As MenuSection = New MenuSection()

' Level 1
oMenuSection.Name = "Financial Transaction"
oMenuSection.Link = "FinancialTransaction.aspx"

' Level 2
oMenuSection.Items.Add(New MenuItem("ReviewersSignatories.aspx", "Reviewers and Signatories"))
oMenuSection.Items.Add(New MenuItem("Documents.aspx", "Supporting Documents"))
oMenuSection.Items.Add(New MenuItem("HistoricalVersions.aspx", "Historical Versions"))

' Add Menu Section
Page.WebTemplateMaster.WebTemplateCore.LeftMenuItems.Add(oMenuSection)
```

FYI, When removing the breadcrumbs in both pages, this problem disappear.

Thank you

![file_1](https://cloud.githubusercontent.com/assets/21176705/17891187/43e99192-6908-11e6-98dd-40cde8306962.png)
![file_2](https://cloud.githubusercontent.com/assets/21176705/17891188/43f46612-6908-11e6-87a2-39f32e77aac5.png)

**Comment by rlambert27** [comment] 2016-09-01 14:40
Just to mention that this also fails on GCWeb.

**Comment by shawnthompson** [comment] 2016-09-01 15:20
Looks like it might be a problem with the [navcurrent plugin](https://github.com/wet-boew/wet-boew/tree/master/src/plugins/navcurrent).

**Comment by Fu22yWu22y** [comment] 2016-09-07 19:23
We did a Temp  work around and added this to a custom css file 

#wb-sec .list-group .list-group .list-group .wb-navcurr.list-group-item {
    background-color: #335075;
}

**Comment by hsrudnicki** [comment] 2016-09-12 20:36
Can be this closed as resolved or otherwise? Please update the status of this again, whether this remains still an issue or otherwise, thx

**Comment by shawnthompson** [comment] 2016-09-21 14:15
We can't close this one, I'd like to solve the problem in the JS and not have to override it with CSS just to mask the issue. If anyone can solve the problem, I can commit it to WET if they want.

BTW @Fu22yWu22y do you have a bear?

**Comment by kpduncan** [comment] 2016-09-21 15:15
I believe it has something to do with this line of code `$elm.trigger( navCurrentEvent, breadcrumb );` in the `wet-boew.js` if commented it no longer marks the menu item current, but affects all pages.

**Comment by kpduncan** [comment] 2016-09-21 16:13
If the current URL don't match a main menu `href` value WET well loop all the `href` values in the breadcrumb. When a breadcrumb `href` is match to a menu item it well mark it current based on the main menu order. Here is the code that causes the issue in the `wet-boew.js`:
```javascript
						for ( i = 0; i !== len; i += 1 ) {
							link = localBreadcrumbLinks[ i ];
							linkHref = link.getAttribute( "href" );
							console.dir(linkHref);
							if ( linkHref.length !== 0 && linkHref.charAt( 0 ) !== "#" ) {
								localBreadcrumbLinksArray.push( link );
								localBreadcrumbLinksUrlArray.push( link.hostname + link.pathname.replace( /^([^\/])/, "/$1" ) );
							}
						}
```

**Comment by kpduncan** [comment] 2016-09-21 16:38
@shawnthompson Please let me know what you think of my latest update (not sure it notifies you when you edit a post).

**Comment by cybersubtype** [comment] 2016-09-26 14:12
Well this be update?

**Comment by shawnthompson** [comment] 2016-09-29 00:41
@ghost or @cybersubtype, do either of you want to make the change to the actual WET plugin and submit a PR? I can show you how via WebEx session. We are looking for more people to collaborate on the project.

**Comment by cybersubtype** [comment] 2016-09-29 11:07
FYI ghost is a deleted account (the one above is mine actually). I wouldn't mind.

**Comment by rlambert27** [comment] 2016-11-18 15:45
Any ideas why the PR was closed? Ideally this needs to be in the v4.0.23 release!

**Comment by LaurentGoderre** [comment] 2016-11-18 15:51
@rlambert27 it probably won't be in v4.0.23

**Comment by kodecount** [comment] 2016-11-18 16:03
@rlambert27 @LaurentGoderre Here a updated version of the fix:

```javascript
if ( len ) {
link = localBreadcrumbLinks[ len - 1 ];
child = link.firstChild;
linkHref = ( child && child.nodeName === "A" ) ? child.getAttribute( "href" ) : "";
if ( linkHref && linkHref.charAt( 0 ) !== "#" ) {
localBreadcrumbLinksArray.push( child );
localBreadcrumbLinksUrlArray.push( child.hostname + child.pathname.replace( /^([^\/])/, "/$1" ) );
}
}
```

**Comment by duboisp** [comment] 2017-01-24 03:42
@shawnthompson any update?

(for reference #7747 was related to this request)

**Comment by shawnthompson** [comment] 2017-01-24 13:34
I have no idea... the ghost account is confusing me and I'm not even 100% I understand the problem so it's hard for me to test. @kodecount want to take this over for me?

**Comment by kodecount** [comment] 2017-01-24 13:43
The problem is when WET was getting the links via:

`localBreadcrumbLinks = ( breadcrumb.jquery ? breadcrumb[ 0 ] : breadcrumb ).getElementsByTagName( "a" );`

It sometimes ignored when a user choice to make the last breadcrumb not a link. That was one issue. Second issue is `for ( i = 0; i !== len; i += 1 ) {...}` issue with looping was it was comparing the entire breadcrumb to the current URL. The issue with this is it creates false positive cause only the last link or text in the bread should be related to the current URL.

Hence why we need to use:

`localBreadcrumbLinks = ( breadcrumb.jquery ? breadcrumb[ 0 ] : breadcrumb ).getElementsByTagName( "li" );`

So we get all breadcrumbs and just look at the last item in the list.

**Comment by kodecount** [comment] 2017-01-24 13:48
For example in this image from above:
![image](https://cloud.githubusercontent.com/assets/23484460/22249564/eb46a1ac-e219-11e6-9b8b-78fe4c7d5e91.png)

The `Category Manager` in the menu URL is `www.example.com/category-manger/` when we are on `www.example.com/category-manger/add` it marks that item in the menu as active, but their is no menu link for `www.example.com/category-manger/add`

**Comment by kodecount** [comment] 2017-01-24 13:49
Also ghost account is when a USER has left GitHub the original commenter of this issue was not me and left GitHub before a solution was found.

**Comment by kodecount** [comment] 2017-01-24 13:53
Some just needs to create a pull request using code from https://github.com/wet-boew/wet-boew/issues/7643#issuecomment-261568426 which should replace [Line 79-86](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/navcurrent/navcurrent.js#L79)

Also at [Line 77](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/navcurrent/navcurrent.js#L77) replace it with:

`localBreadcrumbLinks = ( breadcrumb.jquery ? breadcrumb[ 0 ] : breadcrumb ).getElementsByTagName( "li" );`

**Comment by shawnthompson** [comment] 2017-01-24 15:36
@kodecount can you do a PR with the changes or verify that the changes I did in my branch is sufficient?

https://github.com/shawnthompson/wet-boew/commit/53c2e8028aa3a0d990981504f1c9dac87a00cd08

If so, I'll rebase and put in a PR. 

Thanks

**Comment by kodecount** [comment] 2017-01-24 17:07
Their was changes @dubosip wanted ages ago to the code you have. You can see the changes here:

https://github.com/kodecount/wet-boew/commit/72df780dcf7426257751698c2b1dc4665bb1dbae

No I won't make a PR (I trying to restrain from it when possible).

**Comment by kodecount** [comment] 2017-01-24 17:18
Also here is one more example within WET it self:

Before Patch:
![before_patch](https://cloud.githubusercontent.com/assets/23484460/22258329/8c794c42-e237-11e6-9531-d05723ac92c1.png)

After Patch:
![after_patch](https://cloud.githubusercontent.com/assets/23484460/22258335/92274130-e237-11e6-9e5c-7b1a4cd32c5b.png)

**Comment by duboisp** [comment] 2017-01-24 17:25
Awsome @kodecount 

@shawnthompson do you think you are able to [cherry pick](https://git-scm.com/docs/git-cherry-pick) @kodecount commit and submit a PR?

**Comment by shawnthompson** [comment] 2017-01-24 18:49
Here you go

https://github.com/wet-boew/wet-boew/pull/7859

**Comment by duboisp** [comment] 2017-01-25 01:24
Thanks @shawnthompson and @kodecount for your work on this

**Closed** 2017-01-25 01:23 UTC
Labels: Bug Report: Major
