### ISSUE TITLE
Huge space on top of body section

### ISSUE THREAD

**Issue by seguinrs** [wet-boew/wet-boew#7077] opened 2015-09-03 17:58 UTC
Why is there a huge space on top of the body section.

Thanks
Roger
![space](https://cloud.githubusercontent.com/assets/14113912/9666415/e623c7e8-5243-11e5-84f6-5dbb7ef9309c.png)

**Comment by LaurentGoderre** [comment] 2015-09-03 17:59
I believe this is caused by the margin from the h1

**Comment by seguinrs** [comment] 2015-09-03 18:01
Will this be fixed ?

**Comment by LaurentGoderre** [comment] 2015-09-03 18:02
It can be....

**Comment by seguinrs** [comment] 2015-09-03 18:03
What do I need to do???

**Comment by LaurentGoderre** [comment] 2015-09-03 19:34
It needs to be fixed in the theme

**Comment by seguinrs** [comment] 2015-09-04 11:22
Ok, is that your group that will fix this?

**Comment by seguinrs** [comment] 2015-09-16 12:51
Who will fix this issue in the theme?
Where we at?

**Closed** 2015-09-17 14:20 UTC

**Comment by seguinrs** [comment] 2015-09-17 14:25
Hi Laurent,

The issue is not resolved at my end, doesn’t this take time to replicate?

Thanks
Roger

**Comment by LaurentGoderre** [comment] 2015-09-17 14:41
Yes, It can take up to 20 minutes for it to be updated.

**Comment by LaurentGoderre** [comment] 2015-09-17 14:53
It is updated now: http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/index-en.html

**Comment by seguinrs** [comment] 2015-09-17 15:55
Hi Laurent,

There is still a space.
Here is the source:

Roger
[cid:image001.png@01D0F13F.CCB45B70]

**Comment by LaurentGoderre** [comment] 2015-09-17 16:27
You will need to add the image in Github, it doesn't work with email.

**Comment by seguinrs** [comment] 2015-09-17 16:33
![space](https://cloud.githubusercontent.com/assets/14113912/9939435/2b15d2b6-5d38-11e5-8dbe-f30ca6e783b7.jpg)

**Comment by seguinrs** [comment] 2015-09-17 16:37
Here is the source since the issue is still there.

Thanks



<!DOCTYPE html>
<html id="ctl00_Html1" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head id="ctl00_Head1"><title>
	Log in
</title>

    
	  <meta charset="utf-8">
         
        
         <meta content="width=device-width,initial-scale=1" name="viewport">
         
<meta name="dc.title" content="VSCA Virtual Services Centre Aviation" /><meta name="dcterms.language" content="eng" /><meta name="dcterms.subject" content="VSCA Virtual Services Centre Aviation" /><meta name="dcterms.creator" content="Application Development and Technology Management" /><meta name="dcterms.modified" content="2015-06-22" /><meta name="dcterms.issued" content="2015-06-22" />
		 
         
         <link href="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/assets/favicon.ico" rel="icon" type="image/x-icon">
         <link rel="stylesheet" href="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/css/wet-boew.min.css">
         
         <link rel="stylesheet" href="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/css/theme.min.css">
         
         <noscript>
            <link rel="stylesheet" href="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/css/noscript.min.css" />
         </noscript>
         <link rel="stylesheet" href="http://www.tc.gc.ca/wet-boew/v4/overrides.css">
	
 
<script type="text/javascript" src="../../Scripts/javascript.js" charset="windows-1252"></script></head>
<body>
    
		<ul id="wb-tphp">
            <li class="wb-slc">
               <a class="wb-sl" href="#wb-cont">Skip to main content</a>
            </li>
            <li class="wb-slc visible-sm visible-md visible-lg">
               <a class="wb-sl" href="#wb-info">Skip to "About this site"</a>
            </li>
            <li class="wb-slc visible-md visible-lg">
               <a class="wb-sl" href="#wb-sec">Skip to section menu</a>
            </li>
         </ul>
         <header role="banner">
            <div id="wb-bnr">
               <div id="wb-bar">
                  <div class="container">
                     <div class="row">
                        <object id="gcwu-sig" type="image/svg+xml" tabindex="-1" role="img" data="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/assets/sig-en.svg" aria-label="Government of Canada"></object>
                        <ul id="gc-bar" class="list-inline">
                           <li><a href="http://www.canada.ca/en/index.html" rel="external">Canada.ca</a></li>
                           <li><a href="http://www.canada.ca/en/services/index.html" rel="external">Services</a></li>
                           <li><a href="http://www.canada.ca/en/gov/dept/index.html" rel="external">Departments</a></li>
                           <li id="wb-lng">
                              <h2>Language selection</h2>
                              <ul class="list-inline">
                                 <li><a lang="fr" href="http://localhost:4023/Account_Compte/Login_Ouverture.aspx?lang=fra">Français</a></li>
                              </ul>
                           </li>
                        </ul>
                        <section class="wb-mb-links col-xs-12 visible-sm visible-xs" id="wb-glb-mn">
                           <h2>Search and menus</h2>
                           <ul class="pnl-btn list-inline text-right">
                              <li><a href="#mb-pnl" title="Search and menus" aria-controls="mb-pnl" class="overlay-lnk btn btn-sm btn-default" role="button"><span class="glyphicon glyphicon-search"><span class="glyphicon glyphicon-th-list"><span class="wb-inv">Search and menus</span></span></span></a></li>
                           </ul>
                           <div id="mb-pnl"></div>
                        </section>
                     </div>
                  </div>
               </div>
               <div class="container">
                  <div class="row">
                     <div id="wb-sttl" class="col-md-5">
                        <a href="http://www.tc.gc.ca/eng/menu.htm">
                        <span>Transport Canada</span>
                        </a>
                     </div>
                     <object id="wmms" type="image/svg+xml" tabindex="-1" role="img" data="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/assets/wmms.svg" aria-label="Symbol of the Government of Canada"></object>
                     <section id="wb-srch" class="visible-md visible-lg">
                        <h2>Search</h2>
                        <form action="http://search-recherche.tc.gc.ca/search.aspx" method="get" role="search" class="form-inline">
                           <div class="form-group">
                              <label for="wb-srch-q">Search website</label>
                              <input id="wb-srch-q" class="form-control" name="q" type="search" value="" size="27" maxlength="150">
                           </div>
                           <button type="submit" id="wb-srch-sub" class="btn btn-default">Search</button>
                        </form>
                     </section>
                  </div>
               </div>
            </div>
            <nav role="navigation" id="wb-sm" data-ajax-fetch="https://www.tc.gc.ca/wcms-sgcw/v4/includes/en/sitemenu.html" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
               <div class="container nvbar">
                  <h2>Topics menu</h2>
                  <div class="row">
                     <ul class="list-inline menu">
                        <li><a href="http://www.tc.gc.ca/eng/air-menu.htm">Air</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/marine-menu.htm">Marine</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/rail-menu.htm">Rail</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/road-menu.htm">Road</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/safety-menu.htm">Safety</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/security-menu.htm">Security</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/environment-menu.htm">Environment</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/innovation-menu.htm">Innovation</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/resources-menu.htm">Resources</a></li>
                        <li><a href="http://www.tc.gc.ca/eng/regions.htm">Regions</a></li>
                     </ul>
                  </div>
               </div>
            </nav>
            <nav role="navigation" id="wb-bc" property="breadcrumb">
               <h2>You are here:</h2>
               <div class="container">
                  <div class="row">
                     <ol class="breadcrumb">
                        <li>
                           <a href="http://www.tc.gc.ca/eng/menu.htm">Home</a>
                        </li>                  
<li><a href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/">Virtual Service Centre</a></li><li>Log in</li>
	  
					</ol>
                  </div>
               </div>
            </nav>
         </header>

		
         <div class="container">
            <div class="row">
               
			    <main role="main" property="mainContentOfPage" class="col-md-9 col-md-push-3">
			   
                  <h1 id="wb-cont" property="name">Log in</h1>
    <form name="aspnetForm" method="post" action="Login_Ouverture.aspx" onsubmit="javascript:return WebForm_OnSubmit();" id="aspnetForm" class="indent-none margin-right-none">
<div>
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE4NDI5ODE5NTVkZPsMDzkyt94Kajiltkw7XpOfHYs88gyvZRVRHvZ3+gvG" />
</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>


<script src="/WebResource.axd?d=my0JGtw7PjeImOMA7mOo9kXr5kuL9025c8RLiSVDmzVRQ7IHtbbmgJTCfI6h4l5T5m_hEvImA-gla85hA03rXcJRoSMl72b4ZlZIJzUd4OM1&amp;t=635586505120000000" type="text/javascript"></script>


<script src="/WebResource.axd?d=vYxaG_IxCO3cbeF2NjBEREGDxsH_f2Imesv06mq1j7MvUCAKVnrLofET9Bwq9Dj6T0JB33HyNdcr32ieIC48b9XT5BpX8di1_WGWcvyCyF41&amp;t=635586505120000000" type="text/javascript"></script>
<script src="/WebResource.axd?d=iUo8yygVxTFKRf57WEt6-HC4d2qqEJCE3c-dwaLU0l-XF0T9ruuxz_zMaQPTFV7VPv5DW7wUUGtaaSQSCSrpInRq0YAc1PLfbWmjCDqn6CU1&amp;t=635586505120000000" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
function WebForm_OnSubmit() {
if (typeof(ValidatorOnSubmit) == "function" && ValidatorOnSubmit() == false) return false;
return true;
}
//]]>
</script>

<div>

	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdABT/sRZknZrog03OQdLJ+oMGn/q62cputSStM69AjVs3VAwoLPrf1pUFeEctN5c/U8gqA/0AeAt92pciIIRALlokWVXHc59OuPoHlcNIGYHC1gb0ShdPuvJsJ+G1k7H+On2NBd3zmyuU9FjruTW6NVR79JP7zYLA8IL10TdlvRGv1nnOhsPoGTI8j/EYiJ54jkUsChoAI1u3TFACXkbzghIe/oIdjqXHZpdWQTox7fPUwcl7Dc3Gsts9DxVH7uSPQ9Ud6YWC/EeK/uDz0NmlM4fKk7Ip7AHhaEsZGIgp8sGred6FyEQyXujZsCZ2078OPRwRjfspnIl2iVbxIfYJiGTWvZLyH/661ox6L0qZH9FbJGmg8neJLTVFn73MYWF3q+nhsxmLhwHf1NwlrdOFqc3L0iFCRxNcq0mCahva3fxDtchlHN3wmE8j644LFkvAxNZ+d99K5J9bjO5K05wcekTi" />
</div>
    <div id="divContent">
        
    <div id="ctl00_ContentPlaceHolder1_c1_vsErreurs" style="color:Red;display:none;">

</div>
<p>
    
</p>
<div>
    
    <p>
        <span id="ctl00_ContentPlaceHolder1_c1_lblBienvenue"><b>Welcome to the Virtual Services Centre for Aviation</b></span>
    </p>
    <p>
        <span id="ctl00_ContentPlaceHolder1_c1_lblnote">Thank you for using the Quebec Region's Virtual Services Centre for Aviation.<br /><br /> It will give you access to the full range of services offered to the industry along with <a href='http://www.tc.gc.ca/eng/civilaviation/standards/commerce-circulars-ac0213-1697.htm' target='fenetre' title="Opens up in a new browser window">service level standards</a>.<br /><br /> <span style="font-weight:blod;"><b>Instructions</b></span><br />Select the service of your choice and fill in the online application form. Upon completion, an acknowledgement of receipt will be sent to you by email.<br/><br/>You will then be required to send Transport Canada the appropriate documentation. A Transport Canada representative will later contact you when the services you have requested have been carried out.</span>
    </p>
    <div id="ctl00_ContentPlaceHolder1_c1_panLogin" onkeypress="javascript:return WebForm_FireDefaultButton(event, &#39;ctl00_ContentPlaceHolder1_c1_btnSauvegarder&#39;)">
	
        <p>
            <span id="ctl00_ContentPlaceHolder1_c1_lblImportant"><span id="par_important"><strong>Attention</strong><b> : If you are air operator, choose code 5258 and enter your file number. If you are an ACP, choose code 5802 and enter your licence number without the letters.</b></span> <br /><br /></span>
        </p>
        <p>
            <span>
                </span></p>
        <div>
            <span id="ctl00_ContentPlaceHolder1_c1_lblLogin"><b></b></span>
            <div>
                <fieldset>
                    <legend>
                        <span id="ctl00_ContentPlaceHolder1_c1_lbltitre"><Strong>Please identify yourself</Strong></span></legend>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_ddlLogin" id="ctl00_ContentPlaceHolder1_c1_UserNameLabel">Code</label>
                        </div>
                        <div class="col-md-4">
                            <select name="ctl00$ContentPlaceHolder1$c1$ddlLogin" id="ctl00_ContentPlaceHolder1_c1_ddlLogin">
		<option value="5258">5258 -</option>
		<option value="5802">5802 -</option>

	</select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <span id="ctl00_ContentPlaceHolder1_c1_rfv03" class="text-danger" style="color:Red;display:none;">Please enter a valid file number (9999)</span>
                            <span id="ctl00_ContentPlaceHolder1_c1_rev01" class="text-danger" style="color:Red;display:none;">Please enter a valid file number (9999)</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_UserName" id="ctl00_ContentPlaceHolder1_c1_UserFileLicense">File/license <b>(required)</b>:</label>
                        </div>
                        <div class="col-md-2">
                            <input name="ctl00$ContentPlaceHolder1$c1$UserName" type="text" maxlength="8" id="ctl00_ContentPlaceHolder1_c1_UserName" class="full-width" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_Password" id="ctl00_ContentPlaceHolder1_c1_PasswordLabel">Password <b>(required)</b>:</label><br />
                        </div>
                        <div class="col-md-2">
                            <input name="ctl00$ContentPlaceHolder1$c1$Password" type="password" maxlength="8" id="ctl00_ContentPlaceHolder1_c1_Password" class="full-width" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <span id="ctl00_ContentPlaceHolder1_c1_rfv02" class="text-danger" style="color:Red;display:none;">Please enter the password</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="ctl00_ContentPlaceHolder1_c1_dpListProvince" id="ctl00_ContentPlaceHolder1_c1_lblProvince">Province or territory:</label>
                        </div>
                        <div class="col-md-4">
                            <select name="ctl00$ContentPlaceHolder1$c1$dpListProvince" id="ctl00_ContentPlaceHolder1_c1_dpListProvince">
		<option value="1">Newfoundland and Labrador</option>
		<option value="2">Prince Edward Island</option>
		<option value="3">Nova Scotia</option>
		<option value="4">New Brunswick</option>
		<option selected="selected" value="5">Quebec</option>
		<option value="6">Ontario</option>
		<option value="7">Manitoba</option>
		<option value="8">Saskatchewan</option>
		<option value="9">Alberta</option>
		<option value="10">British Columbia</option>
		<option value="11">Yukon</option>
		<option value="12">Northwest Territories</option>
		<option value="13">Nunavut</option>

	</select>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="row mrgn-tp-md">
                <div class="col-md-12">
                    <input type="button" name="ctl00$ContentPlaceHolder1$c1$LinkButton1" value="Clear" onclick="javascript:__doPostBack(&#39;ctl00$ContentPlaceHolder1$c1$LinkButton1&#39;,&#39;&#39;)" id="ctl00_ContentPlaceHolder1_c1_LinkButton1" />
                    <input type="submit" name="ctl00$ContentPlaceHolder1$c1$btnSauvegarder" value="Submit" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$c1$btnSauvegarder&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))" id="ctl00_ContentPlaceHolder1_c1_btnSauvegarder" />
                </div>
            </div>
            <div class="row mrgn-tp-md">
                <div class="col-md-3">
                    <a href="/Account_Compte/Login_Ouverture.aspx?oubli=mdp">
                        <span id="ctl00_ContentPlaceHolder1_c1_Label1">Forgotten Password</span></a>
                </div>
            </div>
        </div>
    
</div>
</div>


    </div>
    
<script type="text/javascript">
//<![CDATA[
var Page_ValidationSummaries =  new Array(document.getElementById("ctl00_ContentPlaceHolder1_c1_vsErreurs"));
var Page_Validators =  new Array(document.getElementById("ctl00_ContentPlaceHolder1_c1_rfv03"), document.getElementById("ctl00_ContentPlaceHolder1_c1_rev01"), document.getElementById("ctl00_ContentPlaceHolder1_c1_rfv02"));
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
var ctl00_ContentPlaceHolder1_c1_vsErreurs = document.all ? document.all["ctl00_ContentPlaceHolder1_c1_vsErreurs"] : document.getElementById("ctl00_ContentPlaceHolder1_c1_vsErreurs");
ctl00_ContentPlaceHolder1_c1_vsErreurs.headertext = "<span class=\'Entete\'>One or several errors were found</span>";
var ctl00_ContentPlaceHolder1_c1_rfv03 = document.all ? document.all["ctl00_ContentPlaceHolder1_c1_rfv03"] : document.getElementById("ctl00_ContentPlaceHolder1_c1_rfv03");
ctl00_ContentPlaceHolder1_c1_rfv03.controltovalidate = "ctl00_ContentPlaceHolder1_c1_UserName";
ctl00_ContentPlaceHolder1_c1_rfv03.focusOnError = "t";
ctl00_ContentPlaceHolder1_c1_rfv03.errormessage = "<a class=\"lien_erreur\" href=\"#ctl00$ContentPlaceHolder1$c1$UserName\">Please enter a valid file number (9999)</a>";
ctl00_ContentPlaceHolder1_c1_rfv03.display = "Dynamic";
ctl00_ContentPlaceHolder1_c1_rfv03.evaluationfunction = "RequiredFieldValidatorEvaluateIsValid";
ctl00_ContentPlaceHolder1_c1_rfv03.initialvalue = "";
var ctl00_ContentPlaceHolder1_c1_rev01 = document.all ? document.all["ctl00_ContentPlaceHolder1_c1_rev01"] : document.getElementById("ctl00_ContentPlaceHolder1_c1_rev01");
ctl00_ContentPlaceHolder1_c1_rev01.controltovalidate = "ctl00_ContentPlaceHolder1_c1_UserName";
ctl00_ContentPlaceHolder1_c1_rev01.errormessage = "<a class=\"lien_erreur\" href=\"#ctl00$ContentPlaceHolder1$c1$UserName\">Please enter a valid file number (9999)</a>";
ctl00_ContentPlaceHolder1_c1_rev01.display = "Dynamic";
ctl00_ContentPlaceHolder1_c1_rev01.evaluationfunction = "RegularExpressionValidatorEvaluateIsValid";
ctl00_ContentPlaceHolder1_c1_rev01.validationexpression = "^[0-9]*$";
var ctl00_ContentPlaceHolder1_c1_rfv02 = document.all ? document.all["ctl00_ContentPlaceHolder1_c1_rfv02"] : document.getElementById("ctl00_ContentPlaceHolder1_c1_rfv02");
ctl00_ContentPlaceHolder1_c1_rfv02.controltovalidate = "ctl00_ContentPlaceHolder1_c1_Password";
ctl00_ContentPlaceHolder1_c1_rfv02.errormessage = "<a class=\"lien_erreur\" href=\"#ctl00$ContentPlaceHolder1$c1$Password\">Please enter the password</a>";
ctl00_ContentPlaceHolder1_c1_rfv02.display = "Dynamic";
ctl00_ContentPlaceHolder1_c1_rfv02.evaluationfunction = "RequiredFieldValidatorEvaluateIsValid";
ctl00_ContentPlaceHolder1_c1_rfv02.initialvalue = "";
//]]>
</script>


<script type="text/javascript">
//<![CDATA[

var Page_ValidationActive = false;
if (typeof(ValidatorOnLoad) == "function") {
    ValidatorOnLoad();
}

function ValidatorOnSubmit() {
    if (Page_ValidationActive) {
        return ValidatorCommonOnSubmit();
    }
    else {
        return true;
    }
}
        WebForm_AutoFocus('UserName');//]]>
</script>
</form>
    
				<div class="clearfix"></div>
                  <dl id="wb-dtmd">
                     <dt>Date modified:&#32;</dt>
                     <dd><time property="dateModified">2015-07-16</time></dd>
                  </dl>
               </main>		

			<nav role="navigation" id="wb-sec" typeof="SiteNavigationElement" class="col-md-3 col-md-pull-9 visible-md visible-lg">
				<h2>Section menu</h2>
				
				<ul class="list-group menu list-unstyled">
					
					<li>
						<h3 class="wb-navcurr">Transport Canada Virtual Services Center (TCVSC)</h3>
						<ul class="list-group menu list-unstyled">
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC_CSVTC/login" title="">Log out</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/welcome" title="">Welcome</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/dashboard" title="">My dashboard</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/profile" title="">My Personal Profile</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/payment/Index" title="">Make a Payment</a></li>
						</ul>
					</li>
					
		
	  <li>
<h3 class="wb-navcurr"><abbr title='VSCA Virtual Services Centre Aviation'>VSCA</abbr></h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item"  href="/Account_Compte/Login_Ouverture.aspx" title="">Log in</a></li><li><a class="list-group-item"  href="/Account_Compte/PasswordRecovery_RecupererMotDePasse.aspx" title="">Forgotten password</a></li><li><a class="list-group-item"  href="/Registrations_Inscriptions/Registration_Inscription.aspx" title="">VSCA Registration</a></li><li><a class="list-group-item"  href="/Account_Compte/ContactUs_ContactezNous.aspx" title="">Contact Us</a></li>
	  </ul>
		
					
					<li>
						<h3 class="wb-navcurr">E-services catalog</h3>
						<ul class="list-group menu list-unstyled">
              <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/enrollService/search" title="">Search for an E-Service</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/enrollService/Air" title="">Air E-services</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/enrollService/Marine" title="">Marine E-services</a></li>
			        <li><a class="list-group-item" href="#" title="">Road E-services</a></li>
			        <li><a class="list-group-item" href="#" title="">Rail E-services</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/enrollService/AllByMode" title="">All Transport Canada E-services by Mode</a></li>
			        <li><a class="list-group-item" href="http://cawwwappsv/Saf-Sec-Sur/2/TCVSC/eng/enrollService/AllAToZ" title="">All Transport Canada E-services A-Z</a></li>
						</ul>
					</li>
					
				</ul>
			</nav>
			
		
	  
	   </div>
         </div>
		 <footer role="contentinfo" id="wb-info" class="visible-sm visible-md visible-lg wb-navcurr">
            <div class="container">
               <nav role="navigation">
                  <h2>About this site</h2>
                  <ul id="gc-tctr" class="list-inline">
                     <li><a rel="license" href="http://www.tc.gc.ca/eng/notices.htm">Terms and conditions</a></li>
                     <li><a href="http://www.tc.gc.ca/eng/aboutus-disclosure.htm">Transparency</a></li>
                  </ul>
                  <div class="row">
                     <section class="col-sm-3">
                        <h3><a href="http://www.tc.gc.ca/eng/aboutus-menu.htm">About us</a></h3>
                        <ul class="list-unstyled">
                           <li><a href="http://www.tc.gc.ca/eng/aboutus-department-overview.htm">Our Mandate</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/minister-menu.htm">The Minister</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/aboutus-department-menu.htm">Organizational Structure</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/publications-menu.htm">Publications</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/site-menu.htm">Site Map</a></li>
                        </ul>
                     </section>
                     <section class="col-sm-3">
                        <h3><a href="http://www.tc.gc.ca/eng/mediaroom/menu.htm">News</a></h3>
                        <ul class="list-unstyled">
                           <li><a href="http://news.gc.ca/web/dsptch-dstrbr-en.do?mthd=advSrch&#38;crtr.dpt1D=6695&#38;crtr.tp1D=1">News Releases</a></li>
                           <li><a href="http://news.gc.ca/web/dsptch-dstrbr-en.do?mthd=advSrch&#38;crtr.dpt1D=6695&#38;crtr.tp1D=970">Speeches</a></li>
                           <li><a href="http://news.gc.ca/web/dsptch-dstrbr-en.do?mthd=advSrch&#38;crtr.dpt1D=6695&#38;crtr.tp1D=3">Media Advisories</a></li>
                           <li><a href="http://news.gc.ca/web/dsptch-dstrbr-en.do?mthd=advSrch&#38;crtr.dpt1D=6695&#38;crtr.tp1D=930">Backgrounders</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/mediaroom/photos-menu.htm">Photo Gallery</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/mediaroom/video-menu.htm">Video Gallery</a></li>
                        </ul>
                     </section>
                     <section class="col-sm-3">
                        <h3><a href="http://www.tc.gc.ca/eng/contact-us.htm">Contact us</a></h3>
                        <ul class="list-unstyled">
                           <li><a href="http://www.tc.gc.ca/eng/service-feedback-613.html">Service Feedback</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/contact-us.htm#general">Address</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/contact-us.htm#freq">Telephone Numbers</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/contact-us.htm#freq">Emails</a></li>
                           <li><a href="http://sage-geds.tpsgc-pwgsc.gc.ca/cgi-bin/direct500/eng/XEou%3dTC-TC%2co%3dGC%2cc%3dCA">Find an Employee</a></li>
                        </ul>
                     </section>
                     <section class="col-sm-3">
                        <h3><a href="http://www.tc.gc.ca/eng/mediaroom/socialmedia-menu.htm">Stay connected</a></h3>
                        <ul class="list-unstyled">
                           <li><a href="http://www.facebook.com/pages/Transport-Canada/401846167974">Facebook</a></li>
                           <li><a href="http://youtube.com/transportcanada">YouTube</a></li>
                           <li><a href="http://twitter.com/transport_gc">Twitter</a></li>
                           <li><a href="http://www.flickr.com/photos/transportcanada">Flickr</a></li>
                           <li><a href="http://www.tc.gc.ca/eng/feeds.htm">Web Feeds</a></li>
                           <li><a href="http://wwwapps.tc.gc.ca/Comm/5/ListServ/Menu.aspx?lang=eng">Subscribe to E-news</a></li>
                        </ul>
                     </section>
                  </div>
               </nav>
            </div>
            <div id="gc-info">
               <div class="container">
                  <nav role="navigation">
                     <h2>Government of Canada footer</h2>
                     <ul class="list-inline">
                        <li><a href="http://healthycanadians.gc.ca"><span>Health</span></a></li>
                        <li><a href="http://travel.gc.ca"><span>Travel</span></a></li>
                        <li><a href="http://www.servicecanada.gc.ca/eng/home.shtml"><span>Service Canada</span></a></li>
                        <li><a href="http://www.jobbank.gc.ca"><span>Jobs</span></a></li>
                        <li><a href="http://actionplan.gc.ca/en"><span>Economy</span></a></li>
                        <li id="canada-ca"><a href="http://www.canada.ca/en/index.html">Canada.ca</a></li>
                     </ul>
                  </nav>
               </div>
            </div>
         </footer>
         
         <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
         <script src="http://www.tc.gc.ca/wet-boew/v4/theme-gcwu-fegc/js/wet-boew.min.js"></script>
         
         

</body>
</html>

**Comment by LaurentGoderre** [comment] 2015-09-17 16:46
Did you update your CSS?

**Comment by seguinrs** [comment] 2015-09-17 16:48
Which CSS?

**Comment by LaurentGoderre** [comment] 2015-09-17 16:52
Your page is pointing to a local copy of WET, you need to update it to get the changes made.

**Comment by seguinrs** [comment] 2015-09-17 16:57
No, I am pointing to  tc.gc.ca, let’s see if the TC Webgroup can update the files.

Joshua,  can you update the files, do you need more information?

Thanks
Roger

**Comment by LaurentGoderre** [comment] 2015-09-17 16:59
The fix is only available in dev right now, it will be included in v4.0.18

**Comment by seguinrs** [comment] 2015-09-17 17:17
Thanks

Who will look into the 7079 issue?

Roger

**Comment by LaurentGoderre** [comment] 2015-09-17 17:29
I don't know, I'm just a volunteer on this project

**Comment by seguinrs** [comment] 2015-09-17 17:32
Ok, Is Mario B. in charge of the project?

**Comment by LaurentGoderre** [comment] 2015-09-17 17:32
Yeah

**Comment by seguinrs** [comment] 2015-09-17 17:32
Merci

**Comment by seguinrs** [comment] 2015-12-02 17:27
This was only fixed in the internal template, the external template is still broken.
