### ISSUE TITLE
Legend tag Float:left

### ISSUE THREAD

**Issue by StdGit** [wet-boew/wet-boew#7766] opened 2016-11-16 18:20 UTC
@thomasgohard

Is there a special reason why tag Legend is floating left ?

legend { 
   border-bottom: 0; 
  **float: left;**
 } 

If you add a tag like fieldset after it, it will be right aligned

https://github.com/wet-boew/wet-boew/commit/42a76b1bffa30b3103542892b23f4cbf6ca5d14a

https://github.com/wet-boew/wet-boew/blob/a5b906efd6b5cc2d74167d53da9bbe02b4150b11/src/base/bootstrap-overrides/_base.scss#L601

**Comment by kodecount** [comment] 2016-11-16 18:42
It because [Line 609](https://github.com/wet-boew/wet-boew/blob/a5b906efd6b5cc2d74167d53da9bbe02b4150b11/src/base/bootstrap-overrides/_base.scss#L609) doesn't work other wise.

**Comment by kodecount** [comment] 2016-11-16 19:05
What about using:

```css
legend {
  margin-bottom: 0;
}

legend:after {
    border-bottom: 1px solid #e5e5e5;
    content: "";
    display: block;
}
```
This well create a border under the legend title if we really need the border?

**Comment by kodecount** [comment] 2016-11-16 19:17
Here what it would look like with the updated code:

![border_update](https://cloud.githubusercontent.com/assets/23484460/20361878/8edb6d34-ac0f-11e6-90e1-ec6e5dde2fcb.png)

[Line 599-602 and 609-610](https://github.com/wet-boew/wet-boew/blob/a5b906efd6b5cc2d74167d53da9bbe02b4150b11/src/base/bootstrap-overrides/_base.scss#L599) would need to be removed and replaced with above code.

**Comment by kodecount** [comment] 2016-11-16 19:18
@StdGit What do you think?

**Comment by StdGit** [comment] 2016-11-16 22:17
@kodecount 
It is ok with me if it doesn't break anything else.
Thx for your help

**Comment by kodecount** [comment] 2016-11-16 22:56
@StdGit Started the pull request to fix this.

**Comment by duboisp** [comment] 2016-11-17 14:14
@cfarquharson 
* Do you have any comment about removing ```float:left``` to ```legend``` element?
* What do you think of having the border under the legend instead at the top?

:smiley:

**Comment by kodecount** [comment] 2016-11-17 14:16
@duboisp To have it on the top if desired just need to change `legend:after` to `legend:before` personally don't think `float:left` was the best way to get a border.

**Comment by StdGit** [comment] 2016-11-17 14:24
@duboisp @kodecount  
It's ok with me to remove the Float:Left and I prefer the border under the legend

**Comment by duboisp** [comment] 2016-11-17 15:28
@kodecount it is better if you can reproduce the same visual styling as it was because otherwise doing that change would require to do an impact analysis.

@StdGit I understand your preference

So let me suggest to add new class for the legend in order to set the border under it instead of having it at the top by defaults. Then the [WET style guide](http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html) would require to be updated in order to documents that new styling class.

**Comment by kodecount** [comment] 2016-11-17 15:47
@duboisp I've updated the pull request to reflect on what you mentioned.

**Comment by kodecount** [comment] 2016-11-22 17:18
@StdGit At the end of the day looks like were are keeping `float: left`, but instead when using an alternate class it well set it to `float: none;`

**Comment by kodecount** [comment] 2016-11-23 13:35
@StdGit @duboisp The pull request has been update. Were using the `<fieldset>` to create the top border and changing the `<legend>` display type so the top border appears above it instead of through it (standard web design/look). With the class `.legend-brdr-bttm` the `<fieldset>` border-top is set to 0 and the legend is given the border instead.

**Comment by kodecount** [comment] 2016-11-25 13:16
@StdGit Through out this process I found out the the `float: left;` is required due to the way Firefox treats `fieldsets`, so it looks as if we won't be able to remove it.

**Comment by StdGit** [comment] 2016-11-25 13:19
@kodecount ok Thx to have looking at this issue.

**Comment by kodecount** [comment] 2016-11-25 13:31
@StdGit Possibility that when using the `.legend-brdr-bttm` class we can set `float: none;` on the legend.

**Comment by duboisp** [comment] 2016-12-07 14:35
Closing since PR #7771 is merged.

How to apply the bottom border is documented here: http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#fieldset

**Comment by shawnthompson** [comment] 2017-04-19 13:55
Found a new issue with the float on legend. I'll open a new issue and refer this closed one... my bad. Sorry for the emails.

**Closed by shawnthompson** 2017-04-19 13:55 UTC
Labels: Core: CSS
