### ISSUE TITLE
Menu (Nested Menu Items) FireFox 49+ Issue

### ISSUE THREAD

**Issue by joshdevries** [wet-boew/wet-boew#7717] opened 2016-10-26 20:57 UTC
http://wet-boew.github.io/v4.0-ci/demos/menu/menu-en.html

Ever since FireFox has updated to version 49, the Menu plugin is no longer styled correctly when there are nested items in the menu.

The chevrons are missing and there is an odd border around items now.

We have two different implementations of WET we are working with: the standard theme, and the intranet theme and they both have the same issue.

We are on version: v4.0.22-development - 2016-05-17

![menupluginnotworking](https://cloud.githubusercontent.com/assets/5933765/19744726/b93f0adc-9b9c-11e6-98b8-28a33a06ca41.png)

**Comment by LaurentGoderre** [comment] 2016-10-27 11:43
I don't think nested sub menu items are supported by WET

**Comment by kodecount** [comment] 2016-10-27 11:46
Sub-menus are in the [WET Docs](https://wet-boew.github.io/wet-boew/demos/menu/menu-en.html) the issue is Firefox no longer provides a icon for the details and summary tags.

**Comment by LaurentGoderre** [comment] 2016-10-27 11:56
Huh! I didn't know we added this in.

**Comment by LaurentGoderre** [comment] 2016-10-27 11:58
Maybe it's an issue with thatv theme because it works in the examples

![submenu](https://cloud.githubusercontent.com/assets/1090826/19766297/1503d996-9c1b-11e6-8ce0-f68fdfcbc73d.PNG)

**Comment by kodecount** [comment] 2016-10-27 12:36
@LaurentGoderre It seems to be fixed in this version `v4.0.23-development - 2016-10-26`

**Comment by LaurentGoderre** [comment] 2016-10-27 13:50
I look at all the changes since last version that fixed this, but perhaps there was something in v4.0.22 that did (he's ona development build)

@joshdevries can you update to the released version of 4.0.22?

**Comment by kodecount** [comment] 2016-10-27 14:58
@LaurentGoderre I ran a quick test with intranet theme seems to be working with `v4.0.22 - 2016-08-11`

**Comment by joshdevries** [comment] 2016-10-27 15:01
I'll try and update and let you know. Might be a day or 2 though.

**Comment by joshdevries** [comment] 2016-10-27 15:35
I am also using the standard theme and I have the same result.

**Comment by joshdevries** [comment] 2016-10-27 15:35
You have them in the WET documentation in the menu plugin.

**Comment by joshdevries** [comment] 2016-10-27 15:37
We have one person on our team with Firefox 48 still they have no issues,
Firefox r 49 is when it stopped working correctly. Interestingly enough,
for the first time since the early 90's IE is working better than Firefox
on something because it still work's there.

**Comment by kodecount** [comment] 2016-10-27 15:39
There was a small Firefox update sent out v49.0.2.

**Comment by LaurentGoderre** [comment] 2016-10-27 16:35
and is it still there for Firefox 50?

**Comment by kodecount** [comment] 2016-10-27 16:56
@LaurentGoderre Firefox 50 still in development.

**Comment by LaurentGoderre** [comment] 2016-10-27 17:40
I'm on 51 and it seem to works. I wonder if there was an incomplete implementation of details/summary that caused this

**Comment by kodecount** [comment] 2016-10-27 17:50
@LaurentGoderre Not sure check out www.cybersubtype.ca with version `v4.0.21 - 2016-04-12` and it broken.

**Comment by joshdevries** [comment] 2016-10-28 15:53
@LaurentGoderre  @kodecount  I attempted an update, to 4.0.22 and the problem remains the same on FireFox 49

**Comment by kodecount** [comment] 2016-10-28 16:24
@LaurentGoderre Could this be a conflict with Firefox? Looks like they added details and summary support in [Version 49](https://developer.mozilla.org/en-US/Firefox/Releases/49).

**Comment by joshdevries** [comment] 2016-10-28 16:29
Its interesting that this is the first version they added support for it. is there a polyfill or something in WET for Firefox that might be conflicting? I'm guessing IE will be adding support soon as well, might have the same issue: http://caniuse.com/#feat=details

**Comment by kodecount** [comment] 2016-10-28 16:36
@joshdevries I can't confirm, but I believe WET has a poly-fill for details and summary elements, but it only suppose to work if browser has no support. At least that what I understand. @LaurentGoderre Thoughts?

**Comment by EricDunsworth** [comment] 2016-11-02 18:33
The CSS overrides older versions of WET use for details/summary arrows don't play nicely in versions of Firefox that have native details/summary support. Native support is enabled by default in Firefox 49.0+. It's also present in 47-48 in a disabled state (can be manually enabled by going to about:config and setting dom.details_element.enabled is to true).

For years, Webkit/Blink were the only browser rendering engines with native support for details/summary. Since no spec existed at the time on how summary arrow CSS should be handled, their arrows were implemented via a non-standard pseudo-element (``summary::-webkit-details-marker``).

WET's native details/summary CSS was originally designed within that context. It used some CSS overrides to set summary to ``display: block;`` and its polyfill implemented the arrows in Firefox/IE/etc via ``summary::before {content: \25BC\a0;}``. Webkit/Blink's arrows appear fine with that setup.

In recent months, as development of Firefox's native details/summary support advanced, whatwg/html#722 was opened. As a result, [WHATWG's HTML spec was updated to state that summary elements should be styled as list items](https://github.com/whatwg/html/issues/722#issuecomment-188576457). Firefox's native details/summary currently implements that part of the spec. Blink hasn't implemented the "new" way of doing it yet, but eventually will via [Chromium issue 590014](https://bugs.chromium.org/p/chromium/issues/detail?id=590014).

But... wait a sec. What happens when a list items are styled to ``display: block;``? Their bullets disappear. So in older versions of WET, all summary arrows stopped appearing in Firefox 49.0+.

Anyway, I fixed it in #7569 (when JS is enabled), which benefited the mega menu. It's built-into the production version of WET 4.0.22. But it isn't present in the 2016-05-17 development version of 4.0.22. My PR was merged in on 2016-06-21.

I also added noscript support in #7685. A few more adjustments are still needed to support wbdisable and a few rare scenarios. I'll try to get to them in the coming days.

**Comment by LaurentGoderre** [comment] 2016-11-02 19:06
Wow! That's amazing @EricDunsworth nice answer!

**Comment by EricDunsworth** [comment] 2016-11-02 20:03
@LaurentGoderre Thanks :).

Anyway, from what I can tell, #7569 has already fixed the mega menu issues that were covered in the OP.

**Comment by joshdevries** [comment] 2016-11-03 16:43
Nice! thanks for taking the time. Really interesting read :)

Will this be in the next release?

**Comment by EricDunsworth** [comment] 2016-11-03 17:01
@joshdevries It's already part of the production version of 4.0.22, which came out on August 9th. It's not in development versions of 4.0.22 that predate June 21st.

**Comment by joshdevries** [comment] 2016-11-03 17:43
... I forgot to add the new CSS files!! haha well at least this is a good record in case someone else has the same issues. Thanks for your help @EricDunsworth

**Comment by kodecount** [comment] 2016-11-03 17:54
@joshdevries Glad to hear it all working. Don't forget to close the issue. It'll still be available for anyone who needs the reference.

**Closed** 2016-11-03 17:55 UTC
