### ISSUE TITLE
Validating whether two <input> field values match?

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6436] opened 2015-01-12 14:57 UTC
I was looking through the "Form Validation" working example but I could not find any way to check whether two <input> field values match. For example, say I have an "E-mail" input box and then another for "Please re-type your e-maill address" and I want to ensure both contain the same content. How would I use WET Form Validation to accomplish this or is it not possible? I would rather avoid having to include separate validation functionality.

**Comment by CalvinRodo** [comment] 2015-01-12 17:32
Wet uses the [Jquery Validation plugin](http://jqueryvalidation.org/documentation/) to handle client side validation so you can read their documentation to see how to do this client side. 



I should add that I highly recommend you also do the validation on the server side as you can never be sure the user didn't just bypass your JavaScript validation and is posting whatever they want to the server. 

For email though I think you can probably get away from having to do the email matching as long as you send them a validation email to properly ensure the email address works.

**Comment by josephbr** [comment] 2015-01-12 21:22
I already plan to include a server side check. My primary concern is that I cannot achieve the same look/feel as the other validation types (i.e. as seen on http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html where it highlights the field containing the error, labels it, and also displays the error at the top of the screen).

**Comment by LaurentGoderre** [comment] 2015-01-12 21:39
@josephbr I believe the plugin allows for custom validation rules that integrate with the other ones.

**Comment by CalvinRodo** [comment] 2015-01-13 14:00
@josephbr I highly recommend you read the documentation for the jquery validation plugin that i posted
you'd see that one of the standard rules that they provide is http://jqueryvalidation.org/equalTo-method
which according to the documentation is **Requires the element to be the same as another one** so you wouldn't even have to write any custom rules you can just use what is built in.

**Comment by josephbr** [comment] 2015-01-13 14:02
Validating the data should be no problem but the part I am unsure about is how to display the error so that it uses the same look/feel where the field is outlined and the error appears beside it and at the top of the page. What function call was invoked to display the error?

**Comment by CalvinRodo** [comment] 2015-01-13 16:49
I personally haven't looked too much into it I figured it would just work but I guess if there isn't a rule defined for that or messages defined for that rule it won't just work. 

I'd then look into [the documentation for the Validate() method](http://jqueryvalidation.org/validate), it seems you can pass back a list of messages that will appear if the error occurs 

I believe the plugin should add the correct markup to the error and the field and the validation summary should pick up and linkify anything that is marked up with the correct syntax. 

If it doesn't add the correct markup to the field item you'll have to do it yourself, look at issue #6281 for the correct markup needed, I know for a fact that if you have the plugin enabled and markup your field with that code the validation summary will appear and linkify the field

**Comment by CalvinRodo** [comment] 2015-01-13 17:05
I will add I would be very interested in how you accomplish this as we have a plan to move ROEWeb to client side validation in the near future and most of the validation will be done using complex custom rules.

**Comment by pjackson28** [comment] 2015-01-13 17:30
You probably should just use [addMethod](http://jqueryvalidation.org/jQuery.validator.addMethod) as the Validate() method will have already been called by WET. It should allow you to create whatever custom validation you like and the errors will be handled through the same interface just like every other method. You should wait until the wb-ready event before calling it to ensure the validator instance is ready.

**Comment by LaurentGoderre** [comment] 2015-01-13 17:48
One thing to take into consideration is the loading of custom i18n strings. This is a use case that we need to investigate as part of the core

**Comment by CalvinRodo** [comment] 2015-01-13 17:50
@LaurentGoderre  I know in my case we don't change languages client side only server side so we would serve up a file with french strings vs english strings based on the language of the page. Client side code should stay the same except for the file we read the strings out of.

**Comment by pjackson28** [comment] 2015-01-13 18:04
Even in the absence of a central approach, it is easy to specify language-specific strings through the client-side with a simple conditional. I'm not sure how a central language method could be a benefit in this case though when implementers will be injecting the message through a static jQuery Validation method (bypassing WET language handling altogether).

**Comment by LaurentGoderre** [comment] 2015-01-13 18:09
Conditional for i18n might work in this case but it does not help for multilingual sites or big amount of strings. There should be a way to provide your custom i18n strings in the same fashion as the core one

**Comment by pjackson28** [comment] 2015-01-13 18:43
The problem is that the message strings and the addMethod are all jQuery validation. For i18n, all WET does is load the appropriate jQuery validation i18n file which just overrides the addMethod calls (with English messages) that come as part of the jQuery Validation dependency. The only way to override messages already defined by an addMethod is with:
```js
$.extend($.validator.messages, {
	key: "value"
}
```
That would have to be a language specific call (so needs a conditional) so I don't see how that is any easier or any less size for the implementers.

**Comment by LaurentGoderre** [comment] 2015-01-13 18:57
I am not talking about overriding but provinding new ones, if you use addMethod.

This is from the documentation:

```javascript
jQuery.validator.addMethod("math", function(value, element, params) { 
    return this.optional(element) || value == params[0] + params[1];
}, jQuery.validator.format("Please enter the correct value for {0} + {1}")); 
```

This is the desired way for i18n

```javascript
jQuery.validator.addMethod("math", function(value, element, params) { 
    return this.optional(element) || value == params[0] + params[1];
}, jQuery.validator.format(i18n("custom_error_message"))); 
```

There needs to be a way to add the `custom_error_message` to the WET i18n strings

**Comment by pjackson28** [comment] 2015-01-13 19:00
That's the thing, the existing error messages are not part of the WET i18n strings, they are loaded directly into jQuery Validation. So there would be no benefit in adding any custom ones to the WET i18n strings.

**Comment by pjackson28** [comment] 2015-01-13 19:04
Besides jQuery validation already has i18n support. If you leave the message string null, jQuery validation will do a lookup for the message with the "math" key. So if you need to specify a bunch of strings, then you do:
```js
$.extend($.validator.messages, {
    key1: "value1",
    key2: "value2",
    key3: "value3",
    key4: "value4",
    key5: "value5",
    key6: "value6",
    key7: "value7",
    key8: "value8"
};
```

There would be no benefit in putting it in the WET strings first.

**Comment by LaurentGoderre** [comment] 2015-01-13 19:40
But this snippet is not i18n.....What I am saying is when the default i18n are loaded it would be good to be able to specify another i18n file with custom strings that can be used for not only this plugin but other one as well

**Comment by pjackson28** [comment] 2015-01-13 20:02
How would they be used by another plugin? None of the other WET plugins have access to the jQuery Validation error messages as those strings are not added to the WET i18n object (they are directly added to the jQuery validation messages object).

**Comment by LaurentGoderre** [comment] 2015-01-13 20:10
It would be a nice to have to group all custom strings to a custom i18n file so that you can use to custom string not only with this plugin but with other one as well

**Comment by pjackson28** [comment] 2015-01-13 20:20
Should we be loading the custom form error messages in all cases or just on the pages where there is form validation? Error messages tend to be pretty big strings so can quickly increase page size if you have a good number of messages.

Also why would we need a loader for custom i18n strings? Wouldn't implementers just include their own i18n file at the end of the page just like they add any other custom JS? If they want to add it to the WET i18n object then they can just extend window.i18n.

**Comment by LaurentGoderre** [comment] 2015-01-13 20:25
We load all WET core strings all the time, it wouldn't be any different.

Extending the i18n probably would cause their string to get overwritten when the core i18n is loaded

**Comment by pjackson28** [comment] 2015-01-13 20:32
Why did we decide to load all the form error messages at all times? Is it to save an http request on a forms page?

As for extending, it wouldn't cause their string to get overwritten, particularly if they wait for the wb-ready (their extend would override core). They shouldn't be reusing keys anyway as unique keys would have no overwriting issues.

**Comment by LaurentGoderre** [comment] 2015-01-13 20:59
We don't load form error everywhere, but we do load all core strings everywhere

We could have used that approach for the core i18n strings as well but we chose to make it easier for implementers

**Comment by pjackson28** [comment] 2015-01-13 21:02
Actually we do load the form errors everywhere, they are appended to the i18n file for some reason.

**Comment by LaurentGoderre** [comment] 2015-01-13 21:45
Oh ok

**Comment by josephbr** [comment] 2015-01-14 15:42
One thing that confuses me about the jQuery validator. How do I explicitly assign it to the field I want validated? The example you provided is for comparing a field with "two parameters". What if you want to compare one field with another one?

**Comment by pjackson28** [comment] 2015-01-14 15:53
I'd assume you would add <code>data-rule-methodname="true"</code> to one of the fields and in the custom method do whatever steps you need to do for the check (so select the other field in the check and then compare there). You would likely be passing the id of the other field as a param to make it easy to do the check. You can see in additional-methods.js how new methods are created (there are param methods in there as well).

**Comment by LaurentGoderre** [comment] 2015-01-14 15:56
This seems overly complicated in jQuery validation, there should be an easy way to achieve this through the markup, I will look into it.

**Comment by pjackson28** [comment] 2015-01-14 16:04
There is the equalTo method in jQuery validation but it requires JS: http://jqueryvalidation.org/equalTo-method/ (still not that bad)

Here are some other approaches that involve JS (adding methods or rules):
* http://stackoverflow.com/questions/8507310/jquery-validate-rules-comparing-fields
* http://stackoverflow.com/questions/8090485/how-to-use-jquery-validator-to-compare-two-fields
* http://christoph-burmeister.eu/?p=2398

**Comment by LaurentGoderre** [comment] 2015-01-14 16:06
I haven't tested it but I think it's as simple as

```html
<input type="text" id="field1" name="field1" />
<input type="text" id="field2" name="field2" data-rule-equalTo="#field1" />
```

**Comment by josephbr** [comment] 2015-01-14 16:09
That worked perfectly; Thanks Laurent. The error string is already built in too: (i.e. "Please enter the same value again.").

**Comment by pjackson28** [comment] 2015-01-14 16:12
Too bad it is not well documented. Probably should be added to the working examples to show how it is done.

**Comment by josephbr** [comment] 2015-01-14 16:14
I agree as I had no idea this was even possible until Laurent suggested it. Glad I did not have to manually set up the validation rule with the "jQuery Validator Plugin" although it's still good to know that it is possible to do.

**Comment by LaurentGoderre** [comment] 2015-01-14 16:14
They are in the same boat as us...great product not so well documented ;). I found it by reviewing the code.

**Comment by pjackson28** [comment] 2015-01-14 16:16
@LaurentGoderre It was a good find. Could you please add it to the working examples?

**Comment by LaurentGoderre** [comment] 2015-01-14 16:16
When I come back tomorrow for sure. Maybe I should look at contributing to their documentation as well

**Comment by LaurentGoderre** [comment] 2015-01-15 21:31
I added this to the working examples

**Closed by LaurentGoderre** 2015-01-15 21:31 UTC
Labels: Plugin: Form Validation (jQuery Validation), Support Request
