### ISSUE TITLE
Tabbed Interface: Cannot enter in text into input field when form is inside a tab on Android devices.

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#7205] opened 2015-11-19 18:45 UTC
When you select a text input field, the keyboard to type in the text expands, then contracts again as soon as you try to type something in.

**Comment by muling** [comment] 2015-11-19 19:02
This was tested using Browserstack.

**Comment by andre-gh** [comment] 2015-11-19 19:07
Sounds like a focus issue, I will look into this before the next release.

**Comment by MaximMartel** [comment] 2015-11-19 20:08
i used BroweserStack, with a Samsung S5, and i do have that issue Muling. Working on a fix @andre-gh

**Comment by andre-gh** [comment] 2015-11-24 01:44
This is caused by equal heights, equal heights is no longer used on the mobile tabs view of the plugin (and was accidentally used and fixed in #7216) and thus was fixed.

**Closed by andre-gh** 2015-11-24 01:44 UTC
Labels: Plugin: Tabbed Interface/Carousel
