### ISSUE TITLE
Horizontal Definition Lists (Filter Tool)

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7846] opened 2017-01-19 12:40 UTC
So @eswright on #6998 mentioned how he prefers the search ability of a DataTable and like to see something like that for definition lists (`dl`) this is a possible approach.

Description:
This would be a filter for all definition lists (`dl`) on one page within a specified content area. You would add `dl-filter` class to the wrapper around the `dl` tags (for example a `div`, `section`, and etc).

Code:
```javascript
<script>
wb.doc.on( "wb-ready.wb", function() {
	var main,
	dlFilters,
	dlFilter,
	parentElement,
	div,
	label,
	input,
	i18n = wb.i18n;

	var dlFilterComponentCreater = function( element, index ) {

		dlFilter = element;
		parentElement = dlFilter.parentNode;
		div = document.createElement( "div" );
		label = document.createElement( "label" );
		input = document.createElement( "input" );

		if ( !dlFilter.getAttribute( "id" ) ) {
			dlFilter.setAttribute( "id", "wb-dlft-auto-" + index );
		}

		div.className = "dl-filter-component";
		label.innerHTML = i18n( "filter" ) + " ";
		input.setAttribute( "type", "search" );
		input.setAttribute( "id", "wb-dlft-auto-" + index );
		input.setAttribute( "aria-controls", dlFilter.id );

		input.addEventListener( "keyup", function() {
			var filter = this.value.toUpperCase(),
			dlFilter = element,
			dtList = dlFilter.getElementsByTagName( "dt" ),
			ddList = dlFilter.getElementsByTagName( "dd" );
			for (var i = 0; i < dtList.length; i++ ) {
				if ( ( dtList[i] && dtList[i].innerHTML.toUpperCase().indexOf(filter) > -1 ) || ( ddList[i] &&  ddList[i].innerHTML.toUpperCase().indexOf(filter) > -1 ) ) {
					dtList[i].style.display = "";
					dtList[i].nextElementSibling.style.display = "";
				} else {
					dtList[i].style.display = "none";
					dtList[i].nextElementSibling.style.display = "none";
				}
			}
		});

		label.appendChild( input );
		div.appendChild( label );
		parentElement.insertBefore( div, dlFilter );
	};

	dlFilters = document.getElementsByClassName( "dl-filter" );
	for (var i = 0; i < dlFilters.length; i++ ) {
		if ( !document.getElementById( "wb-dlft-auto-" + i ) ) {
			dlFilterComponentCreater( dlFilters[i], i );
		}
	};
});
</script>
```

Demo File View:
[DL_Filter_Demo_Single_Filter.pdf](https://github.com/wet-boew/wet-boew/files/717012/DL_Filter_Demo_Single_Filter.pdf)
[DL_Filter_Demo_Multiple_Filters.pdf](https://github.com/wet-boew/wet-boew/files/717003/DL_Filter_Demo_Multiple_Filters.pdf)

**This is not a completed solution (what I mean is do your own testing before using).**

**Comment by eswright** [comment] 2017-01-19 13:07
Thanks @kodecount  Functionally, the problem on a page like  http://www.nrcan.gc.ca/earth-sciences/geomatics/canadas-spatial-data-infrastructure/8904 is that ctrl-f 'find in page' only works when all the lists are open and not collapsed. (besides that less than 50% of users know about  ctrl-f)

**Comment by eswright** [comment] 2017-01-19 13:10
we need at solution that does not force glossaries to be one big long open list that is used with 'find in page'.  Every implementation is a long list that might meet someone's posting requirement, but it is nothing but frustrating.

**Comment by LaurentGoderre** [comment] 2017-01-19 13:12
I did create a new plugin for all-purpose filtering. It would allow you to define how the filter would search in the content and only show the content that match that filter.

**Comment by kodecount** [comment] 2017-01-19 15:29
Either way I've update the code example to allow for a single filter or multiple filters (**still just a prototype**), but their if anyone wants to use it.

**Comment by duboisp** [comment] 2017-01-19 16:20
For reference - The plugin that @LaurentGoderre are mentioning is the PR #7816 currently in work in progress status.

**Comment by duboisp** [comment] 2017-02-03 21:31
Found that this are a duplicate of #3079

**Closed** 2017-02-03 21:31 UTC
Labels: Close: Duplicate, Suggestion: Feature Request
