### ISSUE TITLE
Question: Indicating "no data" for empty cells in tables

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#7488] opened 2016-04-07 19:30 UTC
In the Canada.ca Style Guide, it says:

"Explain why a cell may have no value. For example:
-  “no data”
-  “0” (zero)
-  “n/a” (not applicable)"

In practice, writing "no data" in tables with a lot of missing data makes the table harder to read than if it was just empty. 

Often the hyphen is used to indicate the same thing, so I'm wondering if, like we do with footnotes using asterisk (*), can we provide sufficient hidden text to tell a screen reader the hyphen indicates no data?

Example:
`<td><span class="wb-inv">no data</span>-<td>`

Any suggestions @duboisp ?

**Comment by LaurentGoderre** [comment] 2016-04-08 12:13
That would read "no data dash" if you have verbose punctuation. I wonder if you could have a css class that would display the dash instead.;

```html
<td><span class="wb-inv tbl-no-data">no data</span><td>
```

```scss
.tbl-no-data {
    &:before {
        content: "-"
    }
}
```

**Comment by bsouster** [comment] 2016-04-08 12:20
Thanks Laurent.

If no one sees any accessibility issues with this, I can try to push this up to the Canada.ca Style Guide as an option.

**Comment by Bgolden67** [comment] 2016-04-08 12:27
Actually this issue is being discussed heavily by the AWG right now.. I raised similar questions and @SBleeks and Company are debating what the best approach is now in terms of accessibility.

Hopefully they can provide some guidance very soon.

**Comment by masterbee** [comment] 2016-04-17 22:08
@Bgolden67 - Please do let us know since I like the CSS idea from @LaurentGoderre but am curious to see if the "dash" is sufficient since I pretty sure screen readers do read the ```:before``` content property value (could have changed since it was a while ago when we tested content property and screen readers )

**Comment by Bgolden67** [comment] 2016-05-11 12:17
Just an Update to say, it's still being discussed by AWG

**Comment by DTardioli** [comment] 2016-06-21 17:53
I just added an issue related to the dash because it's in one of the github wet examples.
https://github.com/wet-boew/wet-boew/issues/7585 
http://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html (see page 4)

**Comment by shawnthompson** [comment] 2016-06-22 13:22
Maybe this should be changed in "Style Guide". Curious if @DK-TBS has any connections with the folks that write the Guide?

**Comment by DTardioli** [comment] 2016-06-22 13:47
@shawnthompson  Below is the email I sent to TBS (ws-nw@tbs-sct.gc.ca & wrpmo-bgprw@tbs-sct.gc.ca) June 21st. When I receive their reply I will post it.
*********
Hi,
The Canada.ca Style Guide (on page 30) shows that no data should be represented by either of the following:
•	“no data”
•	“0” (zero)
•	“n/a” (not applicable)"

In addition to the three examples in the Guide, we would like to use a dash (coded as ndash/regular dash with a proper header/id association).

Will the style guide be updated in the future to include an example of a dash for cells that have no value? If not, can we use the dash to show empty values?

**Comment by DK-TBS** [comment] 2016-06-22 15:28
@shawnthompson – I do!  Denise Eisner is responsible for the Style Guide, and she sits just around the corner from my desk.  I spoke with her about it, and our only concern is around the fact that the dashes would be read out by screen readers in each cell.  “N-dash” being spoken out loud would make tables even more difficult for screen reader users than they already are, so we’d only want to update the Style Guide to allow dashes or hyphens if screen readers don’t see them.  The solution that @LaurentGoderre put forward sounds like it would work well, we’d be totally comfortable with something like that.

Shawn, if you guys can get this working in GCweb and in AEM, let us know and at that point Denise will be happy to update the Style Guide accordingly.  Until then we’ll have to leave it as it is…

**Comment by DTardioli** [comment] 2016-06-22 15:58
The easiest approach would be to simply add a dash as an option and without the extra overhead of styling and formatting through css. N/A and no data are not scan-friendly when looking at data and numbers and some tables come to us with the dash instead of 0 (zero).

**Comment by shawnthompson** [comment] 2016-06-22 19:53
I'm curious to see where the AWG discussion leads. I've always wondered what the accessibility community thought about tables. Any news on the discussion @Bgolden67?

**Comment by Bgolden67** [comment] 2016-06-23 11:50
I've heard nothing new yet maybe @SBleeks or @mysticjeff  could provide some information?

**Comment by SBleeks** [comment] 2016-06-23 20:12
The AWG discussed the use of blank cells within online data tables.  We understand that in some cases, such as accounting tables, blank cells are necessary in that they have specific meaning and provide specific context.  We advise against the use of the dash “-“ to indicate a “blank cell”.  CRA currently uses the dash “-“ for blank cells in some of their tables.  Our CRA contact is away until the first week of July at which time we will request a rationale on the use of the dash “_”.

**Comment by DK-TBS** [comment] 2016-06-24 14:37
Curious:  can someone fill me in on what exactly the problem is with empty TD elements?  I've been able to find some information about the problems that screen readers can have with empty TH elements, but nothing concrete about plain old table cells.  

I haven't spent all that much time searching, but almost all the info I've come across is either outdated or totally vague.  Lots of people out there saying that empty table cells "can cause accessibility problems", but not much in the way of an actual explanation.  Anyone here have experience with this, or solid examples of what the problems are?

**Comment by CoolColin** [comment] 2016-07-06 19:21
Hey everyone, on behalf of AWG, along with @SBleeks I'd like to note that we are in final stages of drafting a formal response that we hope to present in the next 2 weeks. @bsouster could you kindly provide me with the link to that page you mentioned in your original post? I know I've seen it before but after many hours of researching multiple sources and pages I have been unable to find that exact mention. Thanks everyone!

**Comment by DK-TBS** [comment] 2016-07-07 13:59
Thanks for the update @CoolColin - we'll hold off on updating the Canada.ca style guide until we hear back from you on this.  Will you drop us a note on this thread when the response is ready?

**Comment by bsouster** [comment] 2016-07-11 15:01
@CoolColin I can't find the exact page but here's one similar
http://www.cic.gc.ca/english/resources/evaluation/cec/2016/effectiveness.asp#t4-1

**Comment by CoolColin** [comment] 2016-07-11 18:57
My problem is that the original reference from the writing/style guide seems to be “gone” …

**Comment by DTardioli** [comment] 2016-07-11 19:11
@CoolColin @DK-TBS I believe the original reference in the style guide is on page 30
http://www.gcpedia.gc.ca/gcwiki/images/b/b5/Canada-ca_Content_Style_Guide_v2-0_GCPedia_EN.pdf 

... from page 30
When formatting your table, include words that:   < CURRENT
When formatting your table:  < REVISION SUGGESTION

explain why a cell may have no value.
For example:
- “no data”
- “0” (zero)
- “n/a”(not applicable)
- “-” (n-dash) << NEW TEXT ADDITION

**Comment by DK-TBS** [comment] 2016-07-26 15:25
@CoolColin and @SBleeks - Has the AWG come to a decision about this?  We’ve gotten some urgent requests from the editorial group here, and we’d like to let them know what’s going on as soon as possible.  Any chance you can get back to us today?  It doesn’t have to be the complete formal response, just a quick summary of the blank-cells approach would be great.  Let me know...

Big thanks.
Dave

**Comment by gdanova** [comment] 2016-08-03 17:47
As Dave mentioned, what is the problem with empty TD cells? They pose neither a usability nor accessibility problem, and are sometimes needed and other times desired, especially to reduce visual noise. All the options in the guide are, in my view, redundant. _What better way to describe nothing than to write nothing._

**Comment by DTardioli** [comment] 2016-08-03 18:27
More…

Domenic

**Comment by CoolColin** [comment] 2016-08-09 16:51
Hey everyone. Appreciate the patience. With summer vacations and an AWG meeting only once a month @SBleeks and myself are finalizing this over the next 24 hrs and should have an official response/direction to share by Thursday. Appreciate all the feedback!

**Comment by DTardioli** [comment] 2016-08-09 17:10
@CoolColin @SBleeks thanks for the follow-up...let me know if you would like any input or feedback

**Comment by CoolColin** [comment] 2016-08-10 15:22
Good day all. On behalf of the AWG here is our official response in regards to the empty data cells in tables:

The Access Working Group (AWG) has been discussing the topic of blank cells in tables. To this end, we have also performed testing with a wide range of adaptive technologies and received great feedback from individuals in the community.

With that said the AWG is recommending leaving the blank cells empty when appropriate, as the majority of all adaptive technologies notify the user that it is indeed a blank cell. This should pose minimal to no issue to the user provided the table is properly coded, by the use of header/ID associations. It also minimizes visual noise unnecessary to comprehend the content as experienced by some users with the use of dashes instead of blank cells. 

If for example, data cells have been left blank for a specifically noted reason, this could be represented by a table legend, or within the table summary,  notifying the user the exact reason the cell has been left blank. Otherwise the assumption, generally speaking, is that the adaptive technology notifies the user the cell is blank, therefore symbolizing that no data is present for that particular data point. The WET4 Writing Guide states, “Like text, tables should be clear and concise, with as few data elements as possible in each cell…” (http://wet-boew.github.io/wet-boew-styleguide/v4/writing/principals-en.html#tables) 

The use of a dash has been adopted by some to represent blank cells. However if we refer to the WET4 Writing Guide it states the exact purpose and proper use of dashes (em-dash, hyphen and en-dash). They are reserved for text components of your content. See “Dashes and Hyphens” in the style guide: http://wet-boew.github.io/wet-boew-styleguide/v4/writing/formatting-en.html#dash 

Additionally, dashes and blank cells have specific and intended meaning for certain types of tables such as accounting tables. Changing the blank cell in this case would affect the meaning of the accounting table. 

We believe the use of blank cells is the best solution for representing cells with no data. We recognize that in some cases blank cells are necessary when creating complex tables with multiple data clusters for example. Blank cells however, should not be used for the purpose of table layout.

We welcome any further feedback on this topic.

**Comment by hsrudnicki** [comment] 2016-09-06 19:18
Can be this issue closed as resolved, based on the above, including "&nbsp;", as well the css way: empty-cells, or using of conventional notations in statistics, or if otherwise?  Please update the status of this again, thank you

**Comment by CoolColin** [comment] 2016-09-06 19:40
@hsrudnicki The AWG has provided what I feel is a formal air tight response to this. No special CSS should be added or included. No hyphens should be used unless explicitly stated why. @bsouster opened this ticket perhaps he wishes to comment further or close it as resolved?

**Comment by shawnthompson** [comment] 2016-09-06 20:37
@AmelieSirois curious on your opinion? and welcome to WET on Github!

**Comment by hsrudnicki** [comment] 2016-09-09 19:49
The duplicate issue 7585 has been closed, but this remains still an issue waiting for your opinions, as well thoughts to resolve this.

**Comment by AmelieSirois** [comment] 2016-09-13 15:45
@shawnthompson thanks for the invitation to comment and sorry for the delay! I'm definitely very interested in chatting with the Access Working Group (shout out to @CoolColin ) about their work on all fronts. 

So far, from a content design perspective, our reading on the topic brought to light the fact that blank cells in tables can be ambiguous. We don't want the user to misinterpret the information. A blank cell can lead to more questions: Is this empty by mistake? Is the value zero? Is it because values don't apply in this case? etc. So thinking about users and how should make sure they don't get stuck with such questions as they're trying to consume web content, my understanding is that it's best to avoid blank cells as much as possible or at the very least, to explain why they have no value in a very structured and obvious way. We shouldn't leave room for interpretation. 

I tend to agree with @CoolColin and the Access Working Group. I don't think the Canada.ca Content Style Guide contradicts their findings but it may be fitting to add precision. I'd love to engage in thorough conversations about how best to consolidate optimal readability, complete user experience, praise-worthy content design and near flawless accessibility. And that's what I want for Christmas :)

**Comment by gdanova** [comment] 2016-09-13 17:37
It seems to me that if you’re stating that:

> Blank cells can lead to more questions: Is this empty by mistake? Is the value zero? Is it because values don't apply in this case? etc.

and

> Best to avoid blank cells as much as possible or at the very least, to explain why they have no value in a very structured and obvious way. We shouldn't leave room for interpretation.

...then you **do not** actually agree with @CoolColin and the Access Working Group, who have stated:

>If the cell is blank because there is no data point/value for that cell then leave it blank. No explanation required for anything. No extra text required.

My opinion also takes the perspective of the user/reader. Placing something in a cell where nothing belongs in it leads to more confusion and visual noise. There should be no misinterpreting blank cells by the user. Cells are not left empty my mistake. It simply means “nothing”. Writing anything in its place is what can lead to misinterpretation and further user questions. It reminds me of documents with pages containing “this page intentionally left blank”. We wouldn’t want to write “this cell intentionally left blank” in hundreds of data cells would we?

**Comment by AmelieSirois** [comment] 2016-09-13 20:48
@gdanova I agree with: 

> If for example, data cells have been left blank for a specifically noted reason, this could be represented by a table legend, or within the table summary, notifying the user the exact reason the cell has been left blank. 

I also agree that dashes (em-dash, hyphen and en-dash) are reserved for text components of content.

Using complex tables is fitting **only** if **absolutely** necessary. If they can be avoided, I avoid them at all cost (for various reasons, e.g.: tough to view on mobile).

I believe that readability, UX, accessibility, content design, IA, etc. sometimes are considered in silos, whereas I strongly believe any content should be analyzed with all of it in mind. 

Would love to connect with the Access Working Group to chat about their findings.

**Comment by mysticjeff** [comment] 2016-09-13 20:53
Also, Adaptive technology like a screen reader already says "blank" when it hits a blank cell.  

-----Original Message-----

**Comment by mysticjeff** [comment] 2016-09-13 21:11
We also don't want to "over accessify" things.  Additional code or verbiage when not needed can be counter productive.  

I suggest we follow the Accessibility Working Group (AWG)'s recommendations
recommendations


-----Original Message-----

**Comment by duboisp** [comment] 2016-09-14 04:57
@AmelieSirois I see your point that may be in some circumstance blank cells in tables could be potentially ambiguous to the user. Especially depending how styling is used for data tables.

@AmelieSirois Did you have use cases or a list of data table type (like financial table) that would benefit of not leaving blank cells empty and be replaced by a dash, "N/A", 0 or something else?

In my opinion, sometime using complex tables could be the best solution for an optimal user experience (UX). It is with that in mind I documented the [table usability concept](https://github.com/duboisp/Table-Usability-Concept), developed [12 techniques for coding complex table](http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/index-en.html), and created the [WET table validator](http://wet-boew.github.io/v4.0-ci/demos/tablevalidator/tablevalidator-en.html).

:smiley:

**Closed** 2016-09-14 14:29 UTC

**Comment by CoolColin** [comment] 2016-09-14 16:04
I'm surprised this was just closed based on the amount of discussions still taking place...

**Comment by SBleeks** [comment] 2016-09-14 16:09
Yeah… People love to close tickets.
I think we made our case…



Stacy Bleeks

Web Accessibility Expert - Centre of Expertise on Accessibility | Communications and Dissemination Branch
Statistics Canada | Government of Canada
Stacy.Bleeks@canada.ca<mailto:Stacy.Bleeks@canada.ca> / Tel: 613-951-6137

Expert en accessibilité  - Centre d'expertise en accessibilité | Direction des communications et de la diffusion
Statistique Canada | Gouvernement du Canada
Stacy.Bleeks@canada.ca<mailto:Stacy.Bleeks@canada.ca> / Tél : 613-951-6137

**Comment by DTardioli** [comment] 2016-09-14 16:21
It's still not clear whether the table cell can be left blank or can include a dash (em or en?)  - if either of those options were top be adopted, it would require a change to the Canada.ca content style guide rule for using tables to organize data: http://www.tbs-sct.gc.ca/hgw-cgf/oversight-surveillance/communications/csc-grc-eng.asp#wp5-3

**Comment by bsouster** [comment] 2016-09-14 17:39
@CoolColin as you stated earlier, AWG sufficiently answered the question within the scope of what was asked. The discussion has since turned into Canada.ca-specific preferences

**Comment by shawnthompson** [comment] 2016-09-14 20:48
Should we move this discussion to a [GCWeb issue](https://github.com/wet-boew/GCWeb/issues/new)?
