### ISSUE TITLE
Multimedia video player bugs

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#7096] opened 2015-09-14 14:31 UTC
1. The first example video in the working examples has a load icon infinitely spinning in front of the video while it's playing. It continues long after the video is paused. On my own server, the play icon never leaves the screen. (Firefox, IE9)

2. The second example video in the working examples never loads, load icon is spinning forever. (Chrome)

![infiniteloop](https://cloud.githubusercontent.com/assets/1944744/9851582/678de77e-5ac7-11e5-9f71-de5a9dea3f78.jpg)

**Comment by ehcee** [comment] 2015-09-14 18:39
I've experienced the same problem on canada.ca/health in our dev environment with the 4.0.17 version of the canada.ca templates. It just keep the play button overlayed over the video while it's playing in the background. We are on version 4.0.14 in production and they working without this issue. The video bug has been going on for a few versions of the templates since 4.0.14 with either the spinning refresh icon or play icon overlaying over the video while it's playing. This also seems to happen regardless of what browser i am using.

![video_gallery_-_2015-09-14_14 34 44](https://cloud.githubusercontent.com/assets/5295103/9858307/faba8824-5aed-11e5-9982-dcf457b69127.png)

**Comment by LaurentGoderre** [comment] 2015-09-15 13:18
The play button overlay is a duplicate of #6956 and have been fixed by #7044 and will be included in v4.0.18

**Closed** 2015-09-17 12:24 UTC
