### ISSUE TITLE
Toggle: issue with toggle all detail elements (expand/collapse)

### ISSUE THREAD

**Issue by tyhsimms** [wet-boew/wet-boew#8647] opened 2019-05-10 17:30 UTC
I encounter an issue when using a toggle button to expand/collapse all detail elements. If every detail element is opened/closed manually before using the toggle button, clicking the toggle button does nothing on the first click (not the case if only some were open/closed manually). Clicking the button a 2nd time will then trigger the toggle. The issue can be reproduced with the working example.

https://wet-boew.github.io/v4.0-ci/demos/toggle/toggle-en.html#details

To reproduce, manually open the 3 detail elements (Example 1, Example 2, Example 3) and then click the toggle button to close them. First click is fruitless, second click is successful.

**Comment by juleskuehn** [comment] 2019-05-13 15:31
I'll see if I can fix this now. Thanks!

**Comment by juleskuehn** [comment] 2019-05-13 16:31
The issue you noted should be fixed, however, it reveals another problem:
The expected behaviour for a toggle on multiple elements, when some are expanded and some are collapsed, is not defined.

I suggest we define it as follows:
1. Toggle will expand all items if *any* are collapsed.
2. Toggle will collapse all items if and only if *all* are open.

Does this sound like a reasonable approach?t

**Comment by duboisp** [comment] 2019-05-13 21:23
@juleskuehn 

I am not sure. It could be more confusing to users.

What about :

1. Toggle will expand all items if and only if all are collapsed
2. Toggle will collapse all items if and only if all are expanded
3. Otherwise Toggle will follow is normal toggling cycle.

**Comment by juleskuehn** [comment] 2019-05-14 13:12
My preference was that the "state" of the toggle would be entirely determined by the state of the elements it is toggling. However, I see your point and I think it works just as well for the most common scenario:
- User expands one item, then realizes there are many and decides to "Toggle expand all". The normal toggling cycle will provide the desired behaviour.

I have no strong feelings about it really... I will wait for others to weigh in.

**Comment by juleskuehn** [comment] 2019-05-14 14:40
Just to clarify @duboisp 
On second thought, I disagree with your proposal.
- If the group toggle only expands all items when all are collapsed, that would not work for the common scenario I describe above.
"Normal toggling cycle" would then have to mean "collapse all expanded items and expand all closed items". I can't think of any case where a user would want this.
So the group toggle should, in my opinion, either expand all or collapse all.

**Comment by Pacoup** [comment] 2019-05-14 15:29
The problem is the Toggle button itself.

Logically, the Toggle button could mean **Toggle the state of all items On or Off** (basically presses the On and Off button for you), but the problem here is determining what state (On or Off) the group of items is in if some are expanded and some are collapsed. Is it On when a majority of items are expanded? Is it On when a minority of items are expanded? What happens if an equal number of items are expanded and collapsed? This is undecidable behaviour.

Otherwise, you could implement the Toggle to actually toggle the state of every item independently, but that's hardly of any use, as @juleskuehn mentions.

Instead, if you get rid of Toggle entirely (maybe change it to a label for the On / Off buttons), then there are only two possible behaviours: On for everything, Off for everything, and they remain unambiguous regardless of the state the items are in.

Maybe change the button labels as well:
```
 ---------------------------
| Expand all | Collapse all |
 ---------------------------
```

---

> Toggle will expand all items if any are collapsed.
Toggle will collapse all items if and only if all are open.

> Toggle will expand all items if and only if all are collapsed
Toggle will collapse all items if and only if all are expanded

With these, you could literally end up in a state where the Toggle button does nothing at all, with no explanation. It'll just look broken.

**Comment by juleskuehn** [comment] 2019-05-14 16:04
@Pacoup I agree with the idea of removing "Toggle all". What does it add besides confusion?

However, my suggestion

>     Toggle will expand all items if any are collapsed.
>     Toggle will collapse all items if and only if all are open.

will always do something - typically it will expand all items, which is the most desirable function

**Comment by Pacoup** [comment] 2019-05-14 19:39
@juleskuehn 

> Toggle will collapse all items if and only if all are open.

e.g. I open 2 out of 3 items manually. Toggle button now does nothing.

**Comment by juleskuehn** [comment] 2019-05-14 20:06
"Toggle will expand all items if any are collapsed.": It will expand the third item.

**Comment by Pacoup** [comment] 2019-05-14 21:02
Oooooh, right. 🤔 I actually like this solution.

**Closed** 2019-05-30 14:21 UTC
Labels: Feature: Toggle, Query: Feature Request
