### ISSUE TITLE
Tabbed Interface - Carousel: show-thumbs

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6552] opened 2015-02-20 18:49 UTC
When you put in a grid of col-md-8 or smaller, the thumbnails float up into the figcation.

![capture](https://cloud.githubusercontent.com/assets/2575266/6307006/3fb13ea8-b906-11e4-80de-8b75585932f9.JPG)

This happened when we put the show-thumbs class on the carousel on the [Theme landing page](http://servicecanada.github.io/GCWeb/theme-en.html) on Canada.ca. (Add the class to the carousel using Firebug). Same thing happens when you add a col-md-7 on the [WET carousel demo page](http://wet-boew.github.io/v4.0-ci/unmin/demos/tabs/tabs-carousel-en.html)

![capture2](https://cloud.githubusercontent.com/assets/2575266/6307092/2cb63ba4-b907-11e4-993c-b5c27a8c6d37.JPG)

**Comment by LaurentGoderre** [comment] 2015-02-20 19:07
Duplicate of #6548. There seems to be a lot of issues with that carousel style....

**Closed** 2015-02-20 19:08 UTC
