### ISSUE TITLE
Geomap: Static maps not working in Android

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#4815] opened 2014-03-12 17:06 UTC
Static map doesn't show up

**Comment by LaurentGoderre** [comment] 2015-01-20 02:55
From test on browser stack, the problem occurs on most Samsung products except the Tab4, it also seems to affect the older Amazon ones but not the newer one (Kindle Fire HDX 7).

**Comment by LaurentGoderre** [comment] 2015-01-20 21:49
@jvanulde how does the static map work?

**Comment by jvanulde** [comment] 2015-01-21 15:16
@LaurentGoderre setting the static class simple disables all of the map controls. I can't think of a reason why this would cause issues. Is there some way I can test locally?

**Comment by LaurentGoderre** [comment] 2015-01-21 15:45
I haven't found a way to reproduce outside of Android

**Comment by hsrudnicki** [comment] 2015-06-08 20:23
Can be this issue closed ?

**Comment by LaurentGoderre** [comment] 2015-06-09 12:18
No, it's still an issue

**Comment by jvanulde** [comment] 2015-06-09 12:58
I can't reproduce in emulation on Chrome or on my Samsung Galaxy Tab4.

**Comment by LaurentGoderre** [comment] 2015-06-09 15:45
Yeah not through emulation but I was able to reproduce with a native device

**Comment by jvanulde** [comment] 2015-06-09 15:52
What happens exactly? No image at all?

**Comment by LaurentGoderre** [comment] 2015-06-09 18:48
Yeah

**Comment by jvanulde** [comment] 2015-06-09 19:26
Again, we just disable the controls so I can't imagine how that would affect the map. Is there a way for me to test without a physical device?

**Comment by LaurentGoderre** [comment] 2015-06-09 19:59
It seem to only be occurring on physical devices

**Comment by jvanulde** [comment] 2015-06-16 13:14
Can you recheck on PR #6862 please.

**Comment by pjackson28** [comment] 2015-06-17 14:28
Closing since PR #6862 was merged in.

**Closed by pjackson28** 2015-06-17 14:28 UTC
Labels: Browser: Chrome, Plugin: Geomap
