### ISSUE TITLE
Collapsible alerts: icon disappears when collapsed

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#7943] opened 2017-03-13 15:49 UTC
Why does the icon go away when the menu is collapsed?  Was that intentional?  This is with the latest version of WET 4.0.23.

**Comment by kodecount** [comment] 2017-03-13 15:52
What browser? If it is Firefox their is a bug in their a few of their version.

Also latest version is WET 4.0.24.

**Comment by kodecount** [comment] 2017-03-13 15:54
It still occurs in the latest version. I can remember if their able to fix this.

**Comment by kodecount** [comment] 2017-03-13 15:55
Duplicate of https://github.com/wet-boew/wet-boew/issues/7778

**Comment by muling** [comment] 2017-03-13 16:04
Yes I am using Firefox.

**Comment by kodecount** [comment] 2017-03-13 16:05
You'll have to wait till Firefox fixes the bug.

**Closed** 2017-03-14 14:49 UTC
Labels: Close: Duplicate, Plugin: Collapsible alerts
