### ISSUE TITLE
Unable to download Wetboew Canada.ca

### ISSUE THREAD

**Issue by BelangerMaxime** [wet-boew/wet-boew#8564] opened 2019-02-11 17:51 UTC
Hi,

I'm unable to download the latest version : 
https://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html

![image](https://user-images.githubusercontent.com/25433718/52582669-bc421780-2dfb-11e9-8826-974c9f5ee279.png)

Error 404 - NOT FOUND

**Comment by RobJohnston** [comment] 2019-02-11 18:10
Duplicate of https://github.com/wet-boew/wet-boew/issues/8562, I believe.

**Comment by duboisp** [comment] 2019-02-11 20:09
The version 5.0.0 of Canada.ca theme (GCWeb) are now published and available for download.

* [Release notes](https://wet-boew.github.io/themes-dist/GCWeb/gcweb-theme/release/v5.0-en.html)
* [Production files](https://github.com/wet-boew/GCWeb/releases/download/v5.0.0/themes-dist-5.0.0-gcweb.zip)

The link in the wet-boew download page are now working.

**Closed by duboisp** 2019-02-11 20:09 UTC
Labels: Meta, Query: Question
