### ISSUE TITLE
Share Widget-Android 4.2.2-Samsung Galaxy S4 mini

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5235] opened 2014-04-15 18:39 UTC
Email button is 1st on the list of social media sites in the widget.  @pjackson28 maybe it's my phone being funky

![screenshot_2014-04-15-14-32-24](https://cloud.githubusercontent.com/assets/5949078/2711358/fb0c205c-c4cc-11e3-8c9c-bf32bb532280.png)

**Comment by hsrudnicki** [comment] 2015-06-09 15:53
Can be this issue closed?

**Comment by pjackson28** [comment] 2015-06-09 19:38
We'll have to close it as can't reproduce as we have been unable to replicate this anywhere.

**Closed by pjackson28** 2015-06-09 19:38 UTC
Labels: Browser: Android, Close: can't repo, Plugin: Share widget

**Comment by pjackson28** [comment] 2015-06-09 20:00
I just checked and the default browser for the Samsung S4 Mini is out of the support window. It ran Android 4.2.2 (API level 17) which ran WebKit 534.30. The WebKit version has been at least 537.36 since Android 4.4 and Android 5.1 (API level 22) is now available. So yet another reason that the issue should be closed.
