### ISSUE TITLE
Print on does not expand the toggle text for printing

### ISSUE THREAD

**Issue by Sburbidge** [wet-boew/wet-boew#7681] opened 2016-10-03 12:27 UTC
I have created two pages using the toggle.
In the first instance, the print on works perfectly. It expands the entire text for users to print.
http://www.mpcc-cppm.gc.ca/01/400/400-eng.aspx

In this second instance, it doesn't (Timeline section). I'm not sure why it is not working.
http://www.mpcc-cppm.gc.ca/03/305/index-eng.aspx

**Comment by cybersubtype** [comment] 2016-10-03 12:34
The first link isn't working on Chrome (Version 53.0.2785.116 m (64-bit)). It expands them but I only get 1 page. I have to cancel and click print again for it too work. Just in case you're interest in knowing.

**Comment by cybersubtype** [comment] 2016-10-03 12:41
As for the second link I think the issue is ` "parent": "#details-elements"` I don't see any element with that id.

**Comment by Sburbidge** [comment] 2016-10-03 13:53
http://www.mpcc-cppm.gc.ca/03/305/index-eng.aspx
For this link I believe I have found the problem. Whether the text is expanded or not on the screen, by adding the class wb-toggle to the summary, it expands toggle text by default when user want to print the page. You can see it in the print preview. However, it came at the expense of expanding the text by clicking only on the arrow rather than the arrow and/or the text, as in this link (http://www.mpcc-cppm.gc.ca/01/400/400-eng.aspx). 
How can I get to expand the text by clicking anywhere on the line, ( Timeline = arrow and/or text) as well as having the default option of the text being expanded for printing?

**Comment by Sburbidge** [comment] 2016-10-03 13:54
Sorry I mistakenly closed this issue.

**Comment by cybersubtype** [comment] 2016-10-03 14:15
It working on Chrome (Version 53.0.2785.116 m (64-bit)), Firefox v49, and IE11? What version you having a issue with?

**Comment by Sburbidge** [comment] 2016-10-03 17:41
FYI,
Chrome 53.0, works perfectly, toggle works on arrow, text & white space
Internet Explorer v11.0, toggle works on arrow only
Firefox v49.0, the arrow does not appear but works on text & white space

**Comment by cybersubtype** [comment] 2016-10-03 17:44
Did you try cleaning up the code?

**Comment by Sburbidge** [comment] 2016-10-03 18:29
If you mean, validate the page, yes I did and it comes out clean other than the warming about the detail element not being supported in all browsers...

**Comment by cybersubtype** [comment] 2016-10-03 18:30
@Sburbidge Sorry I'm using a latest version and this seems to be fixed in that version. It seems to be a issue limited to your version of WET (v4.0.6).

**Comment by Sburbidge** [comment] 2016-10-03 18:33
That's good news. How would I go about upgrading my WET version to the latest?

**Comment by cybersubtype** [comment] 2016-10-03 18:34
You have to replace the css and js file. They can be downloaded here: http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html

**Comment by Sburbidge** [comment] 2016-10-03 18:42
source code  or production files?

**Comment by cybersubtype** [comment] 2016-10-03 18:44
Depends on your departments policies/server environment. My assumption is your looking for already generated css and js file? If so production files.

**Comment by Sburbidge** [comment] 2016-10-03 18:50
This is beyond my knowledge and I don't want to mess up anything so I'll leave things as they are. Thanks for your help.

**Comment by cybersubtype** [comment] 2016-10-03 18:51
Sometimes thing are better the way they are until everyone at your department ready to update.

**Comment by Sburbidge** [comment] 2016-10-03 18:57
Agreed.

**Closed** 2016-10-03 18:57 UTC

**Comment by Sburbidge** [comment] 2016-10-05 13:34
Thanks. I actually have updated the CSS files from V22 and it works fine in two out of the 3 browsers. In Firefox, I still don’t see the arrow, but the mouse over works indicating that there is a clickable link there. So I’m good with it.

Thank you very much for all your help.

**Comment by cybersubtype** [comment] 2016-10-05 14:47
Someone is currently working on fixing it be a while till it probably pushed out. Check it out here: https://github.com/wet-boew/wet-boew/pull/7685.

**Comment by Sburbidge** [comment] 2016-10-05 20:44
Thanks. Otherwise, it seems to work in all three browsers. Again thank you for your help.

Have a nice evening.
