### ISSUE TITLE
Form Validation-Digits only

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5423] opened 2014-05-13 14:18 UTC
http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html (under "Other Examples")
It says it can only take 0-9, but it has no error message when I type anything that doesn't fit that criteria.  This goes for all browsers I have at my disposal

**Comment by LaurentGoderre** [comment] 2015-06-09 17:45
duplicate of #4941

**Closed by LaurentGoderre** 2015-06-09 17:45 UTC
Labels: External: Dependency Upstream, Plugin: Form Validation (jQuery Validation)
