### ISSUE TITLE
"Basic HTML version" being picked up by search engines

### ISSUE THREAD

**Issue by bsouster** [wet-boew/wet-boew#7468] opened 2016-03-22 15:49 UTC
Recently we noticed Google indexed our Welcome Refugees section with this URL:
http://www.cic.gc.ca/english/refugees/welcome/index.asp?wbdisable=true (plugins auto-disabled)

Google is a huge source of traffic and this page had a lot of significance through Dec to Jan, so this probably disrupted the experience for a lot of users.

Is there a way to keep search engines from crawling the basic HTML version?

**Comment by RobJohnston** [comment] 2016-03-22 15:54
Hi @bsouster , I think that they're talking about this over at https://github.com/wet-boew/wet-boew/issues/7457.

**Comment by LaurentGoderre** [comment] 2016-03-22 16:11
duplicate of #7457

**Closed by LaurentGoderre** 2016-03-22 16:11 UTC
Labels: Close: Duplicate
