### ISSUE TITLE
WET 4.0.24 (Future milestones)

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7905] opened 2017-02-21 14:12 UTC
Is WET gonna make it for tomorrow [future milestone](http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html)?

Their is a lot of outstanding pull request that should be fixed up and submitted for this milestone.

**Comment by LaurentGoderre** [comment] 2017-02-21 15:04
We merged what will make it for the next released. The only potential exception being #7899

**Comment by duboisp** [comment] 2017-02-21 15:13
I am still looking to have the following PR #7883 #7882 #7875 #7790 merged for WET 4.0.24 release

**Comment by duboisp** [comment] 2017-02-21 15:15
And I fixed the merge conflict in #7803, so it should be ready for this release also.

**Comment by LaurentGoderre** [comment] 2017-02-21 15:31
@duboisp you don't want to do the WET extension?

**Comment by LaurentGoderre** [comment] 2017-02-21 15:31
I also don't remember what we decided for #7803

**Comment by LaurentGoderre** [comment] 2017-02-21 15:34
Looking at #7803, I'm pretty sure it would break all lightbox so a pretty risky PR to merge the day before release.

**Comment by kodecount** [comment] 2017-02-21 15:35
https://github.com/wet-boew/wet-boew/pull/7885 (needs french translation)

https://github.com/wet-boew/wet-boew/pull/7759 (looks ready

https://github.com/wet-boew/wet-boew/pull/7742 (looks ready)

**Comment by kodecount** [comment] 2017-02-21 15:38
Also I don't think the plugins (document/script) update and the new facebook plugin be ready for this milestone (https://github.com/wet-boew/wet-boew/pull/7010) ?

**Comment by duboisp** [comment] 2017-02-21 15:38
Prior to create "WET extension" I need an **official** confirmation from the Principal Publisher saying it will support "WET extension" in AEM. The only official confirmation I have is the WET 4 is supported, not any extension of WET. Also I have confirmation that we wont be allowed to do insert any kind of custom javascript.

**Comment by kodecount** [comment] 2017-02-21 15:41
_"insert any kind of custom javascript"_ Isn't WET full of custom JavaScript? Their is a lot of libraries, but also a lot that lack accessibility or do not work in combination with some of the current plugins.

**Comment by duboisp** [comment] 2017-02-21 15:47
For #7803 we discussed to only fix the merge conflict, so that is what I did. 
But, as you did, I will continue that discussion in the PR.

**Comment by LaurentGoderre** [comment] 2017-02-21 15:49
@kodecount that's not what custom javascript meeans.....custom javascript means code that is on individual pages. AT least with code that is in WET there are steps to ensure the code quality such as unit test, coding standards, minification, etc.

**Comment by kodecount** [comment] 2017-02-21 15:53
Okay. Thanks. Misunderstood.

**Comment by EricDunsworth** [comment] 2017-02-21 15:58
Btw if #7759 gets merged in time for 4.0.24, I'd recommend also merging in #7815 (latter partially depends on the former's fixes being present).

**Comment by LaurentGoderre** [comment] 2017-02-21 16:18
The more stuff we merge in last minute like this, the more likely we will end up with a broken release for the next 3 months

**Comment by duboisp** [comment] 2017-02-21 16:33
@LaurentGoderre I agree, but PR's that may need to have an open discussion only get reviewed/discussed one or two week before the official release. That even if they were submitted longtime ago. For example the [Field flow plugin PR](https://github.com/wet-boew/wet-boew/pull/7790) was firstly submitted on Nov 30 2016 and you did the first review two week ago. (btw thanks for reviewing it)

**Comment by Beastmais27** [comment] 2017-02-21 18:17
Hello,

Just wanted to know if #7859 will be apart of  4.0.24?

**Comment by kodecount** [comment] 2017-02-21 18:22
It should be since it merged.

**Comment by Beastmais27** [comment] 2017-02-21 18:27
Perfect!

Thanks for the answer @kodecount.

**Comment by lucas-hay** [comment] 2017-02-21 19:17
@Beastmais27 Yes #7859 will be in the 4.0.24 release.

**Comment by lucas-hay** [comment] 2017-02-21 19:18
@EricDunsworth let's wait on #7759 and #7815 for the next release.

**Comment by lucas-hay** [comment] 2017-02-21 19:21
@duboisp 

> @LaurentGoderre I agree, but PR's that may need to have an open discussion only get reviewed/discussed one or two week before the official release. That even if they were submitted longtime ago. For example the Field flow plugin PR was firstly submitted on Nov 30 2016 and you did the first review two week ago. (btw thanks for reviewing it)

As discussed on our phone call last week, I am hoping to get things on track for the next release and this will be a thing of the past. We have a lot of cleanup to do and some processes to improve, which should all fall into place over time.

**Comment by duboisp** [comment] 2017-03-08 20:52
@lucas-hay have you any news about the "WET extension"? 

If the issue is the size on the core, can I propose a solution that would be similar of geomap plugin? Where the javascript code is in a separate file in the "src/plugins/deps" folder.

**Comment by lucas-hay** [comment] 2017-03-09 13:16
@duboisp Watch for a meeting invite for discussion today or tomorrow.

**Comment by duboisp** [comment] 2017-05-19 03:18
Closing this issue since all mentioned concerns/comments has been all addressed and/or resolved with the release WET 4.0.25

**Closed** 2017-05-19 11:40 UTC
Labels: Meta
