### ISSUE TITLE
$summaryContainer.detach in formvalid.js throwing error

### ISSUE THREAD

**Issue by soatley** [wet-boew/wet-boew#7304] opened 2015-12-17 18:47 UTC
There seems to be a problem in the most recent 4.0.19+2 using the Form Validation.  On line 266 of the formvalid.js file, it attempts to detach from the `$summaryContainer` but it hasn't been defined at that point and throws an error in Chrome
`Uncaught TypeError: Cannot read property 'detach' of undefined`

The fix I made locally was to just check `$summaryContainer` first and then detach if needed:

```
if ($summaryContainer) {
     $summaryContainer.detach();
}
```

Not sure if anyone else is running into this but it seems to be happening on my local install.

**Comment by UncleZen** [comment] 2015-12-18 15:39
I too, discovered this bug yesterday.

**Comment by LaurentGoderre** [comment] 2015-12-18 15:44
This seems related: https://github.com/rachelywang/wet-boew/commit/b1e10308e1d03338288fc1a452dc921efa557583

**Comment by andre-gh** [comment] 2015-12-18 16:34
I will take a look, I don't recall any changes to form validation in the latest release.

**Comment by andre-gh** [comment] 2015-12-18 16:36
Indeed, looks like 999482755237d924073aafbb260a0c5eb968c244 in oct

**Comment by andre-gh** [comment] 2015-12-18 17:00
@UncleZen @soatley Am I correct in saying that this error is mostly-harmless in that it only appears in the console and does not prevent anything from occurring functionally speaking as it only occurs when the form is valid?

**Comment by andre-gh** [comment] 2015-12-18 17:07
As far as I can tell, it only prevents the last error from clearing out of the summary before submission but does properly clear out the validation of the field itself and never prevents submission of the form.  Just trying to determine if we need to do a panic release or not.

**Comment by soatley** [comment] 2015-12-18 17:08
For me, it broke when submitting a form that didn't have any errors in it and then stopped processing the rest of the javascript on my page after that point.

**Comment by andre-gh** [comment] 2015-12-18 17:10
Did you receive an IE debug message or something?  That code should have continued to happily run other JS and only halted that specific on change event handler I believe.

**Comment by soatley** [comment] 2015-12-18 17:12
Using Chrome, I receive the message in the console that is in my first message about not being able to read detach on undefined.

**Comment by andre-gh** [comment] 2015-12-18 17:14
Eg. if your IE debugger break-pointed and paused then no other JS would run.  A normal browser should not operate this way (but one with the visual tools might)

**Comment by andre-gh** [comment] 2015-12-18 17:14
And you press submit on the form and nothing occurs?

**Comment by soatley** [comment] 2015-12-18 17:17
In my case, it does stop, but this is a bit of a different page because it's posting encrypted data to another site.  Here's the javascript code that is fired:

```
 $("#btnPPSubmit").click(function () {
                ppSubmit = true;
                $("#btnPPSubmit").after("<div  aria-live=\"polite\" class=\"bold\">Please wait while we send the data to PayPal...</div>").hide();
                $("#addTicket").addClass("hide");

                $("#form1").submit();
                $("#addTicket").removeClass("hide");
                return false;
            });
```

On the `$("#form1").submit();` line the error is thrown and it stops processing.  It doesn't submit the form either.

**Comment by andre-gh** [comment] 2015-12-18 17:18
@soatley Could you verify for me that you do not have "pause on errors" or similar enabled in your chrome dev tools

**Comment by soatley** [comment] 2015-12-18 17:19
No pause on errors or anything.  I didn't actually realize it was happening until a user called saying the site wasn't working.  I guarantee they don't have any breaks set as they're regular users.  I was able to recreate the issue on my end and using the tools was able to fine the problem.

Hope that helps!

**Comment by andre-gh** [comment] 2015-12-18 17:20
@soatley Sorry, didn't get your last message until after I posted.  Yeah, triggering it manually may be changing the behavior....

**Comment by andre-gh** [comment] 2015-12-18 17:24
@soatley Could you verify for me that #7307 properly resolves your issue?

**Comment by andre-gh** [comment] 2015-12-18 17:32
@soatley If you can verify it resolves the issue, I can preform a release over the weekend.  Normally I would preform it Monday but a variety of holiday breaks are coming up with would cause issues releasing then.

**Comment by soatley** [comment] 2015-12-18 17:35
Just tested and it works fine for me with those changes.

**Comment by andre-gh** [comment] 2015-12-18 17:39
@soatley Okay, I spoke with the team and due to the holidays we will not be preforming a full release.  We will however push the build out and I can link you to a fully built development build to use once that finishes.

**Comment by soatley** [comment] 2015-12-18 17:41
No problem with me.  I've adjusted my code internally to handle it until the next release.

**Comment by andre-gh** [comment] 2015-12-18 17:42
@soatley Thank you, I will not rush to get all the dev builds of all the themes out then.

**Comment by hsrudnicki** [comment] 2016-01-29 19:23
Based on the above, can be this issue closed as resolved/fixed or if otherwise?  Either way, please update this issue's status, thank yo

**Comment by hsrudnicki** [comment] 2016-08-17 15:55
Is this still an issue? Can be this closed as a duplicate of the 7304 issue?

**Comment by masterbee** [comment] 2016-11-05 05:37
closing since the caller's (creator of issue) issue appears to have been addressed and integrated in the build.

**Closed by masterbee** 2016-11-05 05:37 UTC
