### ISSUE TITLE
Problem with Equal Heights

### ISSUE THREAD

**Issue by keithcolbourne** [wet-boew/wet-boew#6680] opened 2015-04-13 15:59 UTC
Hi,

Using: WET template 4.09. 
Integration with CMS.

We are having an issue with implementing the equal heights functionality (http://wet-boew.github.io/v4.0-ci/demos/equalheight/equalheight-en.html). 

The problem seems to be occurring when we have multiple sets of equal heights sections. The functionality seems to be applying the equal heights to ALL sections. We can't separate into different sets. It looks to be an issue with the application of the min-height property as an in-line style and the min-height inheritance. That same min-height is being applied to all sections, we want to be able to inherit for specific set of sections and have that value set to something different for another set...make sense? I assume it's being applied through your jQuery.

What we need is the ability to have multiple sets of differing equal heights on the same page. 

Wondering if this was taken into consideration when developing this functionality.

Thank You!
Keith Colbourne
Dept of National Defence

**Comment by LaurentGoderre** [comment] 2015-04-13 16:19
Can you add your markup so that we can take a look at it?

**Comment by keithcolbourne** [comment] 2015-04-13 17:39
I've been experimenting with different variations for css. Do you have a working example?

An example using WET classes (I've also done with customized css), rendered markup would be as follows:


<div class="wb-eqht col-md-8" id="ehc-1428129317969">
<div class="col-md-6 ">
<h2 class=" bg-primary  ">Dead Man Quotes</h2>
<section class="hght-inhrt  well well-sm"><p>Nobody: Every night and every morn, some to misery are born. Every morn and every night, some are born to sweet delight. Some are born to sweet delight; some are born to endless night.</p></section>
</div>
<div class="col-md-6 ">
<h2 class=" bg-primary  ">Dead Man Quotes</h2>
<section class="hght-inhrt  well well-sm"><p>&nbsp;</p>
<p>William Blake: What is your name?</p>
<p>Nobody: My name is Nobody.</p>
<p>William Blake: Excuse me?</p>
<p>Nobody: My name is Exaybachay. He Who Talks Loud, Saying Nothing.</p>
<p>William Blake: He who talks... I thought you said your name was Nobody.</p>
<p>Nobody: I preferred to be called Nobody.</p></section>
</div>
</div>


<div class="wb-eqht col-md-8" id="ehc-1428129317970">
<div class="col-md-6 ">
<h2 class=" bg-info  ">Stranger Than Paradise Quotes</h2>
<section class="hght-inhrt  well well-sm"><p>Willie: Here, let me tell you a joke, all right? There's three guys, and they're walking down the street. One guy says to the other one, "Hey, your shoe's untied." He says, "I know that." And they walk... No... There's two guys, they're walking down the street, and one of them says to the other one, "Your shoe's untied." And the other guy says, "I know that." And they walk a couple blocks further, and they see a third friend, and he comes up and says, "Your shoe's untied." "Your shoe's un - " Aaah, I can't remember this joke. But it's good.</p></div>
</section>
<div class="col-md-6 ">
<h2 class=" bg-info  ">Stranger Than Paradise Quotes</h2>
<section class="hght-inhrt  well well-sm"><p>Eddie: You know, it's funny... you come to someplace new, an'... and everything looks just the same.</p>
<p>Willie: No kiddin', Eddie.</p></section>
</div>
</div>

When doing further inspection, it appears the wb-eqht jQuery funtionality applies style="MIN-HEIGHT: 477px" to all of the div class="col-md-6" children in the above example. The divs in the second set are never able to compute this for themselves.

**Comment by thomasgohard** [comment] 2015-04-14 14:08
@keithcolbourne equal heights does support multiple groups being equalised independently.

I put your markup into a blank page and both groups have different heights:
![eqht-dff-hghts](https://cloud.githubusercontent.com/assets/1810242/7138312/876f4022-e28d-11e4-87a0-c5360b0f2705.png)

**Comment by LaurentGoderre** [comment] 2015-04-14 14:21
@keithcolbourne on a side note, the heading should be inside the section element. Here is a simplified version of the code

```html
<div class="wb-eqht col-md-8" id="ehc-1428129317969">
	<section class="col-md-6">
		<h2 class="bg-primary">Dead Man Quotes</h2>
		<div class="hght-inhrt well well-sm">
			<p>Nobody: Every night and every morn, some to misery are born. Every morn and every night, some are born to sweet delight. Some are born to sweet delight; some are born to endless night.</p>
		</div>
	</section>
	<section class="col-md-6 hght-inhrt">
		<h2 class="bg-primary">Dead Man Quotes</h2>
		<div class="well well-sm">
			<p>&nbsp;</p>
			<p>William Blake: What is your name?</p>
			<p>Nobody: My name is Nobody.</p>
			<p>William Blake: Excuse me?</p>
			<p>Nobody: My name is Exaybachay. He Who Talks Loud, Saying Nothing.</p>
			<p>William Blake: He who talks... I thought you said your name was Nobody.</p>
			<p>Nobody: I preferred to be called Nobody.</p>
		</div>
	</section>
</div>
```

**Comment by LaurentGoderre** [comment] 2015-04-14 14:22
You also have the ` character after your equalheights which cause some issues

**Comment by keithcolbourne** [comment] 2015-04-14 14:48
Thank you for the replies. 

I'm glad to hear it's supported. It could be an integration thing with our CMS because I'm not getting the same results as you @thomasgohard 

@LaurentGoderre the ` charcter is there as a result of playing around with the markdown. It's not in the actual source. This is the first time I've used markdown here. Also, I believe we put the header outside for CMS integration. 

Unfortunately, I can't test this today. I got put on another priority. I hope to return to it tomorrow or the next day. I can update then. This is still not resolved. Thanks

**Comment by keithcolbourne** [comment] 2015-04-16 18:07
@thomasgohard @LaurentGoderre

Are you guys able to provide a working example in the WET4 template? The jQuery issue is persisting.

Thank You

**Comment by thomasgohard** [comment] 2015-04-16 19:56
@keithcolbourne the [working examples page for Equal height](http://wet-boew.github.io/wet-boew/demos/equalheight/equalheight-en.html) has three separate blocks that are processed independently of one another.

Do you have a live page we can look at?

**Comment by keithcolbourne** [comment] 2015-04-16 20:14
@thomasgohard @LaurentGoderre
Yes...but they are all the exact same size,  All nine blocks, all three sets. Did you test one with a much longer bit of text? Each set has the same content in your working example.

Thank you

**Comment by LaurentGoderre** [comment] 2015-04-16 20:21
I am working on a unit test to prove the bug or not

**Comment by thomasgohard** [comment] 2015-04-16 20:21
@keithcolbourne they do have different heights:
![eqht-dff-hghts](https://cloud.githubusercontent.com/assets/1810242/7190448/5953aa5c-e454-11e4-96b1-4812b197af58.png)
This is when the first two sets have two blocks per row and the third set has four blocks per row.

**Comment by thomasgohard** [comment] 2015-04-16 20:22
@LaurentGoderre :+1:

**Comment by LaurentGoderre** [comment] 2015-04-16 20:54
My unit demonstrates that the plugin supports multiple independent blocks.

**Comment by keithcolbourne** [comment] 2015-04-17 12:40
@thomasgohard @LaurentGoderre
Hmmm...It must be my browser or something because they don't have different heights for me. I'm using Chrome and also IE. I didn't include the nested example but the the code below clearly shows it's not working for me. 479px height on all nine blocks


```
<div class="wb-eqht wb-init wb-eqht-inited" id="wb-auto-1">
<section style="vertical-align: top; min-height: 479px;">
<h3>Short container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Medium container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
<p>Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Long container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
<p>Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text.</p>
<p>Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text.</p>
</section>
</div>


<div class="wb-eqht wb-init">
<section style="vertical-align: top; min-height: 479px;">
<h3>Short container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Medium container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
<p>Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Long container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
<p>Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text.</p>
<p>Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Short container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Medium container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
<p>Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text.</p>
</section>
<section style="vertical-align: top; min-height: 479px;">
<h3>Long container</h3>
<p>Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text. Example text.</p>
<p>Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text. Different example text.</p>
<p>Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text. Other example text.</p>
</section>
</div>
```

But the text is also exactly the same so I don't know how you got your result.

@LaurentGoderre can you share your test? 

If we can't get this working properly, it is going to affect our upgrade to WET4 because some of our clients already use multiple equal heights in WET3. We are really hoping not to have to customize this. Thanks

Thank You

**Comment by LaurentGoderre** [comment] 2015-04-17 13:41
Here is where the test is

https://github.com/LaurentGoderre/wet-boew/commit/0aa172203a88ff0f2faa8d1d589344aebbb75493#diff-263b907ca72d757d57f02482f8848ee2R265

**Comment by thomasgohard** [comment] 2015-04-17 13:44
@keithcolbourne how many blocks are appearing in a row in your browser? Two or three? Because if you have three blocks appearing in a row, they will all have the same height since each row would contain one of the tallest blocks.

**Comment by keithcolbourne** [comment] 2015-04-17 14:12
@thomasgohard @LaurentGoderre 

Ha...it's resizing based on row, not on the actual sections included in the wb-eqt div? I assumed all the sections in that div would have the same height. So it seems this is built with *resizing* in mind. We are more concerned with the **initial** size. I think this might explain the divide in our thinking here.

When I resize my browser so they are in rows of 2, instead of 3, it works. I'd still like to see the row of 3 work. The working example isn't a good test because as I've mentioned, the largest block in each row has the exact same text. 

In any case, I appreciate the help but we still have the issue. I suppose we'll have to come up with a way to make it work for us through customization.

**Comment by LaurentGoderre** [comment] 2015-04-17 14:39
@keithcolbourne I don't follow. Resizing is the hard part of this. How is it not meeting your needs? My tests works with a row of 3.

**Comment by keithcolbourne** [comment] 2015-04-17 14:48
It's hard for me to speak in terms of your example because I can't see that, there's not a corresponding working example, just the test script. 

Resizing is not something we care about for this. I'm not sure how to accurately explain it but let me try...if you think about the working example, think about the 3 rows as 3 differently coded sets with different types of information (one set about tanks, one about jets, one about submarines to give a DND example). We don't care how they line up according to each other, just to the others in their own set. 3 wb-eqt divs. I would like to see the working example contain varying lengths for the sets in the static, original position. Make sense?

**Comment by LaurentGoderre** [comment] 2015-04-17 14:49
Can you please draw a diagram with boxes to illustrate that because I don't think words is helping us here

**Comment by keithcolbourne** [comment] 2015-04-17 14:51
hahaha! Ok fair enough! Give me some time

**Comment by keithcolbourne** [comment] 2015-04-17 17:27
@thomasgohard @LaurentGoderre

Guys, what we are trying to accomplish is like something in this image. Shown are 3 sets of *varying* equal heights. We can't accomplish this with the way it's currently functioning.

![ehc-examples-of-varying-heights-of-sets-of-columns](https://cloud.githubusercontent.com/assets/2145117/7207135/3fe3f426-e505-11e4-97da-c35f9d237e2a.png)

**Comment by LaurentGoderre** [comment] 2015-04-17 19:02
Yes, this is exactly what my test proved works

**Comment by keithcolbourne** [comment] 2015-04-17 19:10
Then how about showing me a working example? Code tells me nothing  It would take five mins to change the existing one.

**Comment by keithcolbourne** [comment] 2015-04-17 19:11
Do you understand what I'm showing here? Do not think about resizing. All of the divs in my example would have the same min-height applied to them from my experience so far with this functionality. We don't want that.

**Comment by LaurentGoderre** [comment] 2015-04-17 19:36
Ok the bug occurs only when the equalheight container contain a grid class. If you remove the `col-md-8` on the parents it works. We should probably fix this though

**Comment by keithcolbourne** [comment] 2015-04-17 19:41
Oh interesting! I'll try this out on Monday morning and get back to you.

Thanks for your efforts! Have a great weekend

**Comment by keithcolbourne** [comment] 2015-04-17 19:46
Scratch that. I'm off Monday. I'll let you know on Tuesday. :)

**Comment by keithcolbourne** [comment] 2015-04-21 19:11
So I tested and yes, removing the width class (col-md-8) resolves this issue. 

However, this presents a problem for us in that now our users can't select the width of this feature/widget/component. We'd have to write something custom to wrap an extra div or create custom class/logic, etc. We like to follow WET as closely as possible before customizing so this presents the question: will you guys look to fix this bug or are we on our own to come up with something?

Thanks

**Comment by LaurentGoderre** [comment] 2015-04-21 19:21
We will need to fix it.

**Comment by keithcolbourne** [comment] 2015-04-21 19:25
Thanks...do you have a timeline as to when it will be worked on -- i.e is it a priority? We are hoping to release our WET4 upgrade in mid-to-late May.

**Comment by LaurentGoderre** [comment] 2015-04-21 20:16
tès medium priority and probably should get fixed within a month

**Comment by LaurentGoderre** [comment] 2015-04-21 20:16
@crichard is this something you can look into?

**Comment by thomasgohard** [comment] 2015-04-21 20:52
Some of this was starting to sound familiar so I did a quick search and found the thread: https://github.com/wet-boew/wet-boew/issues/4145. A solution is described in [this comment](https://github.com/wet-boew/wet-boew/issues/4145#issuecomment-35767971). A markup example is in [this comment](https://github.com/wet-boew/wet-boew/issues/4145#issuecomment-35762656).

@keithcolbourne can you see if that solution still works? Otherwise I'll have to look at what code changes happened from that point on to find out when it ceased to work.

**Comment by crichard** [comment] 2015-04-22 12:24
I can take a look.  I tried to reproduce the problem but I haven't been able to, or I am not grasping the problem correctly.  @keithcolbourne can you send me your markup please (content isn't so important, what I need are all the containers with classes exactly as you want to use them)?  This is for the WIM right?

**Comment by keithcolbourne** [comment] 2015-04-22 12:48
Hi @crichard, yes, it's for the WIM. We have an "Equal Heights Column" component that uses this technology. It's used quite a bit in our current WET3 implementation. So besides issues using this on new pages, we also have concern with migration to WET4, if we can't get this to work properly, several clients and pages will be negatively affected. 

You can use the code from my first example way up above. I confirm that it works when I remove the width class on the parent (col-md-8) - however this presents a problem in that users would then not be able to choose the width of the component and they would all be 100%. The main consideration is for you to not think about resize. We don't care about that in the least. We just want varying lengths equal heights (you can view the graphical mock-up I attached above as well to see an example). 

@thomasgohard I'll take a look at what you referenced and see if there's anything there that can help. I'll let you know.

Thanks everybody!

**Comment by keithcolbourne** [comment] 2015-04-22 12:59
@crichard Also...feel free to call me if you want at 613.996.3839 in case you need me to explain further

**Comment by LaurentGoderre** [comment] 2015-04-22 13:23
@crichard this markup is reproducing the problem

```html
<div class="wb-eqht col-md-8">
	<div class="col-md-6">
		<ul>
			<li>One</li>
		</ul>
	</div>
	<div class="col-md-6">
		<ul>
			<li>One</li>
			<li>Two</li>
			<li>Three</li>
			<li>Four</li>
		</ul>
	</div>
</div>

<div class="wb-eqht col-md-8">
	<div class="col-md-6">
		<ul>
			<li>One</li>
		</ul>
	</div>
	<div class="col-md-6">
		<ul>
			<li>One</li>
			<li>Two</li>
			<li>Three</li>
			<li>Four</li>
			<li>Five</li>
			<li>Six</li>
			<li>Seven</li>
			<li>Eight</li>
		</ul>
	</div>
</div>
```

**Comment by keithcolbourne** [comment] 2015-04-22 13:46
@thomasgohard I'm not sure I see the connection with the referenced issue. Adding class "row" doesn't fix the original problem and we are still stuck with not being able to apply the parent width. Am I understanding this correctly? 

We set widths on both the parent and the children so I'm not sure if you were intending to hardcode those col-xs-xx col-sm-xx col-md-xx classes.

Thanks for the suggestion, though but it looks like we will need the bug fix

**Comment by hsrudnicki** [comment] 2015-06-17 14:40
Can this issue be closed?

**Comment by keithcolbourne** [comment] 2015-06-17 17:13
No, sorry. I was told there would be a bug fix for this. So unless that fix has been completed, it's still an issue...I haven't been told the bug was fixed so as far as I know, it still exists. Don't know what that change Laurent made on 15 May was.
Thanks
Keith

**Comment by LaurentGoderre** [comment] 2015-06-17 18:43
This is still an issue

**Comment by duprasf** [comment] 2015-11-25 22:04
@keithcolbourne Good news! I provided a patch to the equalheight plugin while working on my issue #7153, that should fix this issue as well. I tested with the code provided by @LaurentGoderre in his April 22nd comment and it now works as expected. I would appreciate if you could let us know if it works for you.

**Comment by keithcolbourne** [comment] 2015-11-26 16:43
@duprasf This sounds great, thanks. Upgrading to a full new version of WET would not be doable for us at the moment (even for testing) but if there is a specific file we can test, I can do that. Is there one specific file that you changed to do this? Or would there be too many dependencies with that?

We are currently on 4.0.9 (except for wet-boew.min.js which is 4.0.16)

Thanks

**Comment by duprasf** [comment] 2015-11-26 16:52
I'm not sure why you are not changing all your files since there are only minimal change between version with the same minor version (4.0.x). You might actually introduce some bugs if you update the .js file that requires a updated version of the .css file, but that's your choice. 

The only file that will be updated by my fix is the wet-boew.min.js file.

**Comment by keithcolbourne** [comment] 2015-11-26 17:09
Thanks.

We can't update the full version because of the amount of testing it would introduce for us. (these files are integrated with an enterprise CMS)

Which version of wet-boew.min.js? 4.0.19? 

thank you

**Comment by duprasf** [comment] 2015-11-26 17:56
Yes, when 4.0.19 comes out, scheduled for next week, the patch should be included.

**Comment by keithcolbourne** [comment] 2015-11-26 18:08
Is that file available to me now to test? Thanks

**Comment by duprasf** [comment] 2015-11-26 18:28
That I don't know, I am not a WET developer, just a user. But if you look at the issue #7153 you can see the modified code and paste it into the wet-boew.js (not the minimize file) and test it that way, that's how I developed and tested the solution.

Maybe someone from the development team can tell you how to get a build from master if you want to test with the min file right away.

**Comment by keithcolbourne** [comment] 2015-11-26 18:31
Ok, thanks very much. We can wait for the supported version to be released and then test.

**Comment by andre-gh** [comment] 2015-11-26 18:51
@keithcolbourne @duprasf The patch appears to be failing unit tests on nested elements and I am not sure if it will make it into the next release.  I personally am not too familiar with the equal heights plugin.

**Comment by duprasf** [comment] 2015-11-26 19:04
I don't know how to work with the test suite, but the only thing I can say is that we proved that there was more than one problem with the existing code and yet it passed the test. With this new code, the test fails, maybe there is a problem with the test itself?

I can try to take a look at the test but since I never worked with a test suite, I don't know what I can do.

**Comment by andre-gh** [comment] 2015-11-26 19:05
@duprasf I can look into this, hopefully I can merge the fix Monday, the test file is confusingly written.

**Comment by duprasf** [comment] 2015-11-26 19:25
Looking at the javascript test file, I think I might know what the problem is. First on line 39, the test expect that a single element on its row would have a min-height of 0, I did not do that, the min-height of a single element would be his own height.
The failed test number 5 ("Error: expected 176 to equal 175") is probably due to the fact that I added a 1px to all height since I came across some edge case scenario where the elements did not position themselves correctly when the last element was shorter than the others.

**Comment by andre-gh** [comment] 2015-11-26 23:10
@duprasf Looks right, this test framework is failing to even work locally for me so I had some frustrations but I believe I have it working.  I am new on this project.

**Comment by keithcolbourne** [comment] 2015-11-27 13:49
@andre-gh @duprasf Thanks guys. Can you update this ticket once this fix is released? We will test in our environment then. Thanks again
Keith

**Comment by andre-gh** [comment] 2015-12-01 21:42
@keithcolbourne @duprasf The release is fully deployed now for all themes.

**Comment by keithcolbourne** [comment] 2015-12-02 14:15
Thanks! So the UT issues were resolved?

**Comment by andre-gh** [comment] 2015-12-02 15:26
@keithcolbourne Yes, I worked to get the patch merged properly in for this release as I did not want to leave an outstanding bug like equal heights not working correctly.  Could you see if your issue is resolved?

**Comment by keithcolbourne** [comment] 2015-12-02 15:31
Great, I just did a test in my dev environment and it looks to be resolved. Good stuff. I am going to pass it along for further testing to our QA team and I will report back once that testing is completed. That will be a few days. Thanks.

**Comment by duprasf** [comment] 2015-12-02 15:33
That's great, I'm happy I could fix your bug. Let me know if they find anything else.

**Comment by hsrudnicki** [comment] 2015-12-08 18:36
Made "Going Stale' in order to close this issue soon as resolved/fixed or otherwise? Either way, please keep this issue's status updated, thank you

**Comment by keithcolbourne** [comment] 2015-12-08 20:16
@hsrudnicki It's only been 6 days since it was last updated.

We have just discovered that It's not resolved for us. After our QA team tested we determined that the fix appears to work for IE11 but not for IE9. Unfortunately, the Department of National Defence still uses IE9 as the baseline server. We are not upgrading until 2016. So we have to wait until we can fully test. You can probably close this for your purposes but we will again test when IE11 is rolled out and re-open the ticket if required. Thank you.

**Comment by duprasf** [comment] 2015-12-08 20:20
I still have a computer with IE9, I can take a look at it and try to fix it for you. Was it tested with  LaurentGoderre's code from Apr 22 in this issue? If not can you post the HTML used?

**Comment by andre-gh** [comment] 2015-12-08 20:20
@keithcolbourne Does it function in IE10?

**Comment by keithcolbourne** [comment] 2015-12-08 20:38
Sure. Here's an example of the HTML output:
```
<div class="wb-eqht col-md-6     ">
<section class="col-md-6 panel-success">
<header class="panel-heading">
<h2 class=" panel-title  ">Block 1</h2>
</header>
<div class="eqht-col eqht-col-panel bg-panel">
<div class="panel-body "><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus commodo, enim non aliquam cursus, libero massa ornare tellus, tincidunt vulputate nibh turpis quis dui. Sed euismod condimentum velit at fringilla. Donec nunc justo, maximus vel mauris quis, fringilla commodo lectus. Nam feugiat pretium ligula ut ullamcorper. Praesent fringilla dignissim purus ut auctor.</p>
<div class="clearfix"></div>
</div>
</div>
</section>
<section class="col-md-6 panel-success">
<header class="panel-heading">
<h2 class=" panel-title  ">Block 2</h2>
</header>
<div class="eqht-col eqht-col-panel bg-panel">
<div class="panel-body "><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus commodo, enim non aliquam cursus, libero massa ornare tellus, tincidunt vulputate nibh turpis quis dui. Sed euismod condimentum velit at fringilla. Donec nunc justo, maximus vel mauris quis, fringilla commodo lectus. Nam feugiat pretium ligula ut ullamcorper. Praesent fringilla dignissim purus ut auctor. Suspendisse tristique commodo sem quis hendrerit. Nulla eu sapien enim. Proin interdum eros sit amet neque facilisis convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam imperdiet, velit a feugiat volutpat, dolor tellus tempus enim, nec rhoncus tortor dui sit amet turpis.</p>
<div class="clearfix"></div>
</div>
</div>
</section>
```
It's tested with v4.0.19 so I assume that has whatever Laurent would have added.

Not tested in IE10. 

Thanks

**Comment by andre-gh** [comment] 2015-12-08 20:42
@duprasf if you have a fix by Thursday morning it can make it into a fix release we are doing on Monday, otherwise it will not make it until the next release, the next planned release after that is in three months.

**Comment by duprasf** [comment] 2015-12-08 20:58
I can't see anything wrong using IE9 32 and 64bits. I copied your code, added the missing closing div, surrounded it with  a ```<div class="row>``` (```<div class="clearfix"></div>``` above and below your code was tested and works just as well), then the javascript sets both section to the same height. If you can provide any more information about the problem I will be happy to try to get it out tomorrow so it can be in next Monday's release.

**Comment by keithcolbourne** [comment] 2015-12-09 13:51
I might have just missed copying the div, the xml is valid at the source.

I can try playing with code as you suggest for IE9 purposes. If I recall, 'row' class introduces it's own set of css issues, we've had to remove it in several places. I'll take a look.

Thanks

**Comment by keithcolbourne** [comment] 2015-12-09 14:40
Yeah, no go. It looks like we will wait for the IE11 upgrade. If you really want to see how it appears, our QA team has taken several screenshots. I can include those if you wish but at this point it looks like we'll wait.

Thank you much.

**Comment by hsrudnicki** [comment] 2016-08-15 17:39
Please update this issue's status/milestone, for this current year, whether this issue can be closed or otherwise? Thank you

**Comment by Bgolden67** [comment] 2016-10-20 16:39
I know this is an old thread.. but is there a new class for equal height in wet 4.0.22? I can't seem to find any reference.

**Comment by sylus** [comment] 2016-12-07 15:35
@LaurentGoderre I think this is still an issue.

**Comment by kodecount** [comment] 2016-12-07 15:39
It also a issue with #7752 and #7797 when using tabs the `min-hieght` creates white-space issues (and much more).

**Comment by LaurentGoderre** [comment] 2016-12-08 13:33
@sylus I think you're having a different problem because this works in Firefox and IE11. I'm inclined to close this since ther is possibly only issues with IE9 (didn't test it) and IE9 is not supported anymore

**Comment by LaurentGoderre** [comment] 2016-12-08 14:27
Closing since it only affects IE9 now

**Closed by LaurentGoderre** 2016-12-08 14:27 UTC
Labels: Bug Report: Normal, Plugin: Equalize

**Comment by keithcolbourne** [comment] 2016-12-08 15:21
Just FYI, if the white-spacing issue (padding added) is not resolved, we will be opening a new bug/issue as this is going to be a new requirement in our product (WCMS) in an upcoming release.

**Comment by LaurentGoderre** [comment] 2016-12-08 16:20
No problem!
