### ISSUE TITLE
Tables: 

### ISSUE THREAD

**Issue by DTardioli** [wet-boew/wet-boew#7585] opened 2016-06-21 17:39 UTC
The Canada.ca Style Guide shows that a table cell with no data should be represented by either of the following:
•	“no data”
•	“0” (zero)
•	“n/a” (not applicable)"

**Comment by gdanova** [comment] 2016-08-03 17:34
I don't believe this is necessary for accessibility, and empty cells, especially in a simple table, are often desired.

**Comment by hsrudnicki** [comment] 2016-09-09 17:58
Does this remain still an issue or otherwise?  Please update the status of this again, whether this can be closed as duplicate of the 7488 issue or otherwise, thx

**Comment by DK-TBS** [comment] 2016-09-09 19:17
definitely a duplicate

**Comment by hsrudnicki** [comment] 2016-09-09 19:42
This is closed due to the duplicate issue: 7488, which had been raised earlier, as well still continued discussion to resolve the same open issue.

**Closed by hsrudnicki** 2016-09-09 19:42 UTC
Labels: Close: Duplicate
