### ISSUE TITLE
Tabbed Interface: Bug, Tabs gone when you disable images on chrome

### ISSUE THREAD

**Issue by leechristenson** [wet-boew/wet-boew#7694] opened 2016-10-13 14:37 UTC
Bug - tabs vanish while using Google Chrome.

While using google chrome, if images are disabled while using the Web developer tools the tabs that are currently on the page are disabled as well and vanish. 

Please Look at the screen shots below.

![screen-1](https://cloud.githubusercontent.com/assets/22796599/19353059/c7e4b002-9127-11e6-883d-4e8397fe99a8.jpg)

![screen-2](https://cloud.githubusercontent.com/assets/22796599/19353074/cb6ae85e-9127-11e6-95bd-be6d63a2a98f.jpg)

Also this is on desktop size, it seems to work on mobile.

**Comment by masterbee** [comment] 2016-11-05 01:22
@leechristenson - this is an interesting issue and I downloaded a few other disable images plugins and was able to successfully disable images without the tabs going away. I also tired firefox and was successful at disable images without the the mentioned issue. 

I can see how this can be a bit annoying but this appears to be a vendor plugin issue that is isolated to the browser version of the plugin. I took a quick peek at the authors website and there are a few issues related  ,"known issues" he called it, that revolve around the disabling of background issues and other image type treatments. https://chrispederick.com/work/web-developer/issues/

My suggestion would be to open a ticket with the authors and see where that research leads, he is probably better positioned to address what the root of the problem is. 

I will close the issue since there is not much we can do at the moment, but welcome you to open a new ticket once the author and you find out what is causing this type of conflict.

**Closed by masterbee** 2016-11-05 01:22 UTC
