### ISSUE TITLE
wb-charts: apostrophe in caption breaks the graph

### ISSUE THREAD

**Issue by pierrelalonde** [wet-boew/wet-boew#7346] opened 2016-01-21 16:14 UTC
If a table caption contains one or more apostrophes, the graph in is not rendered at all. Html encoding the apostrophe does not work.
.
\<table class="wb-charts table">
  \<caption>Here's a caption with an apostrophe.\</caption>
  \...

*We should have a graph just below the figcaption text:*
![21-01-2016 11-00-16 am](https://cloud.githubusercontent.com/assets/16809565/12485983/8f14e74e-c02e-11e5-8bf2-bef51bc93822.jpg)

*With the apostrophe removed, the graph works:*
![21-01-2016 11-00-58 am](https://cloud.githubusercontent.com/assets/16809565/12486066/f520b414-c02e-11e5-910d-a3fc1814d651.jpg)

**Comment by LaurentGoderre** [comment] 2016-01-21 16:58
Duplicate of #6079

**Comment by hsrudnicki** [comment] 2016-02-19 18:38
Can, be be this issue closed as well as the referenced issue [6079] (based on the last comment from @LaurentGoderre )?

**Comment by pierrelalonde** [comment] 2016-02-22 14:28
No, the issue has not been resolved.

**Comment by LaurentGoderre** [comment] 2016-02-22 22:20
Closing in favor of the first issue

**Closed by LaurentGoderre** 2016-02-22 22:20 UTC
Labels: Close: Duplicate
