### ISSUE TITLE
Topics menu in Firefox - WET 4.0.13

### ISSUE THREAD

**Issue by jptherrien** [wet-boew/wet-boew#6779] opened 2015-05-15 13:56 UTC
Hi,
It seems that the topics menu is not displayed in the same way with Firefox than others browsers like IE. I've used Firefox 38 and IE 10 to do the test. With Firefox the menu start in the middle of the page. I compared the results with existing sites that use WET 4.0 as  http://www.justice.gc.ca/fra/index.html , http://www.victimsweek.gc.ca/home-accueil.html and http://www.section15.gc.ca/eng/index.html and others.

**Comment by LaurentGoderre** [comment] 2015-05-15 14:29
Duplicate of https://github.com/wet-boew/theme-gcwu-fegc/issues/189

**Closed** 2015-05-15 14:29 UTC
Labels: Close: Duplicate, Theme: GCWU
