### ISSUE TITLE
Overlay in landscape view--Android-Samsung Galaxy S4 mini

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5113] opened 2014-04-02 18:10 UTC
None of the overlays can be closed with the X button in landscape view--must tap other parts of the screen

**Comment by hsrudnicki** [comment] 2015-06-09 14:47
Are you ready to close this issue ?

**Comment by pjackson28** [comment] 2015-06-09 19:45
The issue might be because of a problematic browser build on the S4 mini. It seems to have a lot of display issues where no other phone/browser combination had issues, including Android browser on an Android phone. I am still unable to reproduce on any device I have access to. Can anyone still reproduce the issue? If not, then we should close as a can't reproduce.

**Comment by pjackson28** [comment] 2015-06-09 19:59
I just checked and the default browser for the Samsung S4 Mini is out of the support window. It ran Android 4.2.2 (API level 17) which ran WebKit 534.30. The WebKit version has been at least 537.36 since Android 4.4 and Android 5.1 (API level 22) is now available.

So closing because we can't reproduce the issue and because the browser in question is outside of the support window.

**Closed by pjackson28** 2015-06-09 19:59 UTC
Labels: Browser: Android, Plugin: Overlay
