### ISSUE TITLE
WET validation fails on text box with spaces provided

### ISSUE THREAD

**Issue by fahmyr** [wet-boew/wet-boew#7794] opened 2016-12-01 21:23 UTC
In the sample form http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html the required field validation fails if the text box is populated with space characters. You would expect that the values would be trimmed before being validated such that spaces would not be valid. 

Note that this behavior was observed on the sample page, but for some reason when it was implemented on our site the validation does work as expected, the only difference is that we do not use pattern=".{2,}" data-rule-minlength="2" attributes. I suspect this is the case because a single space does not fail only 2 or more spaces.

![wettextvalidationerror](https://cloud.githubusercontent.com/assets/5008215/20812962/a5aa5b0a-b7e1-11e6-95a5-79b4616ab86c.JPG)

**Comment by nschonni** [comment] 2016-12-01 22:19
Duplicate of #7557

**Closed by nschonni** 2016-12-01 22:19 UTC
