### ISSUE TITLE
Datepicker plugin & form validation

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#5532] opened 2014-06-03 17:59 UTC
When the datepicker is within a form element with validation (i.e. `<div class=”wb-frmvld”>..<form>..<input type=”date”/>.. </form>..</div>`), a javascript error gets generated when I try to select another Month or Year.

The errors can be reproduced on the form validation example page:
http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

-	Click the calendar icon, 
-	then click on the Month link (shows the “jump to” options for Month & Year).
-	Make a selection in any of the dropdown lists and it’ll generate the javascript errors

This happens in IE (using IE 8) and Firefox (using FF 23.0)

More Info if needed:

Webpage error details - IE
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
Timestamp: Fri, 30 May 2014 14:28:01 UTC

Message: 'settings' is null or not an object
Line: 11
Char: 4766
Code: 0
URI: http://wet-boew.github.io/v4.0-ci/js/deps/jquery.validate.min.js

Error Details - FF
TypeError: c is undefined jquery.validate.min.js:11
TypeError: c is undefined jquery.validate.min.js:11
TypeError: c is undefined jquery.validate.min.js:11

Using the unmin version of jquery.validate, we can see that it’s occurring when trying to get the validator of the form, which is “undefined”.
```js
                function delegate(event) {
                                var validator = $.data(this[0].form, "validator"),
                                                eventType = "on" + event.type.replace(/^validate/, "");
                                if ( validator.settings[eventType] ) {
                                                validator.settings[eventType].call(validator, this[0], event);
                                }
                }
```
Looks to be occurring since it’s trying to validate on the form of the datepicker (`<form id="cal-wb-picker-goto" role="form"`) which doesn’t have any validator set for that form.
Should there even be any validation happening on the calendar dropdown lists?

**Comment by RobJohnston** [comment] 2015-02-17 21:03
Has this been fixed?  I can't reproduce it on the form validation example page but a local version running 4.0.9 produces the error in IE9 (all I got to work with today).  Other people around the 'net fix it with a variation of what was mentioned in https://github.com/jzaefferer/jquery-validation/issues/518.

**Comment by RobJohnston** [comment] 2015-02-19 19:19
I've looked a bit more into this and it appears to only be a problem when the page is served via ASP.NET Development Server (the one built into Visual Studio).  When the page is deployed to IIS then the problem goes away.  Interestingly, the only thing I have to do to make it show (locally) is wrap the DatePicker example in ```<div class="wb-frmvld">```.

@nschonni  I think the IE7 label can be removed as that was never mentioned in this issue.  IE8 and IE9 were.

**Comment by hsrudnicki** [comment] 2015-06-10 15:17
Can be this issue closed or otherwise?

**Comment by RobJohnston** [comment] 2015-06-10 15:36
The form validation page (http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html) is still broken for IE 11 but is working for FF 38.0.

The date picker example (http://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html) works only because it is not wrapped in ```<div class="wb-frmvld">```.

**Comment by hsrudnicki** [comment] 2015-06-10 15:54
@pjackson28 @LaurentGoderre :  see the recent response from @RobJohnston in order to make a decision in closing this issue or updating its status

**Comment by GarthMartin** [comment] 2015-06-16 17:20
I too have this issue, even when not running locally, i.e. served by IIS not Visual Studio as @RobJohnston mentioned.

**Comment by hsrudnicki** [comment] 2015-11-06 16:49
Please continue updating this issue's status in milestone(s) whether this issue can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment] 2016-03-02 20:59
Is this still an issue? Either way, please update this issue's status, whether this issue can be closed as already resolved/fixed, based on the milestone settings, or if otherwise? Thank you

**Comment by RobJohnston** [comment] 2016-03-03 12:15
The date picker has been completely overhauled, so I don't get an error any more.

**Comment by LaurentGoderre** [comment] 2016-03-03 14:01
Nice! Can we close then?

**Comment by masterbee** [comment] 2016-04-18 01:27
Closing since error is not present anymore

**Closed by masterbee** 2016-04-18 01:27 UTC
Labels: Browser: IE8, Plugin: Form Validation (jQuery Validation), Polyfill: Date picker
