### ISSUE TITLE
No clean way to wrap error text inside the label it's associated to

### ISSUE THREAD

**Issue by CubicleKid** [wet-boew/wet-boew#7675] opened 2016-09-26 17:51 UTC
We are using Bootstrap for column definitions in this example and WET-boew version 4.0.21, Visual Basic (2013 premium) and Razor

Our difficulty is in adhering to accessibility standards for presenting errors on a page as word wrapping is not working well at all.
We wish to present a legible error associated to a label within that label's tags.

There are two ways we can display the label. 
1. By using classes "Alert Alert-Danger"
2. By using classes "Label Label-Danger"

Method 1 shows very ugly with the alert wrapping and its layers interfere with the user's ability to read the text.
Method 2 does not word wrap as 'white-space: nowrap' is inherited from the Label class. 

**Method 1 source:**
```
 @<div class="form-group">
        <label for="ProjectNumber" class="col-md-5 control-label required">
            <span class="field-name">Please enter the Project Number</span>
            <strong class="required">Required</strong>
            @If Model.listError.Count > 0 Then
                @<br/>@<span class="alert-danger alert">Error 1: This is error text that will not wrap as a class label label-danger class.</span>
            End If
        </label>
        <div class="col-md-7">
            <input class="form-control" id="ProjectNumber" name="ProjectNumber" type="text">
        </div>
    </div>
```
**Method 2 source:**
```
 @<div class="form-group">
        <label for="ProjectNumber" class="col-md-5 control-label required">
            <span class="field-name">Please enter the Project Number</span>
            <strong class="required">Required</strong>
            @If Model.listError.Count > 0 Then
                @<br/>@<span class="label-danger label">Error 1: This is error text that will not wrap as a class label label-danger class.</span>
            End If
        </label>
        <div class="col-md-7">
            <input class="form-control" id="ProjectNumber" name="ProjectNumber" type="text">
        </div>
    </div>
```
Could you help us get error text to wrap while displaying inside a label? The attached screen shots, 1 and 2 represent the display for each of these options respectively.

![1 alert alert-danger image](https://cloud.githubusercontent.com/assets/22453895/18845509/57d1ff86-83f8-11e6-954e-7c81f9eff4f0.PNG)
![2 label label-danger image](https://cloud.githubusercontent.com/assets/22453895/18845512/598c8792-83f8-11e6-8d9d-3fc11400eab3.PNG)

**Comment by cybersubtype** [comment] 2016-09-26 18:20
Can you provide a some html of the form your trying to setup? Also view https://guides.github.com/features/mastering-markdown/ for more information on adding html block codes.

**Comment by cybersubtype** [comment] 2016-09-26 18:59
Here what I came up with. Maybe the WET group well fix this in future. But their is issues even with jQuery Validation when trying to display inline.

HTML:
```html
<form action="#" method="post" novalidate="novalidate" >
<div class="form-group col-md-12">
<label for="ProjectNumber" class="col-md-5 control-label required">
 <span class="field-name">Please enter the Project Number</span>
<strong class="required">(Required)</strong>
<span class="alert-danger alert inline-error"><span class="prefix">Error&nbsp;1: </span> This is error text that will not wrap as a class label label-danger class.</span>
</label>
<input class="form-control" id="ProjectNumber" name="ProjectNumber" type="text">
 </div>
<div class="form-group col-md-12">
<label for="ProjectNumber" class="col-md-5 control-label required">
<span class="field-name">Please enter the Project Number</span>
<strong class="required">(Required)</strong>
<span class="label label-danger inline-error"><span class="prefix">Error&nbsp;1: </span> This is error text that will not wrap as a class label label-danger class.</span>
</label>
<input class="form-control" id="ProjectNumber" name="ProjectNumber" type="text">
 </div>
<div class="form-group col-md-12">
<button class="btn btn-md btn-primary" type="submit" role="button" >Submit</button>
<button class="btn btn-md btn-default" type="reset" role="button">Clear All</button>
</div>
</form>
```
CSS:
```css
.inline-error {
	display: inline-block;
	padding: .2em .6em .3em;
	white-space: nowrap;
	margin: 18px auto;
	font-size: 90%;
}
```
Example:
![form](https://cloud.githubusercontent.com/assets/22446865/18847854/23e327ea-8402-11e6-9de8-60efa33b599f.png)

**Comment by RobJohnston** [comment] 2016-09-26 19:00
This is something that I"ve only though about, but haven't done.  Why not back up a bit and keep the regular razor syntax:
```
<div class="form-group">
    @Html.LabelFor(model => model.ProjectNumber, htmlAttributes: new { @class = "control-label col-md-5 required" })
    <div class="col-md-7">
        @Html.EditorFor(model => model.ProjectNumber, new { htmlAttributes = new { @class = "form-control" } })
    </div>
</div>
```
And then create an HTML helper, like done here:  http://stackoverflow.com/questions/5196290/how-can-i-override-the-html-labelfor-template

In that question, the user also wanted to add a `<span>` within the `<label>` tag.

**Comment by CubicleKid** [comment] 2016-09-27 13:03
Cyber, that's the issue. Ultimately the label class brings a `white-space:nowrap;` element into my error message. Your custom CSS adds that no-wrap. I was hoping this issue would be corrected by someone developing WET. My overarching problem is that our team is trying to proceed without any custom CSS except where absolutely mandatory and it appears this might be a case such as that.

Rob - your answer would work as well but we are also directed to not use `LabelFor` and other For elements in an effort to have better control over how Accessibility and "custom" functionality is displayed in as far as staying within the lines of Bootstrap and WET. 

Is there a way to bring this to the attention of the developers of WET? I was hoping this post would do that but I'm new to GitHub as you can tell.

**Comment by RobJohnston** [comment] 2016-09-27 13:18
This could likely use some polish, but this is what I came up with.  You would call it thusly:

```html
@Html.LabelFor(model => model.ProjectNumber, 
htmlAttributes: new { @class = "control-label col-md-5" }, 
requiredText: "required")
```
or for French:
```html
@Html.LabelFor(model => model.ProjectNumber, 
htmlAttributes: new { @class = "control-label col-md-5" }, 
requiredText: "obligatoire")
```

I know you're using VB.Net, but the following is in C#.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.WebPages;

namespace System.Web.Mvc.Html
{
    public static class LabelExtensions
    {
        public static MvcHtmlString LabelFor<TModel, TValue>(this HtmlHelper<TModel> html, Expression<Func<TModel, TValue>> expression, object htmlAttributes, string requiredText)
        {
            return LabelFor(html, expression, new RouteValueDictionary(htmlAttributes), requiredText);
        }

        public static MvcHtmlString LabelFor<TModel, TProperty>(this HtmlHelper<TModel> htmlHelper, Expression<Func<TModel, TProperty>> expression, IDictionary<string, object> htmlAttributes, string requiredText)
        {
            ModelMetadata metadata = ModelMetadata.FromLambdaExpression(expression, htmlHelper.ViewData);
            string htmlFieldName = ExpressionHelper.GetExpressionText(expression);
            string labelText = metadata.DisplayName ?? metadata.PropertyName ?? htmlFieldName.Split('.').Last();
            bool required = metadata.IsRequired;

            if (String.IsNullOrEmpty(labelText))
                return MvcHtmlString.Empty;
            
            TagBuilder tag = new TagBuilder("label");
            tag.MergeAttributes(htmlAttributes);
            tag.Attributes["for"] = TagBuilder.CreateSanitizedId(htmlHelper.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName(htmlFieldName));

            TagBuilder span = new TagBuilder("span");
            span.AddCssClass("field-name");

            span.SetInnerText(labelText);

            if (required)
            {
                TagBuilder strong = new TagBuilder("strong");
                strong.AddCssClass("required");
                strong.SetInnerText(string.Format("({0})", requiredText));

                tag.AddCssClass("required");
                tag.InnerHtml = string.Format("{0} {1}", span.ToString(TagRenderMode.Normal), strong.ToString(TagRenderMode.Normal));
            }
            else
            {
                tag.InnerHtml = span.ToString(TagRenderMode.Normal);
            }

            return MvcHtmlString.Create(tag.ToString(TagRenderMode.Normal));
        }
    }
}
```

**Comment by cybersubtype** [comment] 2016-09-27 13:31
@shawnthompson or @hsrudnicki Do you guys have any thoughts? This is an issue even with other languages. Maybe have in the WET core css have a class similar to mine but use it like this `.form-horizontal .label-danger, .form-horizontal .alert-danger` so it auto implements this styling in that event?

**Comment by RobJohnston** [comment] 2016-09-27 14:28
Just noticed that the textbox also needs the "required" attribute as well, so try this in conjunction with the `LabelExtensions` class:

```html
<div class="form-group">
    @Html.LabelFor(model => model.ProjectNumber, htmlAttributes: new { @class = "control-label col-md-5",  requiredText: "required" })
    <div class="col-md-7">
        @Html.EditorFor(model => model.ProjectNumber, new { htmlAttributes = new { @class = "form-control", required = "required" } })
    </div>
</div>
```

And I forgot to mention that this is expecting the model to have data annotations to show what is required.  Something like this:

```c#
[Required]
public string ProjectNumber;
```

Or, even this:

```c#
[Required(ErrorMessage = "The Project Number is required.")]
[StringLength(10)]
[Display(Name = "Project Number")]
public string ProjectNumber;
```

**Comment by RobJohnston** [comment] 2016-09-27 14:46
@CubicleKid : That gets you to the WET way of writing horizontal forms with razor syntax.  From here, is this a duplicate of https://github.com/wet-boew/wet-boew/issues/7284?

**Comment by hsrudnicki** [comment] 2016-09-27 14:53
I don't you confuse, you may check also the following issues: #6834,  as well #6966 to get a full/whole picture;
[additionally, it's up to you
- use jquery about wrapping text with label on http://stackoverflow.com/questions/31007757/wrap-text-with-label
- use C# http://stackoverflow.com/questions/4460201/how-to-set-an-event-function-via-a-style
- use JS HTML DOM to change CSS http://www.w3schools.com/js/js_htmldom_css.asp
]

**Comment by hsrudnicki** [comment] 2016-09-27 18:46
and as well into consideration #7074

**Comment by biljanap** [comment] 2016-09-27 18:54
I had this issue with an older version of WET as referenced by @RobJohnston . It looks like it has been fixed for v.4.0.21 at least (not sure about version before).
Just use the code from WET example for horizontal form http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#forms-horizontal and add necessary elements to make fields required.

``` html
<!-- Solution using WET example for horizontal form - no error message -->
<div class="form-group">
  <label for="ProjectNumber" class="col-md-5 control-label required"><span class="field-name">Please enter the Project Number</span> <strong class="required">(required)</strong></label>
  <div class="col-md-7">
    <input class="form-control" id="ProjectNumber" name="ProjectNumber" required="required" type="text">
  </div>
</div>

<!-- Solution using WET example for horizontal form - with error message -->
<div class="form-group">
  <label for="ProjectNumber" class="col-md-5 control-label required"><span class="field-name">Please enter the Project Number</span> <strong class="required">(required)</strong> <strong class="error" id="errorProjectNumber"><span class="label label-danger"><span class="prefix">Error&nbsp;1: </span>This is error text that will not wrap as a class label label-danger class.</span></strong></label>
  <div class="col-md-7">
    <input class="form-control" id="ProjectNumber" name="ProjectNumber" required="required" type="text">
  </div>
</div>
````

This is the look I get with v.4.0.21 using example above:

![error-horizontal-form](https://cloud.githubusercontent.com/assets/2146304/18887383/d99a1c32-84c1-11e6-95d0-a33cedc6860a.jpg)

Make sure you are using all elements as in example.

**Comment by CubicleKid** [comment] 2016-09-27 19:19
Rob. That's fantastic.

The problem showing on [7284](https://github.com/wet-boew/wet-boew/issues/7284) seems to look like exactly what I'm talking about and it's been open since December 8th. The code you demonstrated for creating a custom LabelFor is good to keep handy too.

Hsrudnicki, I'm not confused...those are good references. Thank you for adding them for my consideration. Your examples aren't the first solution I'd apply (Aria and JS) due to the code environment I'm working within but they are good to be aware of when considering our options.

I will keep an eye on 7284 as when that's resolved which now seems to be a clear duplicate of this reported issue.

**Comment by biljanap** [comment] 2016-09-27 19:29
@CubicleKid I opened #7284 but I am not having the issues anymore. As I explained, it works if you use the code as in WET example for horizontal form.

**Comment by CubicleKid** [comment] 2016-09-27 19:31
@biljanap Understood. I haven't had time to comb through your snippet. On first attempt, my result did not appear like yours did so I'm digging a bit to get it working.

**Comment by biljanap** [comment] 2016-09-27 20:31
@CubicleKid I can see that you are missing something in your code that I think it would fix it all.
You need to wrap your `<span class="label label-danger">`in a `<strong  class="error"`> tag.

````html
<div class="form-group">
  <label for="ProjectNumber2" class="col-md-5 control-label required"> <span class="field-name">Example 3: The best solution. Add Break to error text and modify style to remove no-wrap. Please enter the Project Number</span> 
  	<strong class="required">(Required)</strong> 
    <strong class="error" id="errorProjectNumber">
         <span class="label label-danger"> 
              <span class="prefix">Error&nbsp;1: </span> This is error text that will not wrap as a modified class label label-danger class.
         </span> 
    </strong>
  </label>
  <div class="col-md-7">
    <input class="form-control" id="ProjectNumber2" name="ProjectNumber" type="text">
  </div>
</div>
````

That seems to be the only difference between your code and mine. If you are able to add that code, you would not need  `<br>` and `style="white-space:normal;"`

If you add `<strong class="error">` to your code, this css gets applied from theme.min.css:

```html
.wb-frm label strong.error .label, .wb-frm legend .error .label, .wb-frmvld label strong.error .label, .wb-frmvld legend .error .label {
    font-size: 100%;
    white-space: normal;
}
````
Notice `white-space: normal;` in css code.

**Comment by cybersubtype** [comment] 2016-09-28 12:17
I'm using Government of Canada Intranet Theme with `theme.min.css` (v4.0.22 - 2016-08-11) and this does not fix the issue of the horizontal forms.

**Comment by RobJohnston** [comment] 2016-09-28 13:19
@CubicleKid :  I didn't notice you message until last night where you said that you are 

> directed to not use LabelFor and other For elements in an effort to have better control over how Accessibility and "custom" functionality is displayed in as far as staying within the lines of Bootstrap and WET. 

I'm interesting in knowing what the concern is?  The `LabelExtensions` class above should output HTML as in the [WET documentation for a horizontal form] (http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#forms-horizontal), with minimal change to the MVC code generated via scaffolding (just the addition of the "required" text).

**Comment by CubicleKid** [comment] 2016-09-28 14:39
@RobJohnston : The concern is superficial. That approach would work. I know this after having tried to explain it five times now in this post ;) On the other hand, I'm in no position to tell the team how to approach our months-long conversion from a non-Wet hybrid MVC .net system. There is the issue that if I fix a common helper, say LabelFor, to be right for the page I'm on, it'll break many other pages being worked on by many other people who may not be ready to experience that break. It's my gut feeling in our team environment that the best approach to becoming Wet Compliant begins with getting each page working independently. 

Ultimately, I have seen great code and am grateful for all these thought-provoking suggestions but I haven't seen a 'perfect fix' offered on this page that truly fixes my problem - there are small issues with every suggestion with the exception of cybersubtype's note that there's a new version of theme.min.css which I have yet to test. The Perfect fix aside from that possibility is an inline snippet on my Label's inner span of `white-space:normal;` - width adjustment works perfectly, right alignment works, and all borders are obeyed. Problem is we're avoiding inline CSS like the plague.

I have a great idea of my solution now - either a fix being implemented in Wet, we have to create a custom css file regardless of our rules, or we have to change how we display errors. I couldn't have come to this conclusion without the help of everyone posting on this page.

**Comment by RobJohnston** [comment] 2016-09-28 15:11
Interesting... although the new parameter of "`requiredText`" would guarantee that the method in the `LabelExtensions `class is being used.

I wonder if it would ease the concerns of your team if you were able to write  `@Html.WetLabelFor` insead of  `@Html.LabelFor`.  I think it would be an easy change from the code above (change of namespace and the method name).

**Comment by biljanap** [comment] 2016-09-29 17:20
@CubicleKid I know you must be tired of all the replies and suggestions :o) but it is really puzzling why this is working for me but not for you. Just out of curiosity, are you wrapping your form in `<div class="wb-frm">` ? If I remove this class, it's not working for me either. I get similar results as you do.

**Comment by CubicleKid** [comment] 2016-10-04 19:46
@biljanap I've been out sick, long weekend and busy yesterday. I'm back!  About your question, you are "right". I'm not using tha tdiv class for a form, I'm using one we are mandated to use `<form class="form-horizontal" action="#" method="post" novalidate="novalidate" >`
This changes the reaction of how things are aligned - our forms are all right aligned, not left. Fun eh?! :)

**Comment by RobJohnston** [comment] 2016-10-04 19:58
@CubicleKid :  It's a `div ` tag that wraps the `form` tag, not a class of the form.  

It's noted right at the top of the [Form documentation] (http://wet-boew.github.io/wet-boew/docs/ref/formvalid/formvalid-en.html) page... and it should actually be `<div class="wb-frmvld">`.

**Comment by biljanap** [comment] 2016-10-05 18:34
@RobJohnston You are right. Thanks. I did not even realize that I missed "vld" from "wb-frmvld" :o)

**Comment by LaurentGoderre** [comment] 2016-10-18 13:02
Can we close this?

**Comment by cybersubtype** [comment] 2016-10-18 14:11
@LaurentGoderre I say yes as the issue is fixed in latest version.

**Closed** 2016-10-24 21:56 UTC
