### ISSUE TITLE
Datalist-polyfill (auto-complete)-Android-Samsung Galaxy S4 mini

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5106] opened 2014-04-02 16:14 UTC
The auto-complete doesn't work in mobile

**Comment by hsrudnicki** [comment] 2015-06-09 14:42
@nrustand92 @pjackson28 : Are you ready to close this issue ?

**Comment by pjackson28** [comment] 2015-06-09 19:47
This same browser/phone combo has numerous issues tied to it. One thing to keep in mind that it likely falls outside of WET's support window so should we even keep this and the other issues open if we can't reproduce on similar devices and the browser in question will likely be technically outside of the support window?

**Comment by hsrudnicki** [comment] 2015-06-09 19:57
We can ask @LaurentGoderre in making the final decision (?)

**Comment by pjackson28** [comment] 2015-06-09 19:58
I just checked and the default browser for the Samsung S4 Mini is out of the support window. It ran Android 4.2.2 (API level 17) which ran WebKit 534.30. The WebKit version has been at least 537.36 since Android 4.4 and Android 5.1 (API level 22) is now available.

So closing because we can't reproduce the issue and because the browser in question is outside of the support window.

**Closed by pjackson28** 2015-06-09 19:58 UTC
Labels: Browser: Android, Polyfill: Datalist (Auto-complete)
