### ISSUE TITLE
Template on Working Examples Pages not Loading

### ISSUE THREAD

**Issue by naptash** [wet-boew/wet-boew#6868] opened 2015-06-16 20:53 UTC
http://wet-boew.github.io/wet-boew/demos/index-en.html

Subject kinda explains it all.

**Comment by RobJohnston** [comment] 2015-06-17 12:00
Duplicate of #6865.

**Closed** 2015-06-17 16:31 UTC
Labels: Close: Duplicate

**Comment by LaurentGoderre** [comment] 2015-06-17 18:12
It was fixed
