### ISSUE TITLE
Form validation: Issue with file (required) field error message

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew#7554] opened 2016-05-17 19:31 UTC
Hi,

I noticed some weird behaviors with the <input type=file ...> element on the Form validation example page. (http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html)

The "File (required)" field displays error message (This field is required) if you don't upload a file. The error message stays there after you uploaded a file. The issue is if you try to click on a checkbox or radio button or submit button (before clicking anywhere on the page) right after uploading the file using the mouse  they don't get clicked. It appears they get focused as you see the dotted line around the element. You have to click on those elements twice to select or activate. Tested in Chrome v50, IE 11, Firefox 46

Is this an expected behaviour? 

See attached screenshot below.

![form7](https://cloud.githubusercontent.com/assets/12256067/15336529/fb8027c8-1c44-11e6-9b0b-cc4ee306ebd6.gif)

Thanks

**Comment by sarasuri** [comment] 2016-05-17 19:35
![form4](https://cloud.githubusercontent.com/assets/12256067/15336480/cda4384e-1c44-11e6-95ff-28b04df4feea.gif)
![form6](https://cloud.githubusercontent.com/assets/12256067/15336479/cd9fe730-1c44-11e6-85de-e74e86d636aa.gif)

**Comment by nschonni** [comment] 2016-05-18 01:52
Looks like a dupe of #6834

**Comment by sarasuri** [comment] 2016-05-26 14:56
Hi,
I understand the issue exists in the jQuery plugin.

Can anything be done to fix this issue in WET?
Thanks

**Comment by hsrudnicki** [comment] 2016-08-17 15:00
Please update again the status of this issue, whether this can be closed as resolved or otherwise? Thank you

**Comment by sarasuri** [comment] 2016-08-18 19:01
Hi,
This issue has not been resolved yet so please keep open.

**Comment by hsrudnicki** [comment] 2016-08-18 20:25
So, you decided to close this.

**Comment by sarasuri** [comment] 2016-08-18 20:47
Sorry,  I didn't realize that I clicked on "Comment and close". I am reopening it as it is not resolved yet.

**Comment by kodecount** [comment] 2016-11-10 15:17
@sarasuri @nschonni @masterbee I believe issue #6834 and #7554 can be closed. These are dependent on jQuery validation group. I discussed the issue with them. Currently their is no way to cleanly fix this. If you want this issue fixed you'll have to use a around about method found here: https://github.com/jzaefferer/jquery-validation/issues/997 (this is from 2014).

**Comment by LaurentGoderre** [comment] 2016-11-14 13:58
Duplicate of #7554

**Closed by LaurentGoderre** 2016-11-14 13:58 UTC
Labels: Plugin: Form Validation (jQuery Validation)
