### ISSUE TITLE
Glyphicons not displaying in IE8

### ISSUE THREAD

**Issue by TinoTran-Work** [wet-boew/wet-boew#7131] opened 2015-10-02 17:08 UTC
Good morning,

We are are having some issues with glyphicons displaying in IE8.  They do not show up at all in IE8 but they work perfectly find in all other browsers.

We are using version 16 of the WET Framework.

Thank you for your time.  Have a great day!

**Comment by LaurentGoderre** [comment] 2015-10-02 17:34
Duplicate of #7041

**Closed** 2015-10-02 17:35 UTC
Labels: Close: Duplicate
