### ISSUE TITLE
Possible conflict with Tab components and Twitter

### ISSUE THREAD

**Issue by keithcolbourne** [wet-boew/wet-boew#7034] opened 2015-08-18 15:42 UTC
We have recently integrated WET4 (4.0.9) within our CMS. One of our clients is experiencing an issue with the Twitter timeline when combined with Tabbed Interface Carousel (and possibly Tabbed Interface).

Please see: http://www.army-armee.forces.gc.ca/en/index.page

Often (but curiously, not every time) the twitter feed will not load on this page (and test pages with these tabbed components). Debugging shows that a DOM exception (SYNTAX_ERR: DOM Exception 12) occurs in wet-boew.min.js at line 11, character 21530 -- which is this snippet of code: 

```javascript
(j=document.querySelector(c.parent),"tablist"!==j.getAttribute("role"))
```

We are getting this error about 90% of the time on this page. 

Can you please take a look? If it works, keep re-loading, you should eventually see this error.

This has been reported by our clients, so it's not just us developers seeing it.
Thank You
Keith Colbourne

**Comment by pjackson28** [comment] 2015-08-18 16:00
Can you reproduce with the latest version (v4.0.16)? There were issues with the tabbed interface in v4.0.9 that have since been fixed.

**Comment by keithcolbourne** [comment] 2015-08-19 17:56
Thanks. I did a test with the upgraded WET (4.0.16) version and twitter won't display. I don't have a url for you to look at with that version, I tried on one of our development servers. All that shows up is an invisible link to the twitter account that I provided. 

Is it possible you guys can take a look at the url I provided and see if you can find anything that might be WET related? Thank You

**Comment by andre-gh** [comment] 2015-08-21 14:53
I have a lead on the issue, will update later today

**Comment by keithcolbourne** [comment] 2015-08-21 14:57
Thanks. I played with just replacing the wet-boew.min.js and am getting better results but it's too early to tell if it will consistently display. I'm also not a fan of just swapping out just one file (as upgrading WET to 4.0.16 would be out of scope for us).

Look forward to your update, thank you

**Comment by andre-gh** [comment] 2015-08-21 15:25
This issue is due to an automatic ID generation issue resolved in 4.0.10.

If an update is not possible giving your twitter widget div an ID will resolve the issue.  However, this issue may cause issues with other widgets and it is recommend that you update to at-least 4.0.10 if not the latest version.

**Comment by andre-gh** [comment] 2015-08-21 15:27
Actually, I jumped the gun on that, I got lucky refreshing 10 times without seeing it.  The issue is not the ID on the twitter widget...please disregard my solution for the time being.

**Comment by andre-gh** [comment] 2015-08-21 15:39
I have verified that this is an issue with automatic ID generation resolved in 4.0.10.  In this case, your wb-tabs widgets are trying to be selected however IDs are being auto-generated for them which sometimes begin with a number (which is invalid).

The patch which fixed this issue are a series of patches #7a13f5a followed by #87996bc and then by #40cab9f with changes to the ID generation to be faster and to guarantee that the ID generated begins with a letter.

The workaround would be to place an ID on every WET widget which might get selected within the plugin internals, which sounds non-ideal and easy to miss and therefor I am recommending you upgrade WET to the latest version, at-least 4.0.10 will resolve this specific issue.

**Comment by keithcolbourne** [comment] 2015-08-21 15:43
Ok, we will have to figure out what to do. We just released our upgraded WET 4.0.9 version on August 10. A full upgrade won't be feasible for us right away, this is CMS integration.

Thank you for your efforts.

**Comment by hsrudnicki** [comment] 2015-09-25 18:51
and now is time to update this issue's status whether this issue can be closed or otherwise?

**Comment by keithcolbourne** [comment] 2015-09-25 18:58
Upgrading our version of WET fixed this issue. Yes, this can be closed

**Closed** 2015-09-28 17:28 UTC
Labels: Plugin: Tabbed Interface/Carousel
