### ISSUE TITLE
Share Widget-Android-Samsung Galaxy S4 mini-landscape & portrait views

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5116] opened 2014-04-02 18:41 UTC
The background of the widget's header shifts to the left?
![screenshot_2014-04-02-14-37-09](https://cloud.githubusercontent.com/assets/5949078/2595070/51277d10-ba96-11e3-9a69-1c087ccb2e8c.png)

**Comment by hsrudnicki** [comment] 2015-06-09 14:54
Can be this issue closed ?

**Comment by pjackson28** [comment] 2015-06-09 19:40
Can anyone reproduce this issue? I haven't had any success on anything I tried. If nobody can reproduce the issue then we should close as can't reproduce.

**Comment by pjackson28** [comment] 2015-06-09 20:01
I just checked and the default browser for the Samsung S4 Mini is out of the support window. It ran Android 4.2.2 (API level 17) which ran WebKit 534.30. The WebKit version has been at least 537.36 since Android 4.4 and Android 5.1 (API level 22) is now available.

So closing because we can't reproduce the issue and because the browser in question is outside of the support window.

**Closed by pjackson28** 2015-06-09 20:01 UTC
Labels: Browser: Android, Bug Report: Minor, Plugin: Share widget
