### ISSUE TITLE
Overlay: 

### ISSUE THREAD

**Issue by IanYangCa** [wet-boew/wet-boew#9175] opened 2021-09-17 14:34 UTC
I use gcweb/v4_0_39/cdts/compiled/wet-en.js, <section id="mid-screen" class="wb-overlay modal-content overlay-def wb-popup-mid overlay-bg" aria-hidden="true" style="height:260px;width:300px;">

The "Close" button always append to my custom buttons. How can I disable it append to my buttons?[](url)

<section id="mid-screen" class="wb-overlay modal-content overlay-def wb-popup-mid overlay-bg" aria-hidden="true" style="height:260px;width:300px;">
<header class="modal-header">
<h2 class="modal-title">{{deleteComponentTitle}}</h2>
</header>
<div class="modal-body">
	<p>{{deleteComponentMsg}}</p>
</div>
<div class="modal-footer" style="border: 0px;">
	<button type="button" class="btn btn-sm btn-primary pull-left overlay-close popup-modal-dismiss" title="No" style="background:#335075">No
	<span class="wb-inv">No</span></button>&nbsp;&nbsp;
	<button type="button" class="btn btn-sm btn-primary pull-left overlay-close popup-modal-dismiss" title="Yes" data-ng-click="confirmDelComponent()" style="background:#335075">Yes
	<span class="wb-inv">Yes</span></button>
</div>
</section>

**Comment by thekodester** [comment] 2021-09-17 23:38
Duplicate of #9173

**Closed** 2021-09-22 17:41 UTC
Labels: Close: Duplicate
