### ISSUE TITLE
Data Inview-bottom bar-Android-Samsung Galaxy S4 mini-portrait & landscape views

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5103] opened 2014-04-02 15:59 UTC
Top border not straight

![screenshot_2014-04-02-11-54-54](https://cloud.githubusercontent.com/assets/5949078/2593370/b26f9a1a-ba7f-11e3-8323-e9ddcce20e5c.png)

**Comment by hsrudnicki** [comment] 2015-06-09 14:36
Are you ready to close this issue ?

**Comment by pjackson28** [comment] 2015-06-09 20:02
I just checked and the default browser for the Samsung S4 Mini is out of the support window. It ran Android 4.2.2 (API level 17) which ran WebKit 534.30. The WebKit version has been at least 537.36 since Android 4.4 and Android 5.1 (API level 22) is now available.

So closing because we can't reproduce the issue and because the browser in question is outside of the support window.

**Closed by pjackson28** 2015-06-09 20:02 UTC
Labels: Bug Report: Minor, Plugin: Data Inview
