### ISSUE TITLE
Session Timeout Tool Error

### ISSUE THREAD

**Issue by measterbrook** [wet-boew/wet-boew#8499] opened 2018-10-18 22:05 UTC
I am getting this error in the session-timeout.js file:
0x800a1391 - JavaScript runtime error: 'wb' is undefined

I am using this in my webpage:
`<span class="wb-sessto" data-wb-sessto='{"inactivity": 30000, "logouturl": "../index-en.html"}'></span>`

I have loaded the script by inserting this header in the webpage:
`<script src="~/Scripts/session-timeout.js"></script>`

The error occurs when the page opens.

**Comment by RobJohnston** [comment] 2018-10-18 22:31
I think I know your problem.  You should load the `wet-boew.min.js` script, not `session-timeout.js`.  It's all or nothing... you can't pick-and-choose the functionality you want.

Here's a working example:  https://wet-boew.github.io/wet-boew/demos/session-timeout/session-timeout-en.html

**Comment by RobJohnston** [comment] 2018-10-18 22:34
Duplicate of https://github.com/wet-boew/wet-boew/issues/8497.

**Closed** 2018-10-19 19:33 UTC
Labels: Close: Duplicate, Feature: Session timeout, Query: Question, State: Resolved
