### ISSUE TITLE
WET 4.0.18 packaging issue: offline jquery packages

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#7201] opened 2015-11-19 16:42 UTC
Hi, my colleagues have come across the following issue and asked me to raise it on github:

The offline jquery packages now live under directories called /wet-boew/js/jquery/1.11.1 and /wet-boew/js/2.1.14/.  Unfortunately, the WET distribution has reversed the actual files, so the version 1.11.1 files are in the 2.1.14 directory and vice-versa.

Please fix in 4.0.19.

Thank you, Rob.

**Comment by LaurentGoderre** [comment] 2015-11-19 16:49
Duplicate of #7199 and Fixed by #7200

**Closed by LaurentGoderre** 2015-11-19 16:49 UTC
