### ISSUE TITLE
GoC Web Usability Theme

### ISSUE THREAD

**Issue by tascinc** [wet-boew/wet-boew#6578] opened 2015-02-27 14:18 UTC
Menus are appearing shifted to the right significantly... why is that?

Also, form labels that wrap are automatically right-justified. Very odd behavior...

**Comment by LaurentGoderre** [comment] 2015-02-27 14:44
The first issue is a duplicate of https://github.com/wet-boew/theme-gcwu-fegc/issues/189

For the second issue can you please add a screenshot. We have to determine if it's caused by the theme or WET core

**Comment by tascinc** [comment] 2015-02-27 16:24
The odd right-justification of labels is related to the css class
'form-control' - left-justified if the label does not wrap (narrower than
view port) and right-justified if wider than the view port and forced to
wrap.

Romoving the class fixed that one.

**Comment by LaurentGoderre** [comment] 2015-02-27 18:29
What version are you using?

**Comment by tascinc** [comment] 2015-02-27 18:37
4.10. I see that 4.11 was released last week. I haven't applied it yet to
my test site.

**Comment by LaurentGoderre** [comment] 2015-02-27 19:06
This issue sounds familiar....

**Comment by hsrudnicki** [comment] 2015-06-15 18:51
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment] 2015-06-17 20:37
Duplicate of https://github.com/wet-boew/theme-gcwu-fegc/issues/189

**Closed by LaurentGoderre** 2015-06-17 20:37 UTC
