### ISSUE TITLE
Overlay Left, Right, & Full Screen-Android-Samsung Galaxy S4 mini

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5114] opened 2014-04-02 18:15 UTC
Background of the overlay headers not properly aligned

![screenshot_2014-04-02-14-05-32](https://cloud.githubusercontent.com/assets/5949078/2594811/ad1a830a-ba92-11e3-818f-eee00e0ca542.png)

![screenshot_2014-04-02-14-06-23](https://cloud.githubusercontent.com/assets/5949078/2594812/ad1e2064-ba92-11e3-977b-3e928be42944.png)

![screenshot_2014-04-02-14-06-15](https://cloud.githubusercontent.com/assets/5949078/2594813/ad20dee4-ba92-11e3-9849-9d4d9f3b5e6e.png)

**Comment by hsrudnicki** [comment] 2015-06-09 14:52
@nrustand92 @pjackson28 : Are you ready to close this issue ?

**Comment by pjackson28** [comment] 2015-06-09 19:42
This one mobile browser on a specific phone has had display issues across multiple browsers where the issue could not be reproduced on other Android phones using the Android browser. Could this be a case where the issue is something with the browser that we can't fix without breaking support for everything else? I haven't been able to reproduce this issue anywhere else.

**Comment by pjackson28** [comment] 2015-06-09 20:01
I just checked and the default browser for the Samsung S4 Mini is out of the support window. It ran Android 4.2.2 (API level 17) which ran WebKit 534.30. The WebKit version has been at least 537.36 since Android 4.4 and Android 5.1 (API level 22) is now available.

So closing because we can't reproduce the issue and because the browser in question is outside of the support window.

**Closed by pjackson28** 2015-06-09 20:01 UTC
Labels: Browser: Android, Plugin: Overlay
