### ISSUE TITLE
Footnotes in multi-page documents

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/wet-boew#7019] opened 2015-08-07 13:05 UTC
Seems like the footnotes code in WET4 doesn't work properly in multi-page documents. When I click on the footnote, there is no action. However, if I select "Open in a new tab", it works fine.

**Comment by pjackson28** [comment] 2015-08-07 14:30
Do you have an example you can point to? Is the footnote on the same page as the link to the footnote? Note that the footnotes plugin is only intended to work where the link to the footnote and the footnote itself are on the same page.

**Comment by EricLavoie88** [comment] 2015-08-07 14:43
They are not on the same page. In our multipage documents, we have all the footnotes on the last page. Is there a possibility that this plugin can be adapted for multipage documents or is our only option to not use multipage documents? Or have the footnotes on each individual page.

**Comment by pjackson28** [comment] 2015-08-07 14:46
@EricDunsworth Please respond regarding the enhancement request.

**Comment by EricDunsworth** [comment] 2015-08-07 20:31
The footnotes plugin isn't really meant to be used as catch-all for things that are "kind of" similar to footnotes, such as endnotes (this scenario) and table notes. Having said that, I don't mind fixing support for non-ID return links.

@EricLavoie88 If you're not dead set on using endnotes, I'd recommend placing a footnotes section at the end of each individual page, containing only the current page's footnotes. So for example, page 1 might have a footnotes section covering footnotes 1-7, page 2 having one for footnotes 8-14, etc... That's in line with how the footnotes plugin was designed to be used.

@pjackson28 I'll send over a PR to make footnote return links work with non-ID destinations.

As for reference links, I'll skip those. These linking issues only occur if the footnotes plugin is instantiated on the current page, so in practice only the endnotes page should be affected (since the pages containing the endnote references should only be leveraging some of the footnotes plugin's CSS classes for styling - not the plugin itself).

Lastly, I should note that multi-referenced footnote links won't work properly in an endnotes scenario. To make it work, some substantial changes would need to be made to the plugin and how its implemented on pages that link to an endnotes page. IMO it's not worth the effort to implement for such an minor and unusual use-case.

**Comment by EricLavoie88** [comment] 2015-08-11 11:26
Thanks Eric, I will discuss the option with my team.

**Comment by EricDunsworth** [comment] 2015-08-11 20:38
@pjackson28 Regarding the plugin adjustment - I'm on vacation starting in like 20 mins, so I won't have a chance to implement it until later in August :(. Also running into proxy-related build problems atm.

**Comment by hsrudnicki** [comment] 2015-09-25 17:33
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by EricLavoie88** [comment] 2015-11-02 15:50
@EricDunsworth Have you had the time to look into this request?

**Comment by EricDunsworth** [comment] 2015-11-10 14:33
@EricLavoie88 Sorry, haven't had a chance yet :(.

In late August my install of WET's build system was totally busted. Got it working again at some point afterwards, but I've been pretty swamped since. I still intend to fix this issue once I get a chance.

**Comment by EricLavoie88** [comment] 2015-11-10 15:51
Sounds good!

**Comment by hsrudnicki** [comment] 2015-12-18 18:30
@EricDunsworth and others: Based on the above, did you have a time to look into this request?
Either way, please keep this issue's status updated whether this issue can be closed or otherwise? Thank you

**Comment by EricLavoie88** [comment] 2016-01-21 19:19
Any updates on this request? Thanks!

**Comment by EricDunsworth** [comment] 2016-06-10 18:54
@EricLavoie88 Finally got around to addressing this :)! Sorry for the extreme wait :(.

I presume PR #7578 will be merged-in by the time WET 4.0.22 gets released. Once that happens, you should be good to go if you update to that version.

Please note that PR only adds the ability to link to pages. It doesn't add support for multi-referenced footnotes when linking to separate pages. Adding multi-referenced support for separate pages might be possible with something like localStorage, but IMO it's not worth the effort since it's a really uncommon scenario.

**Closed** 2016-06-14 20:46 UTC
Labels: Plugin: Footnotes, Suggestion: Enhancement
