### ISSUE TITLE
logo.svg missing?

### ISSUE THREAD

**Issue by regio760** [wet-boew/wet-boew#7499] opened 2016-04-12 20:21 UTC
In the intranet theme, the splashpage code includes a reference to a log.svg file that seems to not be in the assets folder that it refers to - is that missing or is that deliberate?

**Comment by LaurentGoderre** [comment] 2016-04-13 12:50
Please open an issue with that theme. There is no logo.sbg and the issue is that it's using the default WET Theme splash page for that one page.

**Comment by MaximMartel** [comment] 2016-04-15 15:35
Can we close this issue @regio760 @LaurentGoderre

**Comment by RobJohnston** [comment] 2016-04-15 15:39
This issue got moved to https://github.com/wet-boew/theme-gc-intranet/issues/156

**Comment by MaximMartel** [comment] 2016-04-15 15:40
ok, then ill close this issue since this is a duplicate.

**Closed by MaximMartel** 2016-04-15 15:40 UTC
Labels: Close: Duplicate
