### ISSUE TITLE
Tabpanel Horizontal scroll bar if form-horizontal used - related to #6439

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#6540] opened 2015-02-18 17:14 UTC
I seem to be having the same issue as in #6439 however adding container-fluid to the form class is not resolving it.  Here is my markup.  The first div and the form declaration are in a master page if that makes any difference.

```html
<div class="container body-content">
        <form id="ctl00" class="container-fluid form-horizontal" method="post" action="TestTabs.aspx">
            
    <div id="wb-auto-1" class="wb-tabs wb-tabs-inited tabs-acc"><ul aria-hidden="false" class="generated" role="tablist" aria-live="off"><li class="active" role="presentation"><a id="Tombstone-lnk" role="tab" tabIndex="0" aria-selected="true" aria-controls="Tombstone" href="#Tombstone">Contact Tombstone Data</a></li></ul>
        
    <div class="tabpanels">
            <details aria-hidden="false" aria-expanded="true" id="Tombstone" class="wb-auto-1-grp open fade in" role="tabpanel" tabIndex="-1" aria-labelledby="Tombstone-lnk" open="open">
                <summary aria-hidden="true" aria-expanded="true" id="wb-auto-2" class="wb-toggle tgl-tab wb-toggle-inited wb-details-inited" role="tab" aria-posinset="1" tabIndex="0" aria-selected="true" aria-setsize="1" data-toggle='{"parent": "#wb-auto-1", "group": ".wb-auto-1-grp"}'>Contact Tombstone Data</summary><div aria-hidden="false" aria-expanded="true" class="tgl-panel" aria-labelledby="wb-auto-2">
                <div class="form-group">
                    <label id="MainContent_FirstNameLabel" class="col-sm-3 control-label required" for="MainContent_FirstNameValue">First Name</label>
                    <div class="col-sm-1">
                        <input id="MainContent_FirstNameValue" class="form-control" name="ctl00$MainContent$FirstNameValue" maxLength="50" type="text" required="required">
                    </div>
                </div>
            </div></details>
        </div></div>

            <hr>
        </form>
    </div>
```

Can anyone see something obvious I have missed?  I am using 4.0.10 production.

Thanks,

Garth

**Comment by GarthMartin** [comment] 2015-02-18 17:16
Sorry my markup did not come out right.  
```<div class="container body-content">
        <form id="ctl00" class="container-fluid form-horizontal" method="post" action="TestTabs.aspx">
    <div id="wb-auto-1" class="wb-tabs wb-tabs-inited tabs-acc"><ul aria-hidden="false" class="generated" role="tablist" aria-live="off"><li class="active" role="presentation"><a id="Tombstone-lnk" role="tab" tabIndex="0" aria-selected="true" aria-controls="Tombstone" href="#Tombstone">Contact Tombstone Data</a></li></ul>
    <div class="tabpanels">
            <details aria-hidden="false" aria-expanded="true" id="Tombstone" class="wb-auto-1-grp open fade in" role="tabpanel" tabIndex="-1" aria-labelledby="Tombstone-lnk" open="open">
                <summary aria-hidden="true" aria-expanded="true" id="wb-auto-2" class="wb-toggle tgl-tab wb-toggle-inited wb-details-inited" role="tab" aria-posinset="1" tabIndex="0" aria-selected="true" aria-setsize="1" data-toggle='{"parent": "#wb-auto-1", "group": ".wb-auto-1-grp"}'>Contact Tombstone Data</summary><div aria-hidden="false" aria-expanded="true" class="tgl-panel" aria-labelledby="wb-auto-2">
                <div class="form-group">
                    <label id="MainContent_FirstNameLabel" class="col-sm-3 control-label required" for="MainContent_FirstNameValue">First Name</label>
                    <div class="col-sm-1">
                        <input id="MainContent_FirstNameValue" class="form-control" name="ctl00$MainContent$FirstNameValue" maxLength="50" type="text" required="required">
                    </div>
                </div>
            </div></details>
        </div></div>

            <hr>
        </form>
    </div>```

**Comment by LaurentGoderre** [comment] 2015-02-18 17:17
@GarthMartin I fixed your markup, you need a new line after the three `

**Comment by RobJohnston** [comment] 2015-02-18 17:36
I've been noticing this too, and I have a note that it appeared between 4.0.7 and 4.0.9.  I think it was the addition of "overflow-x: auto" here:
https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tabs/_base.scss#L211
I'm currently just overriding it with overflow-x:inherit until I get a better solution.

I'm more of a back-end developer, so it's ever-so-slightly possible that I don't know what I'm talking about.

**Comment by LaurentGoderre** [comment] 2015-02-18 18:02
We updated Bootstrap to v3.3.- in WET v4.0.11. It might have fixed that issue

**Comment by GarthMartin** [comment] 2015-02-18 19:13
@RobJohnston Where did you override it?

@LaurentGoderre V4.0.11 does not appear to have resolved the issue.

**Comment by LaurentGoderre** [comment] 2015-02-18 19:14
I would recommend not overriding anything because it would make support harder

**Comment by GarthMartin** [comment] 2015-02-18 19:18
@LaurentGoderre I would tend to agree with you 100%.  The tabbed interface seems to have a number of issues the more I play with it and search issues on here.  I may have to revert back to jQuery tabs.

**Comment by LaurentGoderre** [comment] 2015-02-18 19:32
It would be a shame, we are working hard to resolve those issues and have implementers help us with this is very helpful

**Comment by GarthMartin** [comment] 2015-02-18 19:34
@LaurentGoderre It's not a threat :-)   Just need to get the job done!  I appreciate all your help!

**Comment by RobJohnston** [comment] 2015-02-18 19:37
@GarthMartin I made another CSS file that loads after all others (just for the one application that is affected) as a temp fix until I have time to look further.
The only thing in that file now is this
```css
.wb-tabs [role="tabpanel"] {
    overflow-x: inherit;
}
```

@LaurentGoderre I agree that 4.0.11 does not resolve it, but interestingly I can't reproduce it by just wrapping the tabbed content example in a horizontal form.  Will have time to look deeper into this as the app goes into UAT.  And isn't a custom CSS file an acceptable way of overriding WET?

**Comment by LaurentGoderre** [comment] 2015-02-18 19:39
@RobJohnston it's not a bad way but ideally fixes would be added here so others can benefit from it

**Comment by pjackson28** [comment] 2015-02-18 21:33
Note that the reason why the horizontal scrolling is showing up is because the form is overflowing the tab panel (likely due to margin or padding). By overriding the tab panel overflow you are creating an accessibility issue where content that is too wide to fit the tab panel will be clipped rather than exposed through scrolling.

So in the end the issue isn't with the tabbed interface it likely is with your content overflowing the parent container. It is most likely because your content has negative margins or padding (likely from Bootstrap) which makes it bigger than the parent container. Suggest trying to wrap your content with additional Bootstrap parent container(s) to address your likely margin/padding issue. Usually when this happens with a Bootstrap container, it is because it is missing the appropriate Bootstrap parent container (e.g., using a Bootstrap "row" without a Bootstrap "container" as the parent).

**Comment by GarthMartin** [comment] 2015-02-19 13:06
@pjackson28 So based on the markup I posted, do you have a suggestion as to where to put the additional container(s)?  I have tried surrounding the wb-tabs and tabpanels divs with both container and container-fluid divs, but get the same (or worse) results.

Thanks,

**Comment by pjackson28** [comment] 2015-02-19 18:24
The new parent container(s) should be nested in each details element and include everything except the summary element. The key is to counteract the margins/padding that are causing the form elements to overflow the details elements. Using Firebug or Chrome developer tools will help to identify the problem and will help to identify the correct Bootstrap classes to use (essentially the negative margins/padding need to be countered with equal positive margins/padding).

Also noticed that you have nesting issues such as nesting a container-fluid inside of a container. Might be worthwhile using something like Bootlint to help ensure Bootstrap classes are nested properly.

**Comment by biljanap** [comment] 2015-02-19 19:29
@GarthMartin I had the same issue and I found that two options work for me:

**Option 1** - Placing ```<form>``` element inside ```<details>``` element (unless you must have multiple tabs inside the same ```<form>``` element).
Here is the code for Option 1:
```html
    <div class="">
      <div id="wb-auto-1" class="wb-tabs wb-tabs-inited tabs-acc">
        <ul aria-hidden="false" class="generated" role="tablist" aria-live="off">
          <li class="active" role="presentation"><a id="Tombstone-lnk" role="tab" tabIndex="0" aria-selected="true" aria-controls="Tombstone" href="#Tombstone">Contact Tombstone Data</a></li>
        </ul>
        <div class="tabpanels">
          <details aria-hidden="false" aria-expanded="true" id="Tombstone" class="wb-auto-1-grp open fade in" role="tabpanel" tabIndex="-1" aria-labelledby="Tombstone-lnk" open>
            <summary aria-hidden="true" aria-expanded="true" id="wb-auto-2" class="wb-toggle tgl-tab wb-toggle-inited wb-details-inited" role="tab" aria-posinset="1" tabIndex="0" aria-selected="true" aria-setsize="1" data-toggle='{"parent": "#wb-auto-1", "group": ".wb-auto-1-grp"}'>Contact Tombstone Data</summary>
            <form id="ctl00" class="container-fluid form-horizontal" method="post" action="TestTabs.aspx">
              <div aria-hidden="false" aria-expanded="true" class="tgl-panel" aria-labelledby="wb-auto-2">
                <div class="form-group">
                  <label id="MainContent_FirstNameLabel" class="col-sm-3 control-label required" for="MainContent_FirstNameValue">First Name</label>
                  <div class="col-sm-1">
                    <input id="MainContent_FirstNameValue" class="form-control" name="ctl00$MainContent$FirstNameValue" maxLength="50" type="text" required>
                  </div>
                </div>
              </div>
            </form>
          </details>
        </div>
      </div>
    </div>
```

**Option 2** - Placing css class  <code>form-horizontal</code> on <code>div</code> element that groups```<label>``` and ```<input>``` elements.
Here is the code for Option 2:
```html
<div class="">
    <form id="ctl00" class="" method="post" action="TestTabs.aspx">
      <div id="wb-auto-1" class="wb-tabs wb-tabs-inited tabs-acc">
        <ul aria-hidden="false" class="generated" role="tablist" aria-live="off">
          <li class="active" role="presentation"><a id="Tombstone-lnk" role="tab" tabIndex="0" aria-selected="true" aria-controls="Tombstone" href="#Tombstone">Contact Tombstone Data</a></li>
        </ul>
        <div class="tabpanels">
          <details aria-hidden="false" aria-expanded="true" id="Tombstone" class="wb-auto-1-grp open fade in" role="tabpanel" tabIndex="-1" aria-labelledby="Tombstone-lnk" open>
            <summary aria-hidden="true" aria-expanded="true" id="wb-auto-2" class="wb-toggle tgl-tab wb-toggle-inited wb-details-inited" role="tab" aria-posinset="1" tabIndex="0" aria-selected="true" aria-setsize="1" data-toggle='{"parent": "#wb-auto-1", "group": ".wb-auto-1-grp"}'>Contact Tombstone Data</summary>
            <div aria-hidden="false" aria-expanded="true" class="tgl-panel" aria-labelledby="wb-auto-2">
              <div class="form-group form-horizontal">
                <label id="MainContent_FirstNameLabel" class="col-sm-3 control-label required" for="MainContent_FirstNameValue">First Name</label>
                <div class="col-sm-1">
                  <input id="MainContent_FirstNameValue" class="form-control" name="ctl00$MainContent$FirstNameValue" maxLength="50" type="text" required>
                </div>
              </div>
            </div>
          </details>
        </div>
      </div>
      <hr>
    </form>
  </div>
```
Notice that I removed css classes <code>container</code> and <code>body-content</code> from your outside container divs (in both options). Without these classes tabs seems to be better aligned on the page.

**Comment by LaurentGoderre** [comment] 2015-02-20 21:39
Is it possible that #6532 is proposing a fix to your issue?

**Comment by RobJohnston** [comment] 2015-02-23 18:41
One would think so, since that issue is referencing the PR that introduced the exact line that I though caused the problem, but the solution doesn't work for me after adding this to the wet-boew.css class at the appropriate location:
```css
.wb-tabs .tgl-panel > .row {
  margin-left: 0;
  margin-right: 0; }
```

So if you start with the tabbed interface example, wrap it in a horizontal form, and then add a form group like in the form example, you'll end up with the following (trimmed to be the smallest and still show the problem):

```html
    <form class="form-horizontal" role="form" method="get" action="#">
        <div class="wb-tabs">
            <div class="tabpanels">
                <details id="details-panel1">
                    <summary>Example 1</summary>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" id="inputEmail3" placeholder="Email" />
                        </div>
                    </div>
                </details>
            </div>
        </div>
    </form>
```
Is there more mark-up required?

Also, #6439 is very similar but the <code>container-fluid</code> solution isn't working.

**Comment by pjackson28** [comment] 2015-02-23 20:10
A simple fix seems to just wrap all the form groups in a <code>div class="container-fluid"</code>. I don't know if that is proper according to Bootstrap but it does counteract the negative padding and margin applied to <code>.form-horizontal .form-group</code> which is disrupting the tabpanel. So the resulting markup could be:
```html
<form class="form-horizontal" role="form" method="get" action="#">
	<div class="wb-tabs">
		<div class="tabpanels">
			<details id="details-panel1">
				<summary>Example 1</summary>
				<div class="container-fluid">
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
						<div class="col-sm-10">
							<input type="email" class="form-control" id="inputEmail3" placeholder="Email" />
						</div>
					</div>
				</div>
			</details>
		</div>
	</div>
</form>
```

Note that applying <code>container-fluid</code> to the <code>details</code> element doesn't help, it needs to be a nested element.

**Comment by RobJohnston** [comment] 2015-02-23 20:26
That works for me. How 'bout you @GarthMartin ?

**Comment by LaurentGoderre** [comment] 2015-02-23 20:33
@pjackson28 we need to review our HTML. As I bumped Bootlint it found a lot of incorrect use of Bootstrap

**Comment by GarthMartin** [comment] 2015-02-27 16:13
@RobJohnston yes it has worked for me as well.  Thanks.

**Comment by cfarquharson** [comment] 2015-04-13 17:25
@pjackson28 @RobJohnston @GarthMartin you can also use `mrgn-lft-sm mrgn-rght-sm` (5px left and 5px right) instead of `container-fluid` (15px left and 15px right) if you don't want to eat into the available space

**Comment by hsrudnicki** [comment] 2015-06-15 15:41
Can this issue be closed or otherwise?

**Comment by pjackson28** [comment] 2015-06-15 17:24
Yes as it wasn't a problem with the plugin but instead with certain content that was included. Solutions have been identified for those situations. We can reopen if there are situations that are not addressed by the suggested solutions.

**Closed by pjackson28** 2015-06-15 17:24 UTC
Labels: Support Request
