### ISSUE TITLE
Basic HTML Version - Carousel Items

### ISSUE THREAD

**Issue by Robineast** [wet-boew/wet-boew#7445] opened 2016-03-09 15:55 UTC
@wet-boew/access-working-group 
The Basic HTML Version does not offer the same information as the standard version. Under Promotion in the carousel displays only the one tabin the Basic HTML Version and not all of the tabs. It is always the first tab regardless whether or not the carousel is paused or in play. 

A number of the graphics has the alt text set as: alt="null" Maybe these should be empty or have a proper alttext..

**Comment by pjackson28** [comment] 2016-03-09 15:58
@Robineast I suggest filing this on the Canada.ca theme repository instead as this issue is specific to the Canada.ca theme and not WET in general: https://github.com/wet-boew/GCWeb/issues/new

**Comment by pjackson28** [comment] 2016-03-09 18:28
Closing since now filed in https://github.com/wet-boew/GCWeb/issues/1081.

**Comment by shawnthompson** [comment] 2016-03-11 18:48
@pjackson28, I think this is two separate issues.

1. The carousel only displaying 1 panel when in *Basic HTML version* (WET issues?)
![image](https://cloud.githubusercontent.com/assets/2575266/13712041/863e3a70-e78f-11e5-8e08-ea02db694a6e.png)

2. Graphics having `alt` attribute set as `null` (GCWeb issue?)

@Robineast, can you give us an example of where you see the `alt="null"` set? Is it in GCWeb or on Canada.ca?

**Comment by pjackson28** [comment] 2016-03-11 18:56
@shawnthompson You are right, sorry about that and reopening. It is supposed to use CSS that is equivalent to the noscript scenario to make all panels visible. Here is the noscript SCSS that can perhaps help you with debugging the issue: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tabs/_noscript.scss.

Here is the SCSS that is applied in the Basic HTML version scenario that is supposed to achieve the same effect as the noscript SCSS: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tabs/_base.scss#L447-L500

**Comment by hsrudnicki** [comment] 2016-08-22 18:29
Does this remain still an issue or otherwise?  Please update the status of this for the current year, thank you

**Comment by dorina1** [comment] 2016-08-24 13:42
When we select Basic HTML on [canada.ca ](https://www.canada.ca/en/index.html?=undefined&wbdisable=true) we can only access 1 slide out of 4 slides available in the carousel. This happens when using IE 11 and Firefox. 
![basichtml-canadaca](https://cloud.githubusercontent.com/assets/1918938/17932613/d6960e40-69de-11e6-81fb-7d263ac31b89.JPG)
@wet-boew/access-working-group

**Comment by LaurentGoderre** [comment] 2016-10-24 15:37
@dorina1 that is by design. Since all enhacements are disabled, there is no way to navigate through them.

**Comment by rlambert27** [comment] 2016-10-24 15:40
@LaurentGoderre shouldn't they all be displayed one after the other instead? I believe it was that way before. To quote @EricDunsworth this isn't progressive enhancement.

**Comment by EricDunsworth** [comment] 2016-10-24 16:05
Btw I have a PR coming up within the coming days that'll modify the carousel to properly show all panels in noscript, wbdisable and print scenarios. It's mostly ready but needs a few more adjustments before I finalize it.

**Comment by LaurentGoderre** [comment] 2016-10-24 16:25
@rlambert27 @EricDunsworth The argument can be made for both ways though, because showing all of them could be a barrier to usability to have a wall of images two or three screens high before you can even get to the content.

**Comment by EricDunsworth** [comment] 2016-10-26 14:27
@LaurentGoderre Is some extra scrolling really that big of a barrier to usability compared to depriving users of content? As far as scrolling is concerned, showing all carousel panels in noscript/wbdisable/print isn't any different from what's already been done for years with grid layouts becoming linearized in smaller viewports.

Regardless of whether or not a carousel is implemented as primary or secondary content, IMO its panels still contain information that should be available to all users. The carousel plugin shouldn't be anything more than a nicer interface for cycling between the panels. That's in line with the principle of progressive enhancement (which [WET is supposed to be following](http://wet-boew.github.io/v4.0-ci/docs/index-en.html)).

@pjackson28 also mentioned earlier in this issue that the carousel is supposed to use CSS to show all panels in noscript/wbdisable scenarios. In the [tabbed interface's documentation's configuration options](http://wet-boew.github.io/v4.0-ci/docs/ref/tabs/tabs-en.html#config), ``print-active``'s description also states that by default, all panels are supposed to be printed by default (unless that class is used).

**Comment by EricDunsworth** [comment] 2016-12-19 20:30
FYI #7815 should fix what's left of this issue, since it restores all hidden carousel panels in noscript and wbdisable (basic HTML) scenarios.

As for ``alt="null"``... I can't currently find any sign of it in wet-boew, GCWeb, nor Canada.ca's real home page. So I presume that's no longer an issue.

**Closed** 2017-03-30 15:41 UTC
Labels: Bug Report: Normal, Plugin: Tabbed Interface/Carousel
