### ISSUE TITLE
Input type="date" polyfill (date picker): How can I force the WET date picker to display on iOS Mobile Safari and Chrome Desktop Browsers? 

### ISSUE THREAD

**Issue by pauljadam** [wet-boew/wet-boew#7194] opened 2015-11-13 21:44 UTC
How can I force the WET date picker to display on iOS Mobile Safari and Chrome Desktop Browsers? I.e. I want to always use this date picker and never the browser/OS native HTML date picker. Thanks!

http://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html

**Comment by sgdowney** [comment] 2015-11-16 14:32
The date picker polyfill is there only to provide functionality to browsers that don't have this functionality natively.  It's not designed to override the native functionality.  That being said, you could try extracting the date picker source and wiring it in as a custom input type.

**Comment by pauljadam** [comment] 2015-11-16 15:53
The reason I need to only use the WET date picker is because Native HTML5 date pickers are not accessible or fully accessible. Even iOS Mobile Safari's date picker is a worse experience in terms of accessibility of entering a calendar date. Google Chrome's date picker is also not screen reader accessible. Would be really awesome if there was a flag or attribute to add to inputs to always use this date picker and never a native one.

**Comment by LaurentGoderre** [comment] 2015-11-18 14:03
It might be possible but it might cripple to mobile friendliness.

**Comment by pauljadam** [comment] 2015-11-18 22:41
Lots of websites still use custom date pickers that look like a calendar view even for their mobile visitors rather than using a native HTML5 input type=date control. So they're using the "non-mobile friendly" calendars already and they like to have control over the colors, etc. I'm more concerned about accessibility friendliness than mobile friendliness :)

**Comment by nschonni** [comment] 2015-11-19 01:38
@pauljadam you just manually include the script https://github.com/wet-boew/wet-boew/blob/master/src/polyfills/datepicker/datepicker.js (it is condilly loaded if Modernizr indicates no native support). It will apply to the date elements, but there may be conflicts with native handling since it was designed for browsers with no understanding of `input[type=date]`. If you're looking to use this in a non-WET site, then you'll likely need to swap some stuff like the i18n and any wb.* methods.

**Comment by LaurentGoderre** [comment] 2015-11-19 14:03
Maybe you can disable the native behavior using the shadow DOM

**Comment by hsrudnicki** [comment] 2016-01-21 19:52
@pauljadam : Is this above still an issue?  Either way, please update this issue's status whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by pauljadam** [comment] 2016-01-21 20:02
It's an issue that I would like the feature with the framework but I don't require it for a specific project and it's not a functionality bug. It's more of Paul's feature request but not something I need so I'll close it. Thanks for the responses!

**Closed** 2016-01-21 20:02 UTC
Labels: Help: Implementation, Polyfill: Date picker
