### ISSUE TITLE
Multimedia Player - Volume Toggle button issues with JAWS

### ISSUE THREAD

**Issue by dorina1** [wet-boew/wet-boew#8030] opened 2017-05-26 19:22 UTC
@wet-boew/access-working-group 
On both multimedia players ([Multimedia Player - Video](http://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html) and [Multimedia Player - Audio-only](http://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-audio-en.html) the Volume Toggle button does not provide the proper information to JAWS users.

I tried it when using JAWS 16 and JAWS 18 on IE 11 and Edge and when the Volume Toggle button is in focus the verbal message we get is "Volume left right slider 75 to increase or decrease use the arrow keys". (75 is the value that changes when we increase decrease the volume).

We are not aware which arrow keys to use for the volume. It should say: “Volume. To increase or decrease use the up/down arrow keys.” And to also let us know that left/right arrows will backward/forward the audio/video file.

**Comment by LaurentGoderre** [comment] 2017-05-26 19:29
Duplicate of #7955

**Closed by LaurentGoderre** 2017-05-26 19:29 UTC
