### ISSUE TITLE
Create vertical align CSS for tables?

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#6958] opened 2015-07-21 16:52 UTC
Can you add a vertical align CSS that can be used in tables?  In some tables, especially those with merged cells, a vertical align effect helps to nicely balance the content.  

`.v-algn-mddl {vertical-align: middle !important}`

**Comment by pjackson28** [comment] 2015-07-22 14:36
Closing as duplicate of #6906. Please submit your suggestions in that other issue.

**Closed by pjackson28** 2015-07-22 14:36 UTC
