### ISSUE TITLE
DataTables - Individual column searching

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#7164] opened 2015-10-26 14:04 UTC
When looking at datatables I found a way to search columns individually but it is not working in WET4. 

My thoughts are that it is due to me using the JASON array in the opening table tag in combination with the search columns individually code at the bottom of my page. Is there a way to combine the two or another solution all together? 

**JASON array:**

    data-wb-tables='{
        "info" : false, 
        "filter" : false, 
        "paginate" : false, 
        "order" : [[ 1, "asc" ]], 
        "columnDefs": [{ "orderable" : false, "targets":[0] }] 
    }'

**Search columns individually code:**

	$( document ).on( "wb-ready.wb", function( event )  { 
	
		$("tfoot").css({"display":"table-header-group"});
	
		// Setup - add a text input to each footer cell
		$('table tfoot th').each( function () {
			$(this).html( '<input type="text" class="form-control width100 fnt-wght-nrml" />' );
		} );
	
		$('table tfoot th:eq(0)').find("input[type=text]").remove();
	
		// DataTable
		var table = $('table').DataTable();
	
		// Apply the search
		table.columns().every( function () {		
			var that = this;
			$( 'input', this.footer() ).on( 'keyup change', function () {
				if ( that.search() !== this.value ) {
					that
					.search( this.value )
					.draw();
				}
			});
		});
	
	});

**Comment by LaurentGoderre** [comment] 2015-10-26 14:22
You should not call `DataTable()` on an already initialized datatable. PLus that code looks very inefficient. What exactly are you trying to achieve?

**Comment by wilkmit** [comment] 2015-10-26 14:25
Yeh its clearly still a work in progress. All I need is individual col search as the title states.

**Comment by LaurentGoderre** [comment] 2015-10-26 14:28
Did you follow this post? http://datatables.net/forums/discussion/258/search-filter-text-applied-on-a-single-column

Your best bet is to listen for DataTables event, then create your search box. That way you would have a valid reference for the datatable instead of hacking one out

**Comment by wilkmit** [comment] 2015-10-26 14:31
Here is what I followed https://datatables.net/examples/api/multi_filter.html.

**Comment by LaurentGoderre** [comment] 2015-10-26 14:33
http://datatables.net/reference/event/preInit

**Comment by wilkmit** [comment] 2015-10-26 17:36
Is there a way in WET 4 where I can NOT use the JASON array in the opening table tag and just use JS?

**Comment by LaurentGoderre** [comment] 2015-10-26 17:49
It is possible but why don't you want to use the `data-` attribute?

**Comment by wilkmit** [comment] 2015-10-26 18:07
Because the example I am working from (https://datatables.net/examples/api/multi_filter.html) on the datatable website works when WET is not involved in the process. So I am thinking if I initialize my datatable in the JS instead of using the wb-tables class and the JASON array and then try tyh code in the link I provided it may work. That way I am not trying to initialize it twice. That's my thought process...

**Comment by pjackson28** [comment] 2015-10-26 18:18
@wilkmit The reason you are getting the initialize twice is because you are using the incorrect function call. You are using <code>DataTable()</code> which initializes the table and returns an API instance where what you are probably looking for is <code>dataTable().api()</code> which does not initialize the table but instead returns the already initialized instance. You can find more about that on the [API page](http://datatables.net/reference/api/). That way you can let WET initialize the table properly (with all the accessibility enhancements) rather than trying to get around the WET initialization which would mean you lose all the accessibility enhancements and won't get any more JS access than you could already get through WET.

**Comment by sbrioux** [comment] 2015-10-27 13:52
@LaurentGoderre you say it is possible to initialize a datatable without using the data- attribute... do you have an example of how?  I have a table that's being built by JS on the fly from an AJAX response.

**Comment by LaurentGoderre** [comment] 2015-10-27 13:57
I don't have an example no but plugins are built to be initializable through javascript

**Comment by pjackson28** [comment] 2015-10-27 14:08
@sbrioux You would initialize it using the <code>wb-init.wb-tables</code> event as described in the documentation. So build the table in a string in JavaScript (using the AJAX response), inject that into the DOM (inject all at once rather than multiple DOM injections for performance reasons), and then fire the <code>wb-init.wb-tables</code> event on the the table in the DOM to initialize it.

**Comment by sbrioux** [comment] 2015-10-27 14:39
@pjackson28 previously I was passing the JSON string into the dataTables() method to set the parameters.  But how exactly am I doing that through the event now?

```$('.wb-tables').on('wb-init.wb-tables', function(event){ event = JSONSTRING});```???

**Comment by pjackson28** [comment] 2015-10-27 14:59
@sbrioux You would have to pass it through the <code>data-wb-tables</code> attribute in your HTML fragment. Note that the JSON passed to the <code>data-wb-tables</code> attribute is effectively the same as passing that same JSON to the <code>dataTables</code> function. The only difference is the WET enhancements for accessibility and i18n to ensure WCAG 2.0 AA and higher conformance as ell as proper support for French and other languages.

Here is the code for initializing the table which uses extend to override the plugin defaults first with <code>window[ 'wb-tables' ]</code> followed by what is in <code>data-wb-tables</code>:
```js
$elm.dataTable( $.extend( true, {}, defaults, window[ componentName ], wb.getData( $elm, componentName ) ) );
```

**Comment by sbrioux** [comment] 2015-10-27 15:43
@pjackson28 so I kind of did it a round about way.
`$('#example').attr('data-wb-tables', JSON.stringify(options))`
followed by triggering the wb-init.wb-tables but i'm now getting an Uncaught TypeError coming from wet-boew.js:10032 which is happening when I'm trying to resort based on a column header.  This is with serverSide: true

**Comment by andre-gh** [comment] 2015-10-27 15:49
You can not convert a function to JSON, if you want to setup event handlers you will need to use window['wb-tables']

**Comment by andre-gh** [comment] 2015-10-27 16:01
Sorry, misread where the TypeError was. Which version of WET are you on?  I can check what is on that line number.

**Comment by sbrioux** [comment] 2015-10-27 16:04
@andre-gh i'm using currently 4.0.18.  However, I did notice that I was trying to stringify an anonymous function (which I don't think I can do).

Question: is the `wb-data-tables` attribute synonymous with the `window['wb-tables']` variable? I.e. I could just do `window['wb-tables'] = myOptions` (which includes the `"ajax":{"error": function(){}}`)

**Comment by andre-gh** [comment] 2015-10-27 16:07
Yes the global wb-tables gets merged with the data options to produce the final options passed to the module.  They should go hand-in-hand with no changes made.  The only flaw is that window wb-tables is global and you have to clear it if you want to init a different table with different settings and init them one at a time.

In the future WET plugins will hopefully be subclassable to allow you to pass custom event handlers/etc in a more modular way.

**Comment by sbrioux** [comment] 2015-10-27 16:13
Okay.  Regardless if I do 
`	// Datatables options
	window['wb-tables'] = {
		"columnDefs": [{
		"targets": -1,
		"orderable": false,
		"searchable": false
	}],
	"ordering": true,
	"searching": true,
	"processing": true,
    "deferRender": true,
    "serverSide": true,
    "ajax": { 
    	"url":"xhr.php", 
      	"type":"POST",
      	"data": data,
      	"error": function(httpStat, textStat, err) {
      		ajax.empty().html('<div class="center">Something went wrong. Error code: ' + err + '</div>');
      	}
      },
      "columns": columns
  	};
`
or 
`$('#tableId').attr('data-wb-tables', JSON.stringify(options))`

I'm still seeing the following:
Uncaught TypeError: b.replace is not a function wet-boew.js:10032

**Comment by andre-gh** [comment] 2015-10-27 16:18
Are you by any change returning cell values which are null/undefined?  Could you try returning an empty string for those instead.

**Comment by sbrioux** [comment] 2015-10-27 16:48
Just looking through it and I'm not seeing any null/undefined values, there is HTML markup in the cells though.

**Comment by andre-gh** [comment] 2015-10-27 16:56
I suspect this has to do with the numeric sorting code in WET, but without a dataset to test I can not be sure what is causing it.

**Comment by sbrioux** [comment] 2015-10-27 17:07
Would this help any?

{"draw":"7","recordsTotal":"68915","recordsFiltered":"68915","data":[{"VERSION":["1"],"E2":["422 CONVERTER"],"E4":["53003-036"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2F422_converter%2F53003-036&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["422 CONVERTER"],"E4":["53003-088"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2F422_converter%2F53003-088&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["ACROANTENNA TECHNOLOGIES,ANTENNA,IRIDIUM"],"E4":["36859"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Facroantenna_technologies%2Cantenna%2Ciridium%2F36859&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["ACROANTENNA TECHNOLOGIES,ANTENNA,IRIDIUM"],"E4":["37555"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Facroantenna_technologies%2Cantenna%2Ciridium%2F37555&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["ACROANTENNA TECHNOLOGIES,ANTENNA,IRIDIUM"],"E4":["37734"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Facroantenna_technologies%2Cantenna%2Ciridium%2F37734&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["AIR,PRESSURE SENSOR MODEL AIR SB2A"],"E4":["9J1703"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Fair%2Cpressure_sensor_model_air_sb2a%2F9j1703&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["AIR,PRESSURE SENSOR MODEL AIR SB2A"],"E4":["F0640004"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Fair%2Cpressure_sensor_model_air_sb2a%2Ff0640004&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["ANDREW,POSS PROCESSOR POSS-F01"],"E4":["94-00103"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Fandrew%2Cposs_processor_poss-f01%2F94-00103&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["AXYS,SENSOR PROCESSOR MOD (3M & NOMAD)"],"E4":["WM157"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Faxys%2Csensor_processor_mod_%283m_%26_nomad%29%2Fwm157&version=1\" >View<\/a>"},{"VERSION":["1"],"E2":["AXYS,TRANSMITTER MODULE - 3M & NOMAD"],"E4":["WM031"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2Faxys%2Ctransmitter_module_-_3m_%26_nomad%2Fwm031&version=1\" >View<\/a>"}]}

It's just a small sample of a JSON response I am dealing with.

**Comment by pjackson28** [comment] 2015-10-27 17:09
It looks like it is because of the formattedNumCompare function which is used by the Tables plugin for sorting formatted numbers. Here is the WET code where the issue occurs:

```js
	// RegEx used by formattedNumCompare
	wb.formattedNumCompareRegEx = /(<[^>]*>|[^\d\.])/g;

	// Compares two formatted numbers (e.g., 1.2.12 or 1,000,345)
	wb.formattedNumCompare = function( a, b ) {
		var regEx = wb.formattedNumCompareRegEx,
			aMultiple = a.indexOf( "-" ) === -1 ? 1 : -1,
			aNumbers = ( ( a === "-" || a === "" ) ? "0" : a.replace( regEx, "" ) ).split( "." ),
			bMultiple = b.indexOf( "-" ) === -1 ? 1 : -1,
			bNumbers = ( ( b === "-" || b === "" ) ? "0" : b.replace( regEx, "" ) ).split( "." ),
			len = aNumbers.length,
			i, result;

		for ( i = 0; i !== len; i += 1 ) {
			result = parseInt( aNumbers[ i ], 10 ) * aMultiple - parseInt( bNumbers[ i ], 10 ) * bMultiple;
			if ( result !== 0 ) {
				break;
			}
		}
		return result;
	};
```

The above code is called by DataTables through the "formated-num-asc" and "formatted-num-desc" calls:
```js
	// Formatted number sorting
	"formatted-num-asc": function( a, b ) {
		return wb.formattedNumCompare( a, b );
	},
	"formatted-num-desc": function( a, b ) {
		return wb.formattedNumCompare( b, a );
	}
```

So based upon your error, it looks like there is something wrong with the value that is being passed for the b variable.

Note that this is the WET code that DataTables uses to determine what is classified as a formatted number:

```js
	// Formatted numbers detection
	// Based on: http://datatables.net/plug-ins/type-detection#formatted_numbers
	dataTableExt.aTypes.unshift(
		function( sData ) {

			// Strip off HTML tags and all non-alpha-numeric characters (except minus sign)
			var deformatted = sData.replace( /<[^>]*>/g, "" ).replace( /[^\d\-\/a-zA-Z]/g, "" );
			if ( $.isNumeric( deformatted ) || deformatted === "-" ) {
				return "formatted-num";
			}
			return null;
		}
	);
```

**Comment by pjackson28** [comment] 2015-10-27 17:14
I wonder if some of your formatted numbers could be causing problems. Try filtering out some of the following one by one to see if addresses the issue:
* 53003-088 (any number with hyphens, that are not the first character... this is a possible culprit looking at the regex)
* F0640004 (any number that includes letters)

**Comment by pjackson28** [comment] 2015-10-27 17:32
@sbrioux I just tried those combinations and they don't seem to be the culprit. The functions in question handled the ascending and descending sorting for them no problem. Are there any other formatted numbers that you have that could be possible culprits that are not in the sample you provided?

**Comment by sbrioux** [comment] 2015-10-27 17:36
@pjackson28 really hard to tell there are 68915 results to deal with.  Could this be some kind of issue related to server side processing setup?

Pagination seems to be okay.  The error pops up only when trying to sort by a header or trying to filter.

**Comment by pjackson28** [comment] 2015-10-27 17:42
@sbrioux There are only two places in the unminified WET code that use b.replace, one being Charts (which would not be used at all in this scenario), and the other being wb.formattedNumCompare which is called each time you try to sort (which will likely happen any time you sort by header or post-filtering). So something in the column in question is being passed to formattedNumCompare as the b variable and the function can't handle it. 

So the function is treating something like a string when it actually isn't. Thinking on the flip-side, do you have any entries in the column that are actual numbers (that would pass isNumeric) where the rest of the numbers have formatted numbers (so would not pass isNumeric without filtering out some characters)? Perhaps the column is detecting formatted numbers but there are some actual numbers in there that are throwing off the formattedNumCompare function.

**Comment by pjackson28** [comment] 2015-10-27 17:44
Actually never mind about the real numbers part, I just mixed formatted and real numbers in the same column and it worked fine. So something is being passed in that is causing a failure on b.replace.

**Comment by sbrioux** [comment] 2015-10-27 17:53
I'm leaning to something missing on the serverside stuff here.
The table is being initialized with the following:
```javascript
	// Datatables options
	window['wb-tables'] = {
		"columnDefs": [{
		"targets": -1,
		"orderable": false,
		"searchable": false
	}],
	"ordering": true,
	"searching": true,
	"processing": true,
    "deferRender": true,
    "serverSide": true,
    "ajax": { 
    	"url":"xhr.php", 
      	"type":"POST",
      	"data": data,
      	"error": function(httpStat, textStat, err) {
      		ajax.empty().html('<div class="center">Something went wrong. Error code: ' + err + '</div>');
      	}
      },
      "columns": columns
  	};
```
So this means the sorting and chunking of data is and should be done by the server side php script.  However, it almost seems as though the DataTables plug in is still trying to sort it here instead of passing that work to the PHP script.

**Comment by pjackson28** [comment] 2015-10-27 18:15
I wonder if your use of orderable and ordering in addition to serverSide is triggering client-side sorting in addition to your server-side sorting. In theory serverSide should push it to the server to do the ordering like in https://www.datatables.net/examples/server_side/simple.html but something you are doing is trggering the client-side sort as well.

Even if you manage to disable the client-side sort, would be good to know what is tripping up formattedNumCompare. After some testing "a123245" is not a formatted number (no letters allowed) and "1233-32432" is not a formatted number either (no mid-string hyphens) so both are treated as strings (so will not make it to formattedNumCompare). I've tried various combinations and I can't seem to find a string that passes the formatted number check but trips up formattedNumCompare.

**Comment by sbrioux** [comment] 2015-10-27 19:01
As a test I included the following:
`<script type="text/javascript" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>`
Then I put the code as per pre 4.0.18.. probably 4.0.2 I believe.  I passed my options to the dataTable() method and the tables works as it did before I tried updating my templates to 4.0.18.

On a side note should this possibly be a new and separate issue?

**Comment by pjackson28** [comment] 2015-10-27 19:26
That's because the formattedNumCompare function was added after v4.0.2 to address issues being raised about formatted numbers not being sorted correctly. What is happening now is something in your table data is being detected as a formatted number and is tripping up the associated formatting function, where in earlier versions it just treated those formatted numbers like a string (and sorted accordingly, which doesn't work well for formatted numbers).

**Comment by sbrioux** [comment] 2015-10-29 15:42
For now I have been instructed to move on in my project since we have a work around at the moment.

Essentially I'm just including the 1.15.5 DataTables plugin on the page in question and working with it directly that way.

**Comment by andre-gh** [comment] 2015-10-29 15:52
@pjackson28 Would it be a good idea to just put some protections in that sorting function?  Or should we try to actually fix the issue.

**Comment by pjackson28** [comment] 2015-10-29 15:58
@andre-gh It would be good to find out why it is breaking so we can properly fix it. It looks to be two issues in combination:
1. The data is being incorrectly identified as being formatted numbers. Not sure what is tricking the test.
2. Data for some reason is not being passed as a string. Perhaps an object or an actual number is being passed.

**Comment by pjackson28** [comment] 2015-10-29 16:01
@sbrioux If your application is public facing then the issue is that your solution likely will not meet the Standard on Web Accessibility unless you address the accessibility issues with DataTables like WET did (which will be way more work and much more problematic than helping us to fix this issue in WET). Ìt will also create issues with onboarding to Canada.ca. 

For us to fix this in WET, we would need to find out what data is causing the issue. We can likely determine it quickly with a little JS. If you add something like the following to the wb.formattedNumCompare function in the unminified wet-boew.js file then we will at least know what is being passed that is problematic:

```js
if ( !b.replace ) {
     window.console.log( "Invalid value for b: [" + b + "], typeof: " + typeof b );
}
```

The key is to identify what is causing an issue for the

**Comment by pjackson28** [comment] 2015-10-29 16:02
@andre-gh As an interim solution, we could have a test to ensure b.replace and a.replace exist but that it id only a temporary bandaid and wouldn't address the underlying issues (e.g., data being classified incorrectly, incorrect sorting, etc.)

**Comment by andre-gh** [comment] 2015-10-29 16:03
Yeah, I will dig into this today.

**Comment by sbrioux** [comment] 2015-10-29 16:26
@pjackson28 so I got the debug statement in there.  Could be the way the data is formatted coming back from the xhr.php script.

`Invalid vlaue for b: [1], typeof: object`

I used the following debug in the unminified first 
```javascript
// Formatted numbers detection
// Based on: http://datatables.net/plug-ins/type-detection#formatted_numbers
dataTableExt.aTypes.unshift(
	function( sData ) {
		if(!sData.replace){
			window.console.log("Invalid vlaue for b: [" + sData + "], typeof: " + typeof sData);
		}
		// Strip off HTML tags and all non-alpha-numeric characters (except minus sign)
		var deformatted = sData.replace( /<[^>]*>/g, "" ).replace( /[^\d\-\/a-zA-Z]/g, "" );
		if ( $.isNumeric( deformatted ) || deformatted === "-" ) {
			return "formatted-num";
		}
		return null;
	}
);
```

```json
"data":[{"VERSION":["1"],"E2":["422 CONVERTER"],"E4":["53003-036"],"VIEW":"<a class=\"btn btn-default\" name=\"instance\" href=\"..\/instance\/manage_instance_en.html?instance=%2Fmetadata%2Fmsc%2Fsensor%2Falm%2Finstance-xml-2.0%2F422_converter%2F53003-036&version=1\" >View<\/a>"}]
```
Looking at that really small sample I'm thinking that maybe "VERSION": [] is probably bad.  So the version key is point to an array of 1 value.  I'm going to see if I can modify the xhr.php script that's returning the data to remove the array and just dump the value there and report back.

**Comment by sbrioux** [comment] 2015-10-29 16:30
Looks like that fixed it.  So it was the fact that b (or sData) wasn't able to deal with an array of values, which makes sense looking at the method.  In our case they aren't necessary but not sure if this would always be the case.

**Comment by andre-gh** [comment] 2015-10-29 16:32
I seem to recall a year and a half ago being able to use an array of values by writing my own custom filters or something to spit out one div per item, I do not recall what I did exactly though.  It is possible though with the datatables API.

**Comment by pjackson28** [comment] 2015-10-29 16:34
@sbrioux How is the array of values supposed to be implemented in the resulting table? Is it supposed to be split across multiple cells, be post-processed by custom JS within a single cell, or rendered as is as a string?

**Comment by sbrioux** [comment] 2015-10-29 16:37
@pjackson28 in my case it isn't required so I just removed it and made it "key": "value" instead of "key" : ["value"]

**Comment by andre-gh** [comment] 2015-10-29 17:02
I wonder if we should handle that case in our filter function, I will check up with the datatables docs and find out.

**Comment by pjackson28** [comment] 2015-10-29 17:16
@andre-gh Probably the simplest fix to that detection code is to check for sData.replace. If it doesn't exist then return null because it should not be treated as a formatted number (since an integer or float is not a formatted number and neither is an object). So something like the following would work:
```js
if ( !sData.replace ) {
   return null;
}

For formattedNumCompare, you could do the same check except force it to a string when it is not a string. So something like:
```js
if ( !a.replace ) {
   a += "";
}
if ( !b.replace ) {
   b += "";
}
```

**Comment by wilkmit** [comment] 2015-10-29 19:35
This is no longer about the issue I am having so I closed it.

**Closed** 2015-10-29 19:34 UTC
Labels: Bug Report: Minor, Plugin: Table enhancement (DataTables)
