### ISSUE TITLE
Form validation: 

### ISSUE THREAD

**Issue by KodiT56** [wet-boew/wet-boew#6876] opened 2015-06-18 14:11 UTC
Could some one get back to me. Having the js.mobile added  for page responsiveness. working correctly in basic HTML mode. Also form validation hides the forms when basic HTML is used. is there a patch to correct this.
kodit56@hotmail.com
613 402 9210

**Comment by pjackson28** [comment] 2015-06-18 21:40
Why did you add js.mobile for page responsiveness? That is what we use the Bootstrap CSS framework for.

As for your issue, I can't reproduce with the form validation working example: http://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html. Do you mean the feedback form? If so, that is intentional when JS or enhancements are disabled.

**Comment by KodiT56** [comment] 2015-06-19 11:38
Thanks so Much for getting back to me about this. I am the WCAG auditor for Bell and CGI for the SSC youremail@canada.gc.ca and the issue is that they are allowing the fact that JavaScript has to stay active.
so having the Basic HTML will break the application in a variety of ways.  Also because of 3rd party back end systems that dynamically creating there version of the Feedback form that does not function like the WET template. SSC representative stated we needed to add this JavaScript js.mobile.  I am here down town on 160 Elgin Street If possible could I set up a meeting with you to clarify what should be really used to make this product as WCAG compliant as possible.
Kodi Lavergne

**Comment by pjackson28** [comment] 2015-06-19 16:43
I'm still unclear as to why js.mobile is needed as the page responsiveness is done with CSS (through Bootstrap responsive grids) so Basic HTML view would have no impact on that. All Basic HTML view does is prevent WET enhancements from loading (note that this is only meant for users that have difficulties with those enhancements, such as users with really old screen readers).

If you want to stop the form from being hidden when in Basic HTML version then simply override the <code>display: none</code> that is being applied to the form. So you could do that with something like the following (correcting the selector as needed):
```css
.wb-frmvld.nojs-hide {
    display: block !important;
}
```

**Comment by KodiT56** [comment] 2015-06-19 16:55
This was directed to us by Shared Services Canada to add the mobile.js for the responsive behavior.
Obviously is misinformed. I know it is based on CSS media queries.... 
I thought that changing the CSS or template was taboo  because of updates are being updated.
The sample CSS correction you offered  What CSS is that located in?

**Comment by pjackson28** [comment] 2015-06-19 16:58
It was just a suggestion for a CSS override. An even easier (and probably better) approach is to just to remove the <code>nojs-hide</code> class from the div element (it hides content when in Basic HTML version). That way you don't have to make any CSS change and get the intended behaviour.

**Comment by KodiT56** [comment] 2015-06-19 17:08
Thanks Paul
The Details of your CSS are a bit to wrap the head around. The issues with this application having the JavaScript has to be always enabled is a change from the Status Quo for WCAG. So really the basic HTML concept is another layer to my problem. 
The other issue is they are using still the 3.17 template and refuse to update until product is launched....

**Comment by pjackson28** [comment] 2015-06-19 17:16
As JS always being enabled, if a user is explicitly requesting the WET enhancements to be disabled then you shouldn't be overriding that request. Instead, what about requiring the user to use Standard version to access the application? At least you are up front about it rather than forcing JavaScript enhancements back on them without their knowledge or consent.

As for using 3.17, we can't help much more since we don't support that version.

**Comment by KodiT56** [comment] 2015-06-19 17:20
Understood SSC made it clear in the design doc the JavaScript to stay on. Yep fully aware of this fact.
Not the way I would have done it I would of followed the template to the letter. I have made that recommendation several times. with no Success.
But pointing out that class is very helpful Thanks again

**Comment by pjackson28** [comment] 2015-06-19 17:24
Note that what I provided wouldn't work in v3.17 (it is v4.x only). You would instead need to add the following custom CSS:
```css
.no-js .wet-boew-formvalid {
    display: block !important;
}
```

**Comment by KodiT56** [comment] 2015-06-19 17:25
Perfect Thanks

**Comment by pjackson28** [comment] 2015-06-19 17:26
Can we close the issue?

**Comment by KodiT56** [comment] 2015-06-19 17:27
What CSS is to be changed then close

**Comment by KodiT56** [comment] 2015-06-19 17:28
need to spoon feed the developers or they will not do it.

**Comment by pjackson28** [comment] 2015-06-19 17:31
Just add the following somewhere in a custom CSS file:
```css
.no-js .wet-boew-formvalid {
    display: block !important;
}
````

**Comment by KodiT56** [comment] 2015-06-19 17:31
Understood

**Comment by KodiT56** [comment] 2015-06-19 17:34
Close the issue Please thanks

**Closed** 2015-06-19 17:34 UTC
