### ISSUE TITLE
Building WET issue with script\setup

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#6629] opened 2015-03-20 19:37 UTC
![github](https://cloud.githubusercontent.com/assets/1738230/6759472/a51004f2-cf16-11e4-96ed-437afa62a31c.png)

Tried using Eric's setup guide and we ran into a whole bunch of issues. It asked for Python to be installed which we did the latest version. We then tried 2.5.9 and 2.5.7 and now we don't seem to get that error anymore.

We tried different version of NPM like @next, @2.5.0 and @2.5.7 and all of them still generate the same error. We could force grunt to compile and would get everything except the CSS files.

Eric even tried copying the files that work on his machine directly onto mine and still doesn't work.

Any ideas? @EricDunsworth  may add additional details.

**Comment by LaurentGoderre** [comment] 2015-03-20 19:53
Are you up to date? node-sass hasn't required a build for Windows in over a year. The alternative is that the download of the node-sass binary is being blocked...

**Comment by EricDunsworth** [comment] 2015-03-20 20:28
@LaurentGoderre Could it be that something changed recently with regards to Windows building? Both @rlambert27's and my proxy settings are identical and have worked successfully for me in the past. I got him to run a .bat script I created that sets up proper HTTP/HTTP proxy settings for git (including your insteadOf stuff), npm, user environment variables and user profile copies.

Btw I wasn't having this issue as recently as early this afternoon. To try replicating on my end I wiped out my pre-existing WET build system setup (including node.js and all of its leftover files) and reinstalled latest versions from scratch... just got bugged to install Python too. If I install Python 2 it'll probably lead me into the exact same error @rlambert27 posted in the OP.

The only immediate difference I can think of between our respective setups is that up until now I was using node.js v0.10.36 (with npm manually updated to v2.5.0), whereas @rlambert27 is using the latest version (v0.12.0, tested with a whole variety of npm flavors without any luck).

**Comment by LaurentGoderre** [comment] 2015-03-20 20:58
hmmm.....i never used version 0.10. Our build hasn't really changed

**Comment by LaurentGoderre** [comment] 2015-03-23 12:58
I meant, I never used version 0.12

**Comment by LaurentGoderre** [comment] 2015-03-23 18:17
@rlambert27 I think I need the full log. There should be an npm-debug.log which has the full log.

**Comment by stephenbe** [comment] 2015-03-24 01:42
@rlambert27 I just had the exact same problem, try to update your package.json grunt-sass version. 
`"grunt-sass": "^0.14.1"`
becomes
`"grunt-sass": "^0.18.1"`

That should fix your issue and you should be able to compile the sass with no problem.

**Comment by EricDunsworth** [comment] 2015-03-25 20:33
@stephenbe Thanks :)! Worked for me too.

@LaurentGoderre @pjackson28 Could that dependency's version number be changed to 0.18.1 in the wet-boew repo to avoid needing to manually do this? I could send over a PR if needed.

**Comment by stephenbe** [comment] 2015-03-25 22:50
@EricDunsworth you are very welcome :)

**Comment by LaurentGoderre** [comment] 2015-03-26 13:43
Not blindly no.....we have to determine the impact this has on the CSS rendering.

**Comment by EricDunsworth** [comment] 2015-03-26 14:06
@LaurentGoderre Mind if I open a PR now, put a "do not merge" note in it, then compare github.io's working examples to my local ones to ensure 0.18.1 hasn't broken anything?

**Comment by LaurentGoderre** [comment] 2015-03-26 14:08
Sure, maybe post a diff between the two here

**Comment by LaurentGoderre** [comment] 2015-03-26 15:16
Sure, maybe post a diff between the two here

**Comment by EricDunsworth** [comment] 2015-03-27 04:08
Instead of going through all the working examples, I compared what's currently in wet-boew-dist's v4.0-dist branch to a build I did using grunt-sass 0.18.1. For all I know some of the differences below might be OS-related (e.g. Windows 7 x64 vs Travis-CI... Linux?). I can't build with 0.14.1 on neither my workstation nor home computer.

**Differences:**
* ``@charset "UTF-8";`` got added to all CSS files.
* Some CSS files already contain  ``@charset "utf-8";`` before their header comments. In those cases, ``@charset "UTF-8";`` still got added after the header comment, resulting in two charset declarations :S. For example...
```
@charset "utf-8";
/*!
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 * v4.0.13-development - 2015-03-26
 *
 */
@charset "UTF-8";
```
* All ``rgba(0, 0, 0, 0)`` colour properties got changed to ``transparent``.
* Measurements along the lines of 0.1, 0.4, etc have had their leading zero stripped. For example, a measurement like "0.4em" would now be ".4em".
* Many colour values seem to have changed very slightly. For example, ``a.text-primary:hover { color: #1c588a; }`` is now ``a.text-primary:hover { color: #1c578a; }``.
* Instances of ``cursor: not-allowed;`` have changed to ``cursor: false;``.
* Looks like various selectors are being generated differently from before. For example, one selector changed from ``.btn-lg .caret, .btn-lg .btn-group-lg > .btn, .btn-group-lg > .btn-lg .btn`` to ``.btn-lg .caret, .btn-group-lg > .btn .caret``. Another changed from ``.cal-days a, .cal-days div, .cal-days a, .cal-days div`` to ``.cal-days a, .cal-days div``.
* Some pseudo-class selector issues seem to be fixed. For example, ``table.dataTable.display tbody tr:hover.selected`` changed to ``table.dataTable.display tbody tr.selected:hover``.
* ``@media`` selectors that don't contain anything apart from comments no longer appear.

**Comment by LaurentGoderre** [comment] 2015-03-27 13:54
The seledctor changing is the biggest risk here. The charset issue is weird because I thought I fixed that

**Comment by EricDunsworth** [comment] 2015-03-27 15:37
@LaurentGoderre Could it be that the way in which selectors get generated has just been optimized? My last comment's second selector example shows that in 0.14.1, ``.cal-days a, .cal-days div`` was being repeated twice for no reason, whereas in 0.18.1 the repetition went away. I don't know if every selector difference is an improvement compared to before, though...

In any case, sticking with 0.14.1 is problematic since it's preventing contributors that are on Windows from fully setting up the build system. No one on Windows can generate WET's CSS as things stand. I wasn't able to get 0.14.1 working on my home computer either, so this isn't proxy-related.

**Comment by LaurentGoderre** [comment] 2015-03-27 15:48
Actually I can, it works fine for me but anyways, I<m not saying not going, I just have to evaluate the impact this has.

**Comment by EricDunsworth** [comment] 2015-03-27 15:55
Ok.

Btw it's kind of weird... I was able to properly build on my workstation as recently as last Friday afternoon with my pre-existing build system setup. It was only after I tried "resetting" my build system (uninstalling node.js, removing /lib/, /node_modules/, etc folders then reinitializing everything) that I was no longer able to set things up from scratch. Maybe one of grunt-sass' dependencies got a new version in recent weeks, resulting in people with already-working Windows build systems being unaffected... but people trying to setup from scratch being SOL.

**Comment by LaurentGoderre** [comment] 2015-03-27 18:10
Yeah. We had an issue like that with another dependency earlier this week too. Dependency hell... Although it's much better than it was

**Comment by EricDunsworth** [comment] 2015-03-27 18:43
*goes back to Apache Ant :P ;)*

**Comment by EricDunsworth** [comment] 2015-03-30 16:11
@zachfalsetto @thomasgohard Btw this issue is likely going to cause a whole lot of headaches for first-time WET contributors that use Windows at tomorrow's code sprint.

**Comment by LaurentGoderre** [comment] 2015-03-30 16:39
Tomorrow's code sprint is going to be mostly about learning git and about Java.

**Comment by LaurentGoderre** [comment] 2015-03-30 18:35
The first selector I encountered is the this:

Before:
```css
.wb-tabs > details[open] > summary, .wb-tabs > .tabpanels > details[open] > summary {
```

After:
```css
.wb-tabs > details[open] > summary {
```

This is sure to break something. This change is not as simple as it looks

**Comment by LaurentGoderre** [comment] 2015-03-30 18:48
We can't upgrade to the mentioned version of grunt-sass because of a regression that would very negatively impact our CSS. Please post your `npm-debug.log` file to see if we can fix your setup with the current version. Note that the issue is probably specific to your environment because I am unable to reproduce in Windows 7 in a fresh clone.

**Comment by EricDunsworth** [comment] 2015-03-30 19:54
It's happening on both my home and work Windows 7 x64 environments, but ok.

Gist is blocked in our department's network, so I'll post my npm-debug.log file(s) later tonight.

**Comment by LaurentGoderre** [comment] 2015-03-30 19:57
With node v0.10 or v0.12?

**Comment by EricDunsworth** [comment] 2015-03-30 19:58
v0.12 on both OSes.

**Comment by EricDunsworth** [comment] 2015-03-30 20:16
Specifically, I'm on 0.12.0.... Looks like 0.12.1 is out now.

**Comment by LaurentGoderre** [comment] 2015-03-30 20:26
I can reproduce with the latest node. It's probably best for WET developers to stay on the latest v0.10 until the regression is fixed, compiling libsass in Windows is not something easily done.

http://nodejs.org/dist/v0.10.38/x64/node-v0.10.38-x64.msi
http://nodejs.org/dist/v0.10.38/node-v0.10.38-x86.msi

**Comment by EricDunsworth** [comment] 2015-03-30 20:47
I was able to get the build system working with a fresh install of 0.10.38 working on my end too, so I'm happy now :).

**Comment by stephenbe** [comment] 2015-03-30 23:40
@LaurentGoderre I downgraded my node version and it seems to be working again.

**Comment by LaurentGoderre** [comment] 2015-05-28 13:05
Can we close this?

**Comment by rlambert27** [comment] 2015-05-28 13:30
Ok for me :-)

**Closed** 2015-05-28 13:38 UTC
