### ISSUE TITLE
browsers versions supported 

### ISSUE THREAD

**Issue by Ting-ChongMa** [wet-boew/wet-boew#6644] opened 2015-03-25 18:12 UTC
Which browsers and versions are or are not supported by the WET framework v4.0.9 and v4.0.12?
I am looking for information such as "End of support for IE8 at Summer/Fall 2014" (http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html).

**Comment by LaurentGoderre** [comment] 2015-03-25 18:24
Duplicate of #6387

**Closed by LaurentGoderre** 2015-03-25 18:24 UTC
