### ISSUE TITLE
Found new error when validating with validator.w3.org

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew#7291] opened 2015-12-11 15:34 UTC
try this : 
https://validator.w3.org/nu/?useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&doc=http%3A%2F%2Fwet-boew.github.io%2Fv4.0-ci%2Ftheme%2Fcontent-secmenu-en.html
```html
Error: Bad value search for attribute role on element form.

From line 70, column 1; to line 70, column 87

arch</h2>↩<form action="https://google.ca/search" method="get" role="search" class="form-inline">↩<div 
```

**Comment by LaurentGoderre** [comment] 2015-12-11 15:59
My best is that it's an issue with the validator....The aria spec specifically says you should use search
http://www.w3.org/TR/wai-aria/roles#form

**Comment by nschonni** [comment] 2015-12-11 16:48
There has been a bunch of discussion on the accessibility lists about this. Having the role=search directly on a form is currently an error, and you need to put the role on a container object. I guess it's probably because the search role probably clobbers the "form" role for AT.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Laurent GoderreSent: Friday, December 11, 2015 10:59 AMTo: wet-boew/wet-boewReply To: wet-boew/wet-boewSubject: Re: [wet-boew] Found new error when validating with validator.w3.org (#7291)My best is that it's an issue with the validator....The aria spec specifically says you should use search
http://www.w3.org/TR/wai-aria/roles#form

—Reply to this email directly or view it on GitHub.

**Comment by pjackson28** [comment] 2015-12-11 17:44
@nschonni Until that is clarified in the WAI-ARIA spec (still not in the latest 1.1 working draft), then the validator should not be identifying it as an error. The validator is getting bad for having stricter interpretations than the spec permits. For instance a common issue is the validatoris  interpreting "DOM descendant" as meaning "child" for the owned element definition when the DOM specification states: "A descendant node of any node A is any node below A in a tree model, where "below" means "away from the root." (http://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/glossary.html#dt-descendant).

**Comment by pjackson28** [comment] 2015-12-11 17:47
Should also clarify that the same spec definition of child is "A child is an immediate descendant node of a node." So the validator's interpretation that child = descendant is incorrect where the correct interpretation would be that a child is a type of descendant. Hopefully the validator will get better at aligning with the specs (or if the issue is with the wording in spec, then the spec addresses the wording issues).

**Comment by nschonni** [comment] 2015-12-16 01:59
Applicable discussion thread https://github.com/w3c/wcag/issues/113

**Comment by stevefaulkner** [comment] 2015-12-16 11:07
bug on spec fixed re role=search https://github.com/w3c/html-aria/issues/18 and validator bug filed

**Comment by LaurentGoderre** [comment] 2015-12-16 13:52
@stevefaulkner great to hear from you! Thanks!

**Comment by hsrudnicki** [comment] 2016-01-29 15:56
Based on last comments, can be this issue closed as resolved/fixed or if otherwise?  Either way, please update again this issue's status, thank you

**Closed** 2016-01-29 18:51 UTC

**Comment by EricDunsworth** [comment] 2016-02-01 19:53
@hsrudnicki @LaurentGoderre Should this issue remain open until the NU validator stops producing that error?

Btw I've followed up in #validator/validator#193 about the validator itself.

**Comment by LaurentGoderre** [comment] 2016-02-02 14:07
I don't think so because it's not an actual issue on our side. If someone opens a new issue, we will close and reference this issues
