### ISSUE TITLE
Horiztonal scroll on tabs with inner grids

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/wet-boew#6679] opened 2015-04-13 01:44 UTC
In WET4.0.12, the ` overflow-x: auto;` causes a horizontal scrolling bar to appear with you put a `.row` and inside the tabs
```
.wb-tabs [role="tabpanel"] {
    overflow-x: auto;
    position: relative;
    z-index: 1;
}
```
When `overflow-x: auto` is removed, then it goes away.  This was not a problem in WET4.0.0 but we just upgraded to WET4.0.12 and the horizontal scroll is there.  The scroll only move a few pixels so it's not actually doing anything.

```

**Comment by RobJohnston** [comment] 2015-04-13 12:08
This sounds so much like #6540 .

**Comment by pjackson28** [comment] 2015-04-13 13:26
@cfarquharson That's because you are using row improperly, making that element larger than the parent container (due to negative margins and padding). In v4.0.0, it was incorrectly clipping the overflowing element so you wouldn't notice this issue whereas we fixed that in later versions so the underlying issue is now visible. Note that clipping in this case is bad from an accessibility standpoint. As covered in #6540, you need to fix your content so it does not overflow the parent container (triggering the scrollbars). You can find solutions in the other issue.

Closing as duplicate of #6540.

**Closed by pjackson28** 2015-04-13 13:26 UTC
Labels: Close: Duplicate, External: Web Standards Office
