### ISSUE TITLE
WET3 to WET4 classes documentation?

### ISSUE THREAD

**Issue by ashzadeh** [wet-boew/wet-boew#6511] opened 2015-02-10 18:51 UTC
Hello,

We're looking into creating a script to covert WET3 classes to WET4 classes where it's applicable (i.e. span-x to col-md-x).

Is there documentation for the style changes? I'm hoping that I don't have to go through each style guide and look for the differences.

Thanks for the help!
Ash

**Comment by LaurentGoderre** [comment] 2015-02-10 19:21
Duplicate of #5729

**Closed** 2015-02-10 19:22 UTC
Labels: Close: Duplicate
