### ISSUE TITLE
Overlay: 

### ISSUE THREAD

**Issue by IanYangCa** [wet-boew/wet-boew#9174] opened 2021-09-17 14:32 UTC
I use gcweb/v4_0_39/cdts/compiled/wet-en.js, <section id="mid-screen" class="wb-overlay modal-content overlay-def wb-popup-mid overlay-bg" aria-hidden="true" style="height:260px;width:300px;">

The "Close" button always append to my custom buttons. How can I disable it append to my buttons?[](url)

**Comment by thekodester** [comment] 2021-09-17 23:38
Duplicate of #9173

**Closed** 2021-09-22 17:35 UTC
Labels: Close: Duplicate
