### ISSUE TITLE
Form validation data-rule-lettersonly and data-rule-letterswithbasicpunc

### ISSUE THREAD

**Issue by gilles-leblanc** [wet-boew/wet-boew#8165] opened 2017-10-04 18:59 UTC
In the form validation / specialized validation, the following rules: `data-rule-lettersonly` and `data-rule-letterswithbasicpunc` both do not support diacritics (accented caracters).

Which means we can't use them on any forms which can accept French input, but I have requirements for the sites I create to be bilingual. 

Accented caracters are not only used in people's first and last names but also in place names (cities, provinces, etc.) and most values commonly inputed in form fields.

**Comment by RobJohnston** [comment] 2017-10-04 21:45
Duplicate of https://github.com/wet-boew/wet-boew/issues/7592.  Work-around provided too.

**Comment by gilles-leblanc** [comment] 2017-10-05 12:14
Ok thanks for the link I will try this.

It would be very nice if this was mentionned in the documentation. I don't know if I am using the correct documentation source but I have been given this adress: http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html and under Forms validation http://wet-boew.github.io/v4.0-ci/docs/ref/formvalid/formvalid-en.html there is no mention of how to deal with accents much less of  `data-rule-pattern`. It's also not in the link to jQuery Validation plugin documentation provided on the page. 

If I search the jquery validation page for `pattern` I get `jQuery.validator.addMethod` which does not seem to fit in the same style as the `data-rule-` validations. Searching for `data-rule` does not yield anything either. Maybe the documentation is not for the same version as the WET is using or maybe the `data-rule` are provided by the WET itself...

**Closed** 2017-10-05 15:08 UTC
