### ISSUE TITLE
Tables - has anyone got a working implementation that they are willing to share to grab json from external sources

### ISSUE THREAD

**Issue by TimCadieux** [wet-boew/wet-boew#7824] opened 2016-12-21 22:37 UTC
Wow, so from someone who's only ever done business layer in c#, i am truly frustrated.  I can't tell if I'm implementing the table wrong, or maybe its not properly initialized or there's some kind of page life cycle in play here.

I need to pull json files from another dept on the fly and manipulate the data, such as removing duplicates and such.  Up until now I have been getting the data, fixing it then appending it.  This works in some instances but I can't seem to get it to work all the time.  The documentation also point to the datatables documentation but when i try any of that on my pages, it tells me datatables is not a function.

I would need to be able to get the data and fill the table on document.ready and also in some instances based on an event, such as someone having loaded this tab or from a dropdown_change.

If anyone would be willing to help walk me through this, it would be super appreciated!!!!!!!!!!!!!!!!

**Comment by nschonni** [comment] 2016-12-22 04:24
To be able to use the DataTables API directly, you'll need to what for the plugin to load https://wet-boew.github.io/wet-boew/docs/ref/tables/tables-en.html describes the `wb-ready.wb-tables` or `wb-ready.wb` events that you might need to wrap your code in. I think @kodecount might have already provided that advice in another thread.

**Comment by kodecount** [comment] 2016-12-22 12:17
I'm don't recall doing so. But I did have a button function which populated a table of request with JSON then created the tables here: https://github.com/wet-boew/wet-boew/issues/7436#issuecomment-251477543

**Comment by kodecount** [comment] 2016-12-22 12:51
Try something like this:

JavaScript (make sure it under your WET script):
```javascript
wb.doc.on("wb-ready.wb", function() {
	var datatable = $("#datatable").DataTable(), url = "https://www.pinterest.com/healthycdns/drug-prevention.rss", limit, columns = [];
	$.ajax({
		type: 'GET',
		url: 'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feed%20where%20url%20%3D%20\'' + encodeURIComponent(decodeURIComponent(url)) + '\'%20limit%20' + (limit ? limit : 5) + '&format=json',
		dataType: 'json',
		success: function(data) {
			columns.push({
				"mDataProp": "title",
				sTitle: "Title"
			});
			columns.push({
				"mDataProp": "guid",
				sTitle: "Guid"
			});
		}
	}).done(function(data) {
		datatable.destroy();
		$("#datatable").empty();
		datatable = $("#datatable").dataTable({
			"aoColumns": columns,
			"aaData": data.query.results.item
		});
	});
});
```
HTML:
```html
<h1 style="text-align:center;">Pinterest Feed Table Creater</h1>
<table class="wb-tables table table-striped table-hover" id="datatable">
	<thead>
		<tr>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td></td>
		</tr>
	</tbody>
</table>
```

**Comment by LaurentGoderre** [comment] 2016-12-22 12:56
@kodecount, you don't need that much code. I'm pretty usre you can leverage the datatable events to manipulate data.

@TimCadieux the datatable plugin can be intimidating but it's very powerful. If you leverage their event, then you won't get the `DataTable doesn't exist` error anymore.

**Comment by kodecount** [comment] 2016-12-22 12:59
Maybe not but need wants to change the JSON data before populating the table.

**Comment by LaurentGoderre** [comment] 2016-12-22 12:59
From this page: https://datatables.net/reference/event/ you can use the xhr event (https://datatables.net/reference/event/xhr)

You can do this:

```
$(document).on("xhr", ".wb-tables", function(e, settings, json, xhr) {
    Manipulate JSON here
});
```

**Comment by LaurentGoderre** [comment] 2016-12-22 13:00
@kodecount check theexample I just posted. You can create a totally new JSON object from the new one before datatable renders it. It's quite powerful

**Comment by kodecount** [comment] 2016-12-22 13:03
Yes. That is another option.

**Comment by LaurentGoderre** [comment] 2016-12-22 13:07
This option has the advantage of not doing DOM operation such as destroy and empty because it processes the data before any of the rendering takes place.

**Comment by TimCadieux** [comment] 2016-12-22 13:24
@Laurent Goderre, could you perhaps expand on the example a little, how it
would be used in a real situation?

Something like (cobbled together from datatables web events page)

<button id="populate_data" class="btn btn-info mrgn-tp-md"
type="button">Populate Data</button>


would it be?

$('#populate_data').click(function(tablename){

$('#' + tablename).on("xhr", ".wb-tables", function(e, settings, json, xhr) {

    json = FunctionThatGrabsMyJSONData();
});

.dataTable( {
        ajax: "data.json"
    } );

}

**Comment by kodecount** [comment] 2016-12-22 14:33
How are you getting data? Is it a file or URL?

**Comment by TimCadieux** [comment] 2016-12-22 14:35
a json file from another dept, therefore using an ajax call with callback

**Comment by LaurentGoderre** [comment] 2016-12-22 14:38
@TimCadieux is the file publicly accessible? I could create a quick prototype for you

**Comment by TimCadieux** [comment] 2016-12-22 14:39
unfortunately it is not...perhaps this ? https://jsonplaceholder.typicode.com/

**Comment by LaurentGoderre** [comment] 2016-12-22 14:48
Is the data protected or can you share?

**Comment by TimCadieux** [comment] 2016-12-22 14:53
Shall i paste it here?

**Comment by kodecount** [comment] 2016-12-22 14:54
You can drop files it your comments?

**Comment by TimCadieux** [comment] 2016-12-22 14:56
Ah nice...had to change the ext as json is not supported
[queryByRating.txt](https://github.com/wet-boew/wet-boew/files/669005/queryByRating.txt)

**Comment by kodecount** [comment] 2016-12-22 15:52
@LaurentGoderre Their is a bug that would need to be fixed before his JSON would work if he is using:
```
"data": [
{
...
"publication": {
  "id": 1538,
  "name": "Ottawa Citizen.com"
},
...
}
]
```
at [Line 121 in table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L121) need to `sData = sData.toString();` before doing `sData.replace(...)`.

Also at [Line 133 in table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L133)  need to `data = data.toString();` before doing `data.replace(...)`.

This bug appears if using:

```html
<table class="wb-tables table table-striped table-hover" id="datatable" aria-live="polite" data-wb-tables='{
"bDeferRender": true,
"ajaxSource": "ajax/report.json",
 "columns": [
 		{ "data": "id", "className": "report-id h4" },
		{ "data": "title", "className": "report-title" },
		{ "data": "byline", "className": "report-byline" },
		{ "data": "body", "className": "report-body" },
		{ "data": "section", "className": "report-section" },
		{ "data": "categories[,].id", "className": "report-categories-id" },
		{ "data": "categories[,].name", "className": "report-categories-name" },
		{ "data": "categories[,].keywords[,].id", "className": "report-categories-keywords-id" },
		{ "data": "categories[,].keywords[,].hits", "className": "report-categories-keywords-hits" },
		{ "data": "publication.id", "className": "publication-id" },
		{ "data": "publication.name", "className": "publication-name" }
	]}'/>
```

**Comment by LaurentGoderre** [comment] 2016-12-22 16:00
@TimCadieux I'm very busy before leaving for the holiday. Is it ok if I make the prototype in early January?

**Comment by TimCadieux** [comment] 2016-12-22 16:08
Sure, any help is appreciated, I can work on something else instead

**Comment by TimCadieux** [comment] 2016-12-22 16:09
The goal would be to manipulate the data and return something a little
simpler, perhaps that helps?

**Comment by LaurentGoderre** [comment] 2016-12-22 16:20
I know exactly how to do it, I just wanted to use something as close to your data as possible. I have don't similar stuff in many of my projects.

**Comment by TimCadieux** [comment] 2016-12-22 16:23
ok, i'll shutup now :-)

**Comment by LaurentGoderre** [comment] 2016-12-22 16:29
Oh no, lol. I was just trying to reassure you that it can be done and it shouldn;t take me too long when I come back ;)

**Comment by TimCadieux** [comment] 2016-12-22 16:31
I was just teasing :-)

**Comment by kodecount** [comment] 2016-12-22 16:33
If your using this HTML:

```html
<table class="wb-tables table table-striped table-hover" id="datatable" aria-live="polite" data-wb-tables='{
"bDeferRender": true,
"ajaxSource": "ajax/report.json",
"columns": [
  { "data": "id", "className": "report-id h4" },
  { "data": "title", "className": "report-title" },
  { "data": "byline", "className": "report-byline" },
  { "data": "body", "className": "report-body" },
  { "data": "section", "className": "report-section" }
]}'/>
  <thead>
	<tr>
	  <th>Id</th>
		<th>Title</th>
		<th>Byline</th>
		<th>Body</th>
		<th>Section</th>
	</tr>
  </thead>
	<tfoot>
	<tr>
		<th>Id</th>
		<th>Title</th>
		<th>Byline</th>
		<th>Body</th>
		<th>Section</th>
	</tr>
  </tfoot>
</table>
```

You could do something like:

```javascript
<script>
$( document ).on("xhr.dt", ".wb-tables", function(e, settings, json, xhr) {
	var data = json.data,
	dataArr = data.map(function(item){ return item.title });
	dataArr.some(function(item, idx){
			var isDuplicate = dataArr.indexOf(item, idx + 1) !== -1;
	    if ( isDuplicate ) {
				data = removeDuplicate(data, item);
			}
	});
	json.data = data;
});

function removeDuplicate(data, title) {
	$.each(data, function(i, el){
		if (this.title == title){
			data.splice(i, 1);
			return false;
		}
	});
	return data;
}
</script>
```

**Comment by LaurentGoderre** [comment] 2016-12-22 16:39
@kodecount seems pretty close. Although `$.each` is really not efficient for this kind of thing

**Comment by kodecount** [comment] 2016-12-22 16:40
Imagine their is better way (always is with JavaScript). It just what I know.

**Comment by LaurentGoderre** [comment] 2016-12-22 16:49
Yeah! The structure seems bang on!

**Comment by kodecount** [comment] 2016-12-22 17:07
@LaurentGoderre Also think I should open new issue about the bug or do you think your gonna work on in new year?

**Comment by LaurentGoderre** [comment] 2016-12-22 17:13
Well, I'm not sure what the bug is exactly but open a report and include what the expect behavior is and how it diverges from the behavior. Maybe someone else has some insight as to why it was coded a certain way. We can confirm the bug in the new year.

**Comment by kodecount** [comment] 2016-12-22 17:14
The bug is `"id": 1234` this is a integer but the WET code assumes it a string and tries to do a `.replace`

**Comment by LaurentGoderre** [comment] 2016-12-22 17:35
Oh wow. That's quite an edge case. Good find

**Comment by kodecount** [comment] 2016-12-22 17:42
@TimCadieux I've added a update to my post to show how you could create links for the category data. It not the best way especially if it really large (the json file) but could get you started.

**Comment by kodecount** [comment] 2016-12-22 17:49
@TimCadieux I've added a update to my post to show how you could create links for the category data. It not the best way especially if it really large (the json file) but could get you started.

**Comment by TimCadieux** [comment] 2016-12-22 18:08
Wow, that's really interesting....I'll look into it ,,thx!!

**Comment by kodecount** [comment] 2016-12-22 18:10
What I mean is what @LaurentGoderre said about `$.each` it good, but no the best if it gets really large. I'm not sure of better performance options as I never really dealt with this.

**Comment by TimCadieux** [comment] 2017-01-04 17:24
Ok, so i'm still fighting with this.

If I place this code inside a tab panel, the search textbox loses focus after each letter...if you comment out the tab panel, everything works as expected.

    `
    <div class="wb-tabs ignore-session">
        <div class="tabpanels">
            <details id="Test1">
                <summary>Test 1</summary>
                <table class="wb-tables table table-striped table-hover" id="datatable">
                    <thead>
                        <tr>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                        </tr>
                    </tbody>
                </table>

            </details>
            <details id="Test2">
                <summary>Test 2</summary>

            </details>
        </div>
    </div>
    <script>
        wb.doc.on("wb-ready.wb", function () {
            var datatable = $("#datatable").DataTable(), limit, columns = [];
            $.ajax({
                type: 'GET',
                url: '/assets/js/application/newsdesk/lederoit.json',
                dataType: 'json',
                success: function (data) {

                    // THEN CREATE COLUMNS TABLE
                    columns.push({
                        "mDataProp": "title", // this is the data for that header
                        sTitle: "title" // this is header
                    });
                    columns.push({
                        "mDataProp": "publication.name",
                        sTitle: "Source"
                    });
                }
            }).done(function (data) {
                datatable.destroy(); // destroy initialize table
                $("#datatable").empty(); // reinitialize table as empty
                // now populate table with data
                datatable = $("#datatable").dataTable({
                    "aoColumns": columns,
                    "aaData": data.articles
                });
            });
        });

    </script>

`

**Comment by kodecount** [comment] 2017-01-04 17:29
There is a few knows issue https://github.com/wet-boew/wet-boew/issues/7385 or https://github.com/wet-boew/wet-boew/issues/7516

**Comment by TimCadieux** [comment] 2017-01-04 17:45
Right, the removeClass trick worked, thx

**Comment by TimCadieux** [comment] 2017-01-05 13:31
Argh, the above code i'm using is still suffering from the searchbox losing focus after typing each letter..

**Comment by kodecount** [comment] 2017-01-05 13:38
Yes as example in the issue when the page is resized the Equalizer plugin kicks in.

**Comment by TimCadieux** [comment] 2017-01-05 13:45
Ok, I fixed that by placing the removeclass code in the wb-ready after the code that populates the table has run

**Comment by TimCadieux** [comment] 2017-02-01 18:59
@LaurentGoderre, I didn't want to bug you, but you suggested you'd be able to share a demo of the proper way to do this sometime after Christmas?

**Comment by LaurentGoderre** [comment] 2017-02-01 20:08
Yeah, sorry it's a busy time here with the censur. Hopefully I can give you the example next week

**Comment by TimCadieux** [comment] 2017-02-02 16:27
thx

**Comment by TimCadieux** [comment] 2017-02-22 19:32
Not to be too annoying but can no one share a working example?  I've attempted to use the code  @kodecount posted above but the path to the json file is dynamic and so "ajaxSource": "ajax/report.json", does not work for me...

my path requires me to look at date and other fields on the form so that I can then send it off to a function to build my query like


   `

    var Page_size = ((p_size !== null) ? '&page_size=' + p_size : "");

    var Sort = "&sort_field=publication_date&sort_order=Desc";

    var drange = ((dateRange !== null) ? '&date_range=' + dateRange : "");

    var url = api + query + drange + Page_size + Sort + '&format=json' + app_key;
      
    return url;
`

**Comment by kodecount** [comment] 2017-02-26 03:42
Not sure if WET has any method for dynamic URL with data-tables. Don't quote me on it but I think @duboisp was working on something.

Either way I have this: http://kodecount.ca/demos/tables/

**Comment by TimCadieux** [comment] 2017-02-28 00:35
Sigh. ok. so still trying this.... what im doing is loading a dummy local json file, just to get Xhr.dt to fire.
Then i wanted to overwrite that data with my own.
Everything works except that if I overwrite json.data inside my callback function it gets ignored.
if I load a var with data and overwrite json.data outside my Callback, it works...
ideas?

`     

    $(document).on("Xhr.dt", ".wb-tables", function (e, settings, json, xhr) {

    //goal is to overwrite the .wb-tables json.data with data from the db or json in this case

          var _rangeData;

            GetData()
            .then(
                function (data) {
                    json.data = data; //<- This is populated with an array of data...it doesn't load...
                });
                    var d = [
                    {
                        "title": "This is a test"
                    }];
            json.data = d; // <- This does work....
        });
`

**Comment by kodecount** [comment] 2017-02-28 13:01
Hey I was able to do it like this:

```javascript
<script>

var pstId = GetURLParameter( "pstId" ),
	link = 'https://jsonplaceholder.typicode.com/' + ( ( pstId ) ? ( 'posts?id=' + pstId ) : 'posts' );

$.ajax( {
	url: link,
	method: 'GET',
	dataType: 'json',
	success: function( data ) {},
	error: function ( textStatus, errorThrown ) {}
} ).then( function( data ) {
	passData( data );
} );

function passData( data ) {
	$( document ).on( "xhr.dt", ".wb-tables", function( e, settings, json, xhr ) {
		json.data = data;
	} );
}

// http://www.jquerybyexample.net/2012/06/get-url-parameters-using-jquery.html
function GetURLParameter( sParam ) {
  var sPageURL = window.location.search.substring( 1 );
  var sURLVariables = sPageURL.split( '&' );
  for ( var i = 0; i < sURLVariables.length; i++ ) {
    var sParameterName = sURLVariables[ i ].split( '=' );
    if ( sParameterName[ 0 ] === sParam ) {
      return sParameterName[ 1 ];
    }
  }
}

</script>
```
The issue is with AJAX are asynchronous and you can't see the data outside of it's method.

**Comment by TimCadieux** [comment] 2017-02-28 14:10
unfortunately, using your example almost exactly, the table is blank...if I comment the Ajax call, then it populates from the JSON temp file.

I wonder if it has to do with the layout of the data in the new file?
`                <table id="dataTable" class="wb-tables table table-striped table-hover" aria-live="polite" data-wb-tables='{
                "bDeferRender": true,
                "ajaxSource": "/assets/json/temp.json",
                 "columns": [
                    { "data": "title", "className": "nws-tbl-ttl h4" }
                  ]}'>
                    <thead>
                        <tr>
                            <th>Title</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Title</th>
                        </tr>
                    </tfoot>
                </table>`
`    
    var link = 'https://jsonplaceholder.typicode.com/posts/1';

        $.ajax({
            url: link,
            method: 'GET',
            dataType: 'json',
            success: function (data) { },
            error: function (textStatus, errorThrown) { }
        }).then(function (data) {
            passData(data);
        });

        function passData(data) {
            $(document).on("xhr.dt", ".wb-tables", function (e, settings, json, xhr) {
                json.data = data;
            });
        }`
{
temp.json
  "data": [
    {
      "title": "<a href=\"http://news.gc.ca/web/index-en.do\">Biomass Program Continues to Support Transition to Renewable Energy in Manitoba</a>"
    }
  ]
}

**Comment by kodecount** [comment] 2017-02-28 14:13
I believe it has to be with `https://jsonplaceholder.typicode.com/posts/1` I had to use `https://jsonplaceholder.typicode.com/posts?id1` because the example is using `GET`

**Comment by TimCadieux** [comment] 2017-02-28 14:15
Thx, that worked...!  Now to see if I can get mine to work!!

**Comment by TimCadieux** [comment] 2017-02-28 15:27
I feel like I'm so close...I've used the layout of my page...but the xhr event gets skipped?

`    $(document).ready(function () {
    GetDataTable();
});
    GetDataTable: function () {

        GetData()
        .then(
        function passData(data) {
            var q = $.Deferred();
            $(document).on("xhr.dt", ".wb-tables", function (e, settings, json, xhr) {  <---THIS EVENT IS SKIPPED
                console.log(json);
                json.aaData = data;
                q.resolve(s);
            });
            return q.promise();
        });

        function GetData() {
            var q = $.Deferred();

            data.GetCustomDateRangeData(myqueryere, function (data) {
                var s = [];
                s = js.utils.RemoveDups(data.articles);

                q.resolve(s);
            });

            return q.promise();
        }
    }
`

**Comment by kodecount** [comment] 2017-02-28 15:39
I think `$(document).on("xhr.dt", ".wb-tables", function (e, settings, json, xhr){})` would be called before `$(document).ready(function () {})`. Just my guess.

**Comment by LaurentGoderre** [comment] 2017-02-28 15:39
The event handler should be outside any function, otherwise it might not get attached at the right time

**Comment by TimCadieux** [comment] 2017-02-28 16:13
The below code runs all the way through but again, the table data does not get overridden.  I also tried to set json.data to null in case it was maintaining that data but it didn't make any difference.

    $(document).on("xhr.dt", ".wb-tables", function (e, settings, json, xhr) {
    page.GetDataTable()
    .then(
        function passData(data) {
            var q = $.Deferred();
            json.aaData = data;
            q.resolve();
            return q.promise();
        });
    });

**Comment by TimCadieux** [comment] 2017-02-28 16:23
Further testing:

    page.GetDataTable()
    .then(
    function passData(data) {
        var q = $.Deferred();
        console.log(json);
        console.log(data);
        json.aaData = [  // DOES not OVERWRITE
                        {
                            "title": "Test 1"
                        },
                        {
                            "title": "Test 2"
                        },
                    ]

        q.resolve();
        return q.promise();
    });
      json.aaData = [  // DOES OVERWRITE
                        {
                            "title": "Test 1"
                        },
                        {
                            "title": "Test 2"
                        },
                    ]

**Comment by kodecount** [comment] 2017-02-28 16:28
This might help: http://stackoverflow.com/questions/5105731/convert-json-array-to-aadata-format

**Comment by TimCadieux** [comment] 2017-02-28 16:38
I think my testing above is showing that the data is accepted in when outside the function but for some reason when inside the function, it accepts it but then ignores it?

**Comment by LaurentGoderre** [comment] 2017-02-28 16:51
By using a promise, you are defering the processing of the data after datatable is finished executing

**Comment by TimCadieux** [comment] 2017-02-28 17:03
Argh...any suggestions are appreciated.

**Comment by LaurentGoderre** [comment] 2017-02-28 17:34
Why are you using queues anyways?

You could use the following ` data-wb-tables='{"ajax": {"url": "test.json", "dataSrc": "arti"}}'` and

```js
<script>
wb.doc.on('xhr.dt', function(e, settings, json){
	var articles = json.articles,
		articlesLength = articles.length,
		a, article;

	for(a = 0; a < articlesLength; a++) {
		article = articles[a]

		json.articles[a] = [
			article.title,
			article.byline,
			article.section
		]
	}
})
</script>
```

**Comment by TimCadieux** [comment] 2017-02-28 18:21
All i've ever wanted to do...is simply make the location from which the table is populated, dynamic..
ie
var category = GetCategoryfromdropdown;
var DateRange - GetDaternagefromCalendar;

"ajaxSource": myapi + DateRange + Category +  apiKey + apiUSER

**Comment by LaurentGoderre** [comment] 2017-02-28 19:26
I thought you tried to manipulate the data. IF you want it dynamic then you would need to trigger the loading of the table dynamically.

**Comment by kodecount** [comment] 2017-02-28 19:48
If can simple do:

HTML:
```html
<table id="datatable" class="table table-hover table-stripped wb-tables" data-wb-tables='{"destroy": true, "bDeferRender": true, "ajax": {"url": "https://jsonplaceholder.typicode.com/posts/", "dataSrc": ""},
"columns": [
  { "data": "userId", "className": "posts-userId" },
  { "data": "id", "className": "posts-id" },
  { "data": "title", "className": "posts-title" },
  { "data": "body", "className": "posts-body" }
]}'>
	<thead>
		<tr>
			<th>User Id</th>
			<th>Id</th>
			<th>Title</th>
			<th>Body</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>
```

JavaScript:
```javascript
<script>

var pstId = GetURLParameter( "pstId" );
if ( pstId ) {
	var $table = $( "#datatable" ), link = 'https://jsonplaceholder.typicode.com/posts?id=' + pstId;
	$table.attr( "class", "table table-hover table-stripped wb-tables" );
	$table.attr( "data-wb-tables", '{"destroy": true, "bDeferRender": true, "ajax": {"url": "' + link + '", "dataSrc": ""}, "columns": [{ "data": "userId", "className": "posts-userId" },{ "data": "id", "className": "posts-id" },{ "data": "title", "className": "posts-title" },{ "data": "body", "className": "posts-body" }]}' );
	$table.trigger( "wb-init.wb-tables" );
}

// http://www.jquerybyexample.net/2012/06/get-url-parameters-using-jquery.html
function GetURLParameter( sParam ) {
	var sPageURL = window.location.search.substring( 1 );
	var sURLVariables = sPageURL.split( '&' );
	for ( var i = 0; i < sURLVariables.length; i++ ) {
		var sParameterName = sURLVariables[ i ].split( '=' );
		if ( sParameterName[ 0 ] === sParam ) {
			return sParameterName[ 1 ];
		}
	}
}

</script>
```

**Comment by kodecount** [comment] 2017-02-28 19:49
'"destroy": true' allows you to trigger table without it screaming initialization issues.

**Comment by kodecount** [comment] 2017-02-28 19:54
When you do solve your issue I think it best to close this issue as it'll probably confuse someone more then help them.

**Comment by TimCadieux** [comment] 2017-02-28 20:34
Doesn't .Destroy also remove anything added in the wb.ready event?  I tried adding buttons but they were removed when I used destroy.

@LaurentGoderre - I want to do both. Once I have brought imln the data from a dynamic path, I need to remove duplicates and do other such but it appears I could use xhr even to do that.

I also need to be able to use the Export to excel button.

It's important that I get this right as it'll be the template for all the pages.on our site.

**Comment by kodecount** [comment] 2017-02-28 22:38
For excel button see https://github.com/wet-boew/wet-boew/issues/7599#issuecomment-259236714

**Comment by kodecount** [comment] 2017-03-01 00:20
Please see my updated example: http://kodecount.ca/demos/tables/. Should have all your looking for.

**Comment by TimCadieux** [comment] 2017-03-01 00:22
@kodecount There is normally a button to look at your code, but no in this example?

**Comment by kodecount** [comment] 2017-03-01 00:23
I'll add a file with code. Too lazy to update at this moment. One second.

**Comment by kodecount** [comment] 2017-03-01 00:24
Here is the code:
[index.txt](https://github.com/wet-boew/wet-boew/files/809377/index.txt)

**Comment by kodecount** [comment] 2017-03-01 00:27
You may need to manually refresh page to see updates add some more content.

**Comment by TimCadieux** [comment] 2017-03-01 00:37
Well the page itself works great thanks!  No i need to see about converting it to my url!  I will report back!!

**Comment by TimCadieux** [comment] 2017-03-01 13:54
@kodecount Would you mind if i email you offline, i have 1-2 final questions..

**Comment by kodecount** [comment] 2017-03-01 14:00
Sure email on GitHub profile.

**Comment by kodecount** [comment] 2017-03-02 12:53
Sure, email on GitHub profile...

Here another demo from are discussion: https://kodecount.ca/demos/tables/reports

**Comment by kodecount** [comment] 2017-03-02 12:54
I think I got the date logic wrong, but if you do **Date From** as 2016-01-08 and **Date To** as 2016-01-01 it should filter the results.

**Closed** 2017-03-04 03:00 UTC
Labels: Help: Implementation, Plugin: Table enhancement (DataTables)
