### ISSUE TITLE
Geomap: 

### ISSUE THREAD

**Issue by swadcock** [wet-boew/wet-boew#8096] opened 2017-07-21 17:31 UTC
It appears that Geomap is built on top of OpenLayers v2.13  Are there any plans to update to OpenLayers v4.x?

**Comment by LaurentGoderre** [comment] 2017-07-21 18:34
@jvanulde is upgrading to v3

**Comment by nschonni** [comment] 2017-07-21 19:15
Duplicate of #7011

Although that one is talking about 3, and I guess 4 has been released since then.

**Closed by nschonni** 2017-07-21 19:15 UTC
