### ISSUE TITLE
polyfill (date picker) and ASP.NET UpdatePanel / date picker issues on ASP.NET UpdatePanel post back 

### ISSUE THREAD

**Issue by matvez** [wet-boew/wet-boew#6595] opened 2015-03-04 15:11 UTC
On post back a WET polyfill date picker inside an ASP.NET UpdatePanel is lost. The UpdatePanel reloads existing markup and destroys the existing polyfill. How can I reinstate the polyfill date picker inside that UpdatePanel on post back?  

```asp
<asp:Content ID="HeadContent" ContentPlaceHolderID="HeadContent" runat="server">
    <script type="text/javascript">
    </script>
</asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="server">
    <form id="MainForm" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <asp:TextBox ID="txtDate" runat="server" Text="" type="date" data-rule-dateISO="true">
</asp:TextBox>
                <asp:Button ID="btn" runat="server" OnClick="btn_Click" Text="Button" />
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</asp:Content>
```

**Comment by LaurentGoderre** [comment] 2015-03-04 16:04
What does your postback do? It sounds like it doesn't refresh the page but changes the DOM

**Comment by matvez** [comment] 2015-03-04 16:18
On button OnClick event will trigger a partial postback at UpdatePanel level. This loses the polyfill date picker icon.
        
        protected void btn_Click(object sender, EventArgs e)
        {
            //empty
        }

**Comment by LaurentGoderre** [comment] 2015-03-04 16:26
I would strongly recommend not using an UpdatePanel and rely on our Form Validation instead of the server side .NET way.

**Comment by matvez** [comment] 2015-03-04 17:23
The UpdatePanel is used for an internal web application and not Form Validation related. I use your polyfill datepicker for any date related input fields. The above code sample is a “bare-bones” code sample displaying the issue when using a polyfill datepicker with an UpdatePanel. On my side, the real issue arises when using ASP.NET controls (even complex aspx pages) containing lots of CRUD operations. Simply wrapping the whole asp control with an UpdatePanel will ease the work with partial page refresh. I am aware of the advantages/disadvantage in using UpdatePanels but they do coming in handy sometimes.

Currently I have two workarounds on the issue but hope I could find one for the WET polyfill....

1- Move datepicker outside of the UpdatePanel (sometimes not always not possible)
2- Recreate a datepicker every partial-postback completion with an UpdatePanel


Here is a bare-bones example demonstrating the polyfill issue with UpdatePanel:


<%@ Page Language="C#" MasterPageFile="~/Wet.Usability.Intranet.Master" AutoEventWireup="true" %>

<asp:Content ID="HeadContent" ContentPlaceHolderID="HeadContent" runat="server">
    <script type="text/javascript">
    </script>
</asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="server">
    <form id="MainForm" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <asp:TextBox ID="txtDate" runat="server" Text="" type="date" data-rule-dateISO="true"></asp:TextBox>
                <asp:Button ID="btn" runat="server" OnClick="btn_Click" Text="Button" />
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</asp:Content>

<script language="C#" runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        //Empty
    }
    protected void btn_Click(object sender, EventArgs e)
    {
        //Empty
    }
</script>

**Comment by LaurentGoderre** [comment] 2015-03-04 19:36
The problem is that by using the UpdatePanel, elements that are added to the page are not enhanced like the elements that exist when the page loads. You will need to create a script to re-enhance all elements after the UpdatePanel makes a change to the page.

**Comment by matvez** [comment] 2015-03-04 21:29
That is exactly what I want. Any ideas on how to create such a script to reload the polyfill? What do I need to call from the WET in order to reload that polyfill date picker?

**Comment by LaurentGoderre** [comment] 2015-03-04 21:48
```javascript
$( input[type=date] ).trigger( "wb-init.wb-date" );
```

**Comment by matvez** [comment] 2015-03-05 15:04
Thanks, I am try out to load the proper request. It should look something like this:

<%@ Page Language="C#" MasterPageFile="~/Wet.Usability.Intranet.Master" AutoEventWireup="true" %>

<asp:Content ID="HeadContent" ContentPlaceHolderID="HeadContent" runat="server">
    <script>
    </script>
</asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="server">
    <form id="MainForm" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <script>
                    Sys.Application.add_load(BindEvents);

                    function BindEvents() {
                        $(document).ready(function () {
                            alert("Test");
                            $("input[type=date]").trigger("wb-init.wb-date");
                        });
                    }
                </script>
                <asp:TextBox ID="txtDate" runat="server" Text="" type="date" data-rule-dateISO="true"></asp:TextBox>
                <asp:Button ID="btn" runat="server" OnClick="btn_Click" Text="Button" />
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</asp:Content>

<script language="C#" runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        //Empty
    }
    protected void btn_Click(object sender, EventArgs e)
    {
        //Empty
    }
</script>

**Comment by LaurentGoderre** [comment] 2015-03-05 16:27
You can't use the document ready because an ajax call does not re-trigger the ready event. You need to rely on the .NET event for the UpdatePanel, if any.

**Comment by LaurentGoderre** [comment] 2015-03-05 17:02
.NET out of the box is really really dirty but here's how you can do it
http://stackoverflow.com/questions/1152946/how-to-have-a-javascript-callback-executed-after-an-update-panel-postback

**Comment by matvez** [comment] 2015-03-05 18:01
On the example below, both alert("pageLoad"); and alert("EndRequestHandler"); work yet the next line $("input[type=date]").trigger("wb-init.wb-date"); does not work :(

<%@ Page Language="C#" MasterPageFile="~/Wet.Usability.Intranet.Master" AutoEventWireup="true" %>

<asp:Content ID="HeadContent" ContentPlaceHolderID="HeadContent" runat="server">
    <script>
    </script>
</asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="server">
    <script>
        function pageLoad() {
            alert("pageLoad");
            $("input[type=date]").trigger("wb-init.wb-date");
        }
    </script>


    <form id="MainForm" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">

            <ContentTemplate>
                <script>
                    //Sys.Application.add_load(dosomething);
                    Sys.WebForms.PageRequestManager.getInstance().add_endRequest(EndRequestHandler);
                    
                    // $().ready(function () {

                    function EndRequestHandler() {
                        alert("EndRequestHandler");
                        $("input[type=date]").trigger("wb-init.wb-date");
                    }

                    //});
                </script>

                <asp:TextBox ID="txtDate" runat="server" Text="" type="date" data-rule-dateISO="true"></asp:TextBox>
                <asp:Button ID="btn" runat="server" OnClick="btn_Click" Text="Button" />
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</asp:Content>

<script language="C#" runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        //Empty
    }
    protected void btn_Click(object sender, EventArgs e)
    {
        //Empty
    }
</script>

**Comment by LaurentGoderre** [comment] 2015-03-05 18:29
Hard to say why without seeing what markup .NET generates

**Comment by LaurentGoderre** [comment] 2015-03-05 18:33
I just tested and that code works perfectly for me. Can you confirm that .NET outputs the form as an input of type date?

**Comment by matvez** [comment] 2015-03-05 18:35
You tested the code in .NET ? here is the txtDate source output:

<input name="ctl00$MainContent$txtDate" id="MainContent_txtDate" type="date" data-rule-dateISO="true" />

**Comment by CalvinRodo** [comment] 2015-03-05 18:48
I can confirm that using type="date" on an Asp.Net text box will output a input with type="date". 
This
````html
<asp:TextBox runat="server" ID="txtFirstDayWorked" data-bind="value: FirstDayWorkedValue" type="date" />
````
Renders as 
````html
<input class="polyfill picker-field" data-role="none" style="<<Removed For Brevity>>" name="ctl00$MainContent$txtFirstDayWorked" value="2015-01-01" id="MainContent_txtFirstDayWorked" data-bind="value: FirstDayWorkedValue" type="date">
````

This is our app running on WET 3, but it does demonstrate an input of type date being rendered properly.

**Comment by LaurentGoderre** [comment] 2015-03-05 20:11
You could try 

```js
alert($("input[type=date]").length);
```

To make sure that the selector works

**Comment by matvez** [comment] 2015-03-05 20:44
The output is "1"

**Comment by LaurentGoderre** [comment] 2015-03-05 21:01
I don't see any reason why this wouldn't work.....

**Comment by nschonni** [comment] 2015-03-05 22:09
.Net and Visual Studio did require patches at one point to actually produce type=date on the input tags.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Laurent GoderreSent: Thursday, March 5, 2015 1:01 PMTo: wet-boew/wet-boewReply To: wet-boew/wet-boewSubject: Re: [wet-boew] polyfill (date picker) and ASP.NET UpdatePanel / date picker issues on ASP.NET UpdatePanel post back  (#6595)I don't see any reason why this wouldn't work.....

—Reply to this email directly or view it on GitHub.

**Comment by hsrudnicki** [comment] 2015-06-15 19:34
Are you ready to close this issue?

**Comment by matvez** [comment] 2015-06-16 12:04
Hi,

Yes you can close this ticket - thanks for the helpDate: Mon, 15 Jun 2015 12:34:17 -0700

**Closed** 2015-06-17 13:35 UTC
Labels: Support Request

**Comment by iBootstrap** [comment] 2016-06-11 07:01
For anyone facing similar issues ...
I had a similar issue with Details/summary polyfill.
Using this thread, I was able to fix my issue.
Instead of : $("input[type=date]").trigger("wb-init.wb-date");
I used : $("summary").trigger("wb-init.wb-details");

Thanks !
