### ISSUE TITLE
Tabbed Interface: Anchors away!

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7111] opened 2015-09-24 13:47 UTC
We are using the tabs on the Canada.ca site and we are seeing a bug with using anchors on a second tab.

Here's a sample of the markup we are trying to use:
http://shawnthompson.github.io/wet-boew/unmin/demos/tabs/tabs-en.html

If you switch to the second tab and click on one of the letters anchors (W), the content above the anchor disappears into the tab.

![image](https://cloud.githubusercontent.com/assets/2575266/10074919/e3735280-62a0-11e5-989e-7d7cc564148b.png)

The first tab panel works fine.

cc/ @therealolivergross

**Comment by andre-gh** [comment] 2015-09-24 18:50
Browsers appear to be scrolling the `overflow: hidden` `.tabpanels` div instead of the body...not sure why they would opt into doing that...it does not appear to be the tab panel code itself scrolling it.

**Comment by pjackson28** [comment] 2015-09-25 14:39
Suggest looking at why the content is overflowing the container. There used to be a problem with horizontal scrolling where some of the Bootstrap classes were used incorrectly, causing a child container to effectively be wider than the parent container (due to negative margins/padding imposed by the Bootstrap class). Perhaps something similar is happening here where negative margins/padding are being imposed causing the child container to be taller than the parent container, resulting in scrolling rather than forcing the parent container to be the same height.

**Comment by andre-gh** [comment] 2015-09-28 15:27
Yeah, something like that, I will do some deep debugging of this later today.  I do not want to break something which was done for a reason though.

**Comment by andre-gh** [comment] 2015-09-28 18:09
Looks like a wb-tabs bug, it appears that the tabs keep an "open" class around despite not being open.  Working on a fix.

**Comment by andre-gh** [comment] 2015-09-28 18:25
Ok, I see the problem, that class was intentional, the idea was to leave it "open" to allow for "fade out" it would appear.  Problem is, fade out effects only visibility in the dom and messes up browser's decisions.  Looking into a correct solution to allow for fade out but not breaking the browser's spatial awareness.

**Comment by andre-gh** [comment] 2015-09-28 19:49
This is very frustrating, there are hacks you can do in css to force a fade out to go to display none after fading like:

        99.9999% { opacity: 0; }

        100% { display: none; }

But I am not sure if we should be doing that or not or if I can fix the issue without fixing how tab fade works.

**Comment by pjackson28** [comment] 2015-09-28 20:50
@andre-gh Oddly enough I can reproduce with IE11 with the link Shawn provided but can't reproduce locally with the latest WET files (couldn't reproduce on IE11, Firefox or Chrome). Are you able to reproduce locally on your side? Locally it is scrolling down to the appropriate location with no clipping issues (tested with the third tab). I wonder what combination is causing this to happen in Shawn's example.

**Comment by andre-gh** [comment] 2015-09-28 20:56
I have been able to reproduce in IE and Firefox.  The important thing about Shawn's example is that his first tab is longer than his second tab.  I have been working in this assumption, it is possible there is something else wrong, I will investigate more tomorrow.

**Comment by LaurentGoderre** [comment] 2015-09-28 21:01
I consistently reproduce it in Firefox 40

**Comment by pjackson28** [comment] 2015-09-28 21:07
@andre-gh It looks like you are right that it only happens if the length of the first tab exceeds the length of the second tab.

**Comment by andre-gh** [comment] 2015-09-28 21:15
I think I will look up tomorrow how this logic is specified in the spec, it is not making sense to me that a browser would handle it this way and yet two different browsers do so....

**Comment by andre-gh** [comment] 2015-09-29 17:50
Fixed via #7120 although I am not totally happy with that fix.  I wish understood why it does not work correctly.

**Closed** 2015-10-21 00:53 UTC
Labels: Awaiting pull request, Plugin: Tabbed Interface/Carousel
