### ISSUE TITLE
Share widget (Pinterest)

### ISSUE THREAD

**Issue by num3thod** [wet-boew/wet-boew#6659] opened 2015-04-01 16:43 UTC
Currently cannot share pages with Pinterest using the Share widget.

Chrome 35
Tested here http://wet-boew.github.io/wet-boew/demos/share/share-en.html

**Comment by pjackson28** [comment] 2015-04-01 17:36
What happens when you try to share? Does it give an error? The more detail you can provide the better as not everyone has a Pinterest account.

**Comment by num3thod** [comment] 2015-04-01 19:10
I get the following modal window:
Oops!
Parameter 'method' (value link) is not one of unknown, uploaded, scraped, bookmarklet, email, iphone, button, ipad, android, android_tablet, api_sdk, extension, api_other, api_bulk_upload, adtech, directpartner, martech, button_external, bad.

**Comment by num3thod** [comment] 2015-04-01 19:11
This SO question seems very similar. Will try the solution and report back.
http://stackoverflow.com/questions/20957665/pinterest-link-on-wordpress-gives-error

**Comment by pjackson28** [comment] 2015-04-01 20:03
Thanks for looking into this. Note that the Share widget pumps out the following URL for Pinterest:
<code>http://www.pinterest.com/pin/create/link/?url={u}&amp;media={i}&amp;description={t}</code>. The <code>{u}</code> gets replaced with the page URL, the <code>{i}</code> gets replaced with the image URL and the <code>{t}</code> gets replaced by the page title.

**Comment by num3thod** [comment] 2015-04-01 20:52
Found the issue, it should now be http://www.pinterest.com/pin/create/button/...

instead of http://www.pinterest.com/pin/create/link/...

Ex: <a href="http://www.pinterest.com/pin/create/button/?url=http%3A%2F%2Ftravel.gc.ca%2F&media=http%3A%2F%2Ftravel.gc.ca%2Fvt%2Fcustom%2Fimages%2Ffb-opengraph-icon.jpg&description=Travel.gc.ca%20-%20Home" class="shr-lnk pinterest btn btn-default gl-share" target="_blank">Pinterest</a>

**Comment by pjackson28** [comment] 2015-04-01 21:02
Glad you found a fix. Could you please submit a PR and test to make sure the fix works as intended?

**Comment by num3thod** [comment] 2015-04-02 14:07
Will do.

**Comment by pjackson28** [comment] 2015-04-10 20:46
Fixed by #6677.

**Closed by pjackson28** 2015-04-10 20:46 UTC
Labels: Plugin: Share widget
