### ISSUE TITLE
Positioning text in table cell

### ISSUE THREAD

**Issue by terribly** [wet-boew/wet-boew#7728] opened 2016-10-31 18:11 UTC
I need to be able to change the positioning of TH and TD cell text so the text aligns to top of cell or middle (rarely bottom). This was the old valign attribute. I cannot seem to do this in WET. Am I missing something?

**Comment by masterbee** [comment] 2016-11-01 03:51
@terribly - by default tables in Bootstrap and WET for that matter are vertical aligned "top". No one has created a vertical style set of utility classes for tables. Interested in doing the P.R for this?

**Comment by EricDunsworth** [comment] 2016-11-02 19:56
Btw this appears to be a duplicate of #6906.

**Comment by LaurentGoderre** [comment] 2016-11-03 12:00
Closing as a duplicate

**Closed by LaurentGoderre** 2016-11-03 12:00 UTC
Labels: awaiting-reply
