### ISSUE TITLE
WET 4 - DataTables - How can I get individual column search working?

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#7169] opened 2015-10-29 20:02 UTC
How can I get DataTables individual column search working inside the WET 4 frame work?

**DataTables documentation/example**
https://datatables.net/examples/api/multi_filter.html

**JSFiddle that proves my code works outside of the WET 4 framework**
https://jsfiddle.net/ay16vnp1/6/

**My WET 4 code**

**HTML**

    <div class="table-responsive">
    
        <table id="example" class="wb-tables table table-bordered table-striped table-condensed small" data-wb-tables='{"info" : false, "filter" : false, "paginate" : false, "order" : [[ 1, "asc" ]], "columnDefs": [{ "orderable" : false, "targets":[0] }] }'>
        
        <thead>
        
            <tr>
            <th rowspan="2" title="Select all" class="text-center"><input class="selectAllCases" type="checkbox" value="" /></th>
            <th rowspan="2" class="">H1</th>
            <th rowspan="2" class="">H2</th>
            <th rowspan="2" class="">H3</th>
            <th rowspan="2" class="">H4</th>
            <th colspan="4" class="">H5</th>
            </tr>
        
            <tr>
            <th class="">H5.1</th>
            <th class="">H5.2</th>
            <th class="">H5.3</th>
            <th class="">H5.4</th>
            </tr>
        
        </thead>
        
        <tfoot>
        
            <tr>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            <th class="bg-default"></th>
            </tr>
        
        </tfoot>
        
        <tbody class="text-middle">
        
            <tr>
            <td class="text-center"><input class="case" type="checkbox" value="" /></td>
            <td>Value1.1</td>
            <td>Value1.2</td>
            <td>Value1.3</td>
            <td>Value1.4</td>
            <td>Value1.5</td>
            <td>Value1.6</td>
            <td>Value1.7</td>
            <td>Value1.8</td>
            </tr>
            
            <tr>
            <td class="text-center"><input class="case" type="checkbox" value="" /></td>
            <td>Value2.1</td>
            <td>Value2.2</td>
            <td>Value2.3</td>
            <td>Value2.4</td>
            <td>Value2.5</td>
            <td>Value2.6</td>
            <td>Value2.7</td>
            <td>Value2.8</td>
            </tr>
            
            <tr>
            <td class="text-center"><input class="case" type="checkbox" value="" /></td>
            <td>Value3.1</td>
            <td>Value3.2</td>
            <td>Value3.3</td>
            <td>Value3.4</td>
            <td>Value3.5</td>
            <td>Value3.6</td>
            <td>Value3.7</td>
            <td>Value3.8</td>
            </tr>
            
            </tbody>
        
        </table>
    
    </div>

**JS**

	$( document ).on( "wb-ready.wb", function( event )  {
	
		// Move tfoot to thead
		$("tfoot").css({"display":"table-header-group"});
	
		// Setup - add a text input to each footer cell
		$('#example tfoot th').each( function () {
			$(this).html( '<input type="text" class="form-control width100 fnt-wght-nrml" />' );
		});
	
		var table = $('#example').DataTable();
	
		table.columns().every(function() {
			var that = this;
			$('input',this.footer()).on('keyup change', function() {
				if (that.search() !== this.value) {
					that.search(this.value).draw();
				}
			});
		});
			
	});

**Comment by pjackson28** [comment] 2015-10-29 20:54
@wilkmit It's because you are using DataTable() instead of dataTable().api() to get the reference to the API. You use the first one if the DataTables instance is not already initialized while you use the second one when it is already initialized. Since WET initializes the DataTables instance for you, you need to use dataTable().api() to get the API reference that you are looking for. You can find out more here: https://datatables.net/reference/api/.

Also note that you need to have a label (using the <code>label</code> element) for those input fields you are adding to meet accessibility requirements (which could be safely hidden using the <code>wb-inv</code> class if you don't want the label to be visible).

**Comment by wilkmit** [comment] 2015-11-18 13:57
This would have been much simpler to implement using the datatables plugin separate to the WET 4.0 template. Could you look into making this function of datatables easier to use. 

Maybe allow both the wb-tables class and the JASON array approach and the all JS approach. Or allow all the functionality of datatables to be to be controlled by the wb-tables class and the JASON array. This is just a suggestion for a future release of WET. 

Thanks for the help.

**Comment by pjackson28** [comment] 2015-11-18 14:26
@wilkmit The challenge is we need to introduce accessibility and other enhancements which is why having the datatables plugin separate isn't viable (the plugin on it's own does not meet GC requirements). A future version of the framework may make it a little bit easier but I don't think it will allow carte-blanche initialization like you are asking for. Even then, you already have full API access with <code>.dataTable({ "retrieve": true }).api()</code>, the only challenge you seem to be encountering is that you are used to using the constructor (<code>.DataTable()</code> to get a new instance to the API rather than retrieving the existing instance <code>.dataTable({ "retrieve": true }).api()</code>. It only means a slight change to one of your lines of code above (changing <code>.DataTable()</code> to <code>.dataTable({ "retrieve": true }).api()</code>). Ideally DataTables would check to see if an instance already existed when using (<code>.DataTable()</code>) but unfortunately it only does that with <code>.dataTable({ "retrieve": true }).api()</code> and just throws an error for <code>.DataTable()</code> if an instance already exists.

**Comment by johnpalaganas** [comment] 2015-11-24 15:44
@pjackson28 What are the accessibility issues when using the Datatable plugin separately?

**Comment by pjackson28** [comment] 2015-11-24 19:50
@johnpalaganas Off the top of my head, here are some of the changes:

* Implementing the i18n label/message support
* Fixing the positioning and order of DataTable features (since they were causing user confusion)
* Fixing the accessibility issues with the pagination buttons
* Fixing French and other non-English character support for sorting and filtering
* Fixing the sorting icons/buttons
* Fixing contrast and colour issues
* Switching image-based icons to text-based icons (for scalability/accessibility reasons)

**Comment by johnpalaganas** [comment] 2015-11-24 21:08
@pjackson28 Thank you!

**Comment by hsrudnicki** [comment] 2016-01-13 21:02
@wilkmit @johnpalaganas : Based on the answers/comments from @pjackson28 can be this issue closed as resolved/fixed or if otherwise?  Please update this issue's status, thank you

**Comment by RobJohnston** [comment] 2016-04-01 15:27
Just noticed that this is a duplicate of #6748.  I put instructions to get it to work in that issue.

**Closed** 2016-04-01 15:35 UTC
