### ISSUE TITLE
Input type=date (visual) off by one error

### ISSUE THREAD

**Issue by chyne** [wet-boew/wet-boew#7246] opened 2015-12-04 15:22 UTC
If you select a date in the date picker and then go back to try to select another date, the date highlighted is off by one day from the previous selection.

I've seen this behaviour in both Firefox and IE 11, and occurs both locally and on the WET demos.

**Comment by LaurentGoderre** [comment] 2016-01-05 14:20
Duplicate of #6744 and will be addressed by #6606

**Closed by LaurentGoderre** 2016-01-05 14:20 UTC
Labels: Polyfill: Date picker
