### ISSUE TITLE
Form validation: wet-boew.js error

### ISSUE THREAD

**Issue by denis-tessier** [wet-boew/wet-boew#7363] opened 2016-01-29 14:28 UTC
Hi,

I am working on a calculator which contains 3 fields that are all mandatory, so I want to add validation. I added the "wb-frmvld" DIV around the form, have added the required="required" attribute to all 3 fields, and have added the following jQuery to be triggered on the "Calculate" button click (since it is not a submit button, the "Calculate" button click just calls a JavaScript function which does the calculation): 
'
    $('#calculate').on('click', function() {
        $("#calc").valid();
    });
'

However, I am having a couple of issues: 
1- Every time one of the 3 input fields loses focus (or when the "Calculate" button is clicked), the following error occurs: 
Uncaught TypeError: Cannot read property 'detach' of undefined
p.validate.showErrors @ wet-boew.js:6156
a.extend.showErrors @ jquery.validate.min.js:9
a.extend.element @ jquery.validate.min.js:9
a.extend.defaults.onfocusout @ jquery.validate.min.js:9
b @ jquery.validate.min.js:9
(anonymous function) @ jquery.validate.min.js:9
jQuery.event.dispatch @ jquery.js:4435
elemData.handle @ jquery.js:4121
jQuery.event.trigger @ jquery.js:4350
jQuery.event.simulate @ jquery.js:4652
handler @ jquery.js:4780
2wet-boew.js:6156 

The error occurs on this line: 
wet-boew.js line 6156: $summaryContainer.detach();

2- The error message stays on the page even after the issue has been rectified and the button re-clicked: 
The form could not be submitted because 1 error was found.
Error 1: Field Name 3 - This field is required.

Can you please let me know if there is something I am not setting up properly or something I am doing wrong, as I followed the WET instructions for the Form validation tool... 

Thank you, 

Denis Tessier

**Comment by LaurentGoderre** [comment] 2016-01-29 19:48
Duplicate of #7304

**Closed by LaurentGoderre** 2016-01-29 19:48 UTC

**Comment by denis-tessier** [comment] 2016-01-29 20:30
Hi Laurent,

I replaced the $summaryContainer.detach(); line in the wet-boew.js line
6156 in my localhost, and I am getting the same error, and the same
problem.

line 6156 in my localhost wet-boew.js: $form.find( "#" + errorFormId ).
detach();

The error at the top of the page stays even after the problem is corrected
and the "Calculate" button is clicked again... Am I missing something?

Please advise... Thank you,

Denis Tessier
