### ISSUE TITLE
ISO date validation not working properly in IE and Chrome

### ISSUE THREAD

**Issue by fahmyr** [wet-boew/wet-boew#8112] opened 2017-08-14 15:11 UTC
As per the demo form validation.
http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

<input class="form-control" id="date1" name="date1" type="date" data-rule-dateISO="true" />

using IE 11, or latest chrome. Entry the date 2017-11-31, which is invalid, will not trigger an invalid date error. This is only an issue if you provide a 31 for any month that only has 30 days, or 29, 30, 31 for February that is not a leap year.

Works fine in firefox by the way.

The invalid date is allowed to propagate which eventually causes a system exception when the date is evaluated by the C# code.
![date](https://user-images.githubusercontent.com/5008215/29277888-0b0e6b30-80e1-11e7-9292-c59d16396544.PNG)

**Comment by nschonni** [comment] 2017-08-14 16:44
Duplicate of #6878

**Closed by nschonni** 2017-08-14 16:44 UTC
