### ISSUE TITLE
Issue with the browser back button

### ISSUE THREAD

**Issue by shenghuang** [wet-boew/wet-boew#7718] opened 2016-10-27 19:39 UTC
We have a WET3 application, whose workflow will be broken when the browser back button is clicked.

Does WET have a mechanism for back button interaction e.g. displaying a warning message then redirecting to the start page of the workflow, disallowing back button clicks, or another way that meets the accessibility standard? Please advise.

Thanks,
Sheng

**Comment by masterbee** [comment] 2016-10-28 02:25
@shenghuang - this is a bit of a tricky question since there are some nuances to your question. So lets see if I can help.

Playing with the back button start to get into some native browser functionality which historically has been a bit difficult to implement consistently across all browsers. HTML5 does give us the history API which now allows us to program this history with still some issues with `popstate` in IE. 

If memory serves WET3 pre-dates HTML5 so it is probably unlikely that it leveraged the [History API](http://caniuse.com/#feat=history), and after a quick scan there was reference to any of the plugins leveraging ```window.onbeforeunload``` which was the common method to try to play with back button type events. So I am not sure there is anything in WET3.0 or WET 3.1 that could be leveraged as model.

That said, trying to change the expected behavior of browser functionality also starts to become a bit of a slippery slope since WCAG 2.0 https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html reminds us that it is important for people with disabilities often find it confusing when websites and applications change behaviors of tools unexpectedly.

Let me know if this helps,

**Comment by kodecount** [comment] 2016-10-28 11:32
@shenghuang Personally don't think WET should ever have this type of mechanism, but anyhow here are some great topics on this subject:

http://stackoverflow.com/questions/665399/how-do-i-stop-the-back-and-refresh-buttons-from-resubmitting-my-form
http://stackoverflow.com/questions/12381563/how-to-stop-browser-back-button-using-javascript
http://stackoverflow.com/questions/39932944/disable-browser-back-action-using-jquery
http://blog.55minutes.com/2011/10/how-to-defeat-the-browser-back-button-cache/

**Comment by masterbee** [comment] 2016-10-28 12:27
@kodecount have a tendency to agree for the most past but not opposed to exploring some irons at having a mechanism to warn users of actions if things like back buttons that can lead to data loss and so forth. I just don't think changing it expected destination is a good idea, but personally enjoyed a bit of nagging from webpages from time to time when I was about to loss data for action and it was not apparent.

@shenghaung closing the issue since there is some healthy information about he topic. Feel free to re-open if something is not clear

**Closed by masterbee** 2016-10-28 12:27 UTC

**Comment by shenghuang** [comment] 2016-10-28 16:35
Thanks for the info. I also think changing expected destination isn't a good idea and having a warning mechanism could help. I am going to close the request.

**Comment by kodecount** [comment] 2016-10-28 16:41
@shenghuang @masterbee As for the message it my understanding in most modern browser you can't stop the [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) or [onunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunload) but with `onbeforeunload` you can use an alert (example in the link) to tell the user if they leave the page the data be lost. 

On another not must browsers are removing the ability to send a custom message and you'll be stuck with the default message the browsers thinks is correct.

**Comment by kodecount** [comment] 2016-10-28 16:54
Great example is even Google uses the method of letting the browser handle it with an `onbeforeunload` event:

![demo](https://cloud.githubusercontent.com/assets/22446865/19814734/f59d851a-9d15-11e6-8ee8-39ea01fa42f1.png)

**Comment by kodecount** [comment] 2016-10-28 16:56
Also another approach not sure if discus in the links is having the page open on a new tab or window.
