### ISSUE TITLE
Feedback Form (WET 4.x)

### ISSUE THREAD

**Issue by tbuhler** [wet-boew/wet-boew#6671] opened 2015-04-09 14:27 UTC
I am setting up a form using the feedback form example and I noticed that if I have JavaScript disabled in the browser the form and inputs disappear (this happens in the working example). Is there a solution for this issue?

**Comment by LaurentGoderre** [comment] 2015-04-09 14:34
This is by design. The solution relies on JavaScript and therefore replaces the form with alternate ways to send feedback (mail or phone)

**Comment by LaurentGoderre** [comment] 2015-04-21 20:49
@tbuhler did this answer your question?

**Comment by hsrudnicki** [comment] 2015-06-17 14:31
@tbuhler @LaurentGoderre : Can this issue be closed?

**Comment by pjackson28** [comment] 2015-06-17 16:26
Closing since the question was answered.

**Closed by pjackson28** 2015-06-17 16:26 UTC
Labels: Content: Feedback Form
